// Code generated by Plystra CLI. DO NOT EDIT.

import {
  createRuntime,
  hasOwn,
  invoke,
  isPlainObject,
  PlystraError,
  type ClientOptions,
  type RequestOptions,
  type Runtime,
} from "../../../runtime.js";

export const capabilityID = "alpha.beta/v1";
export const contractDigest = "sha256:570f299106e1a66a1c0d760720a54cbcf9054b763f38bc41ba65fe89e4dc1f26";
const routePath = "api/v1/capabilities/alpha.beta/v1/invoke";

export type Request = Readonly<Record<string, never>>;

export type Response = Readonly<Record<string, never>>;

export type ErrorCode = never;

function isRequest(value: unknown): value is Request {
  return (
    isPlainObject(value) &&
    Object.keys(value).length === 0
  );
}

function isResponse(value: unknown): value is Response {
  return (
    isPlainObject(value) &&
    Object.keys(value).length === 0
  );
}

export type Operation = (
  request: Request,
  options?: RequestOptions,
) => Promise<Response>;

export function bindOperation(runtime: Runtime): Operation {
  return async (request, options = {}) => {
    let requestIsValid = false;
    try {
      requestIsValid = isRequest(request);
    } catch {
      requestIsValid = false;
    }
    if (!requestIsValid) {
      throw new TypeError("request does not match alpha.beta/v1");
    }
    const response = await invoke(runtime, routePath, request, options);
    if (!isResponse(response)) {
      throw new PlystraError(200, "invalid_response");
    }
    return response;
  };
}

export function createOperation(options: ClientOptions): Operation {
  return bindOperation(createRuntime(options));
}
