package javascriptgen

const runtimeSource = `// Code generated by Plystra CLI. DO NOT EDIT.

import {
  fromJson,
  toBinary,
  toJson,
  type DescMessage,
  type DescMethodUnary,
  type JsonValue as ProtobufJSONValue,
  type MessageShape,
} from "@bufbuild/protobuf";
import { Code, ConnectError, type Transport } from "@connectrpc/connect";
import { createConnectTransport } from "@connectrpc/connect-web";

const maximumPayloadBytes = 1_048_576;
const maximumCredentialBytes = 65_536;
const maximumJSONDepth = 64;
const minimumSignedInteger = -9_223_372_036_854_775_808n;
const maximumSignedInteger = 9_223_372_036_854_775_807n;
const plystraErrorDetailType = "plystra.generated.transport.v1.PlystraErrorDetail";
const maximumTraceIDBytes = 128;

export type Awaitable<T> = T | PromiseLike<T>;
export type JSONPrimitive = string | number | boolean | null;
export type JSONValue =
  | JSONPrimitive
  | { readonly [key: string]: JSONValue }
  | readonly JSONValue[];

export interface ClientOptions {
  readonly baseUrl: string | URL;
  /** Returns the raw access token; Plystra adds the Bearer authorization scheme. */
  readonly getAccessToken?: () => Awaitable<string | null | undefined>;
  readonly fetch?: typeof globalThis.fetch;
}

export interface RequestOptions {
  readonly signal?: AbortSignal;
}

export type KernelErrorClass =
  | "invalid_argument"
  | "not_found"
  | "conflict"
  | "denied"
  | "unauthenticated"
  | "unavailable"
  | "timeout"
  | "cancelled"
  | "result_unknown"
  | "internal"
  | "version_incompatible";

interface PlystraErrorDetailBase {
  readonly requestedCapabilityID: string;
  readonly canonicalCapabilityID: string;
  readonly traceID?: string;
}

export type PlystraErrorDetail = Readonly<
  PlystraErrorDetailBase &
    (
      | {
          readonly semanticErrorCode: string;
          readonly kernelErrorClass?: never;
        }
      | {
          readonly semanticErrorCode?: never;
          readonly kernelErrorClass: KernelErrorClass;
        }
    )
>;

export class PlystraError extends Error {
  readonly status: number;
  readonly code: string;
  readonly detail: PlystraErrorDetail | undefined;

  constructor(status: number, code: string, detail?: PlystraErrorDetail) {
    super(code);
    this.name = "PlystraError";
    this.status = status;
    this.code = code;
    this.detail =
      detail === undefined
        ? undefined
        : (Object.freeze({ ...detail }) as PlystraErrorDetail);
  }
}

/** @internal */
export type FieldKind =
  | "string"
  | "integer"
  | "number"
  | "boolean"
  | "object"
  | "array";

/** @internal */
export interface EnumCodec {
  readonly canonical: string | bigint | number | boolean;
  readonly protobufName: string;
}

/** @internal */
export interface FieldCodec {
  readonly canonicalName: string;
  readonly protobufJSONName: string;
  readonly kind: FieldKind;
  readonly items?: Exclude<FieldKind, "array">;
  readonly required: boolean;
  readonly enum?: readonly EnumCodec[];
}

/** @internal */
export interface MessageCodec {
  readonly fields: readonly FieldCodec[];
}

/** @internal */
export interface ErrorContract {
  readonly requestedCapabilityID: string;
  readonly canonicalCapabilityID: string;
  readonly semanticErrorCodes: readonly string[];
  readonly detailDescriptor: DescMessage;
}

/** @internal */
export interface Runtime {
  readonly transport: Transport;
  readonly getAccessToken:
    | (() => Awaitable<string | null | undefined>)
    | undefined;
}

/** @internal */
export function createRuntime(options: ClientOptions): Runtime {
  if (options === null || typeof options !== "object") {
    throw new TypeError("Plystra client options must be an object");
  }
  const baseUrl = normalizeBaseUrl(options.baseUrl);
  const fetcher = options.fetch ?? globalThis.fetch;
  if (typeof fetcher !== "function") {
    throw new TypeError("Plystra client requires a Fetch-compatible function");
  }
  if (
    options.getAccessToken !== undefined &&
    typeof options.getAccessToken !== "function"
  ) {
    throw new TypeError("getAccessToken must be a function");
  }
  const transportFetch: typeof globalThis.fetch = (input, init) =>
    fetcher(input, {
      ...init,
      cache: "no-store",
      credentials: "same-origin",
      redirect: "error",
    });
  return Object.freeze({
    transport: createConnectTransport({
      baseUrl: connectBaseUrl(baseUrl),
      useBinaryFormat: true,
      fetch: transportFetch,
    }),
    getAccessToken: options.getAccessToken,
  });
}

/** @internal */
export async function invoke(
  runtime: Runtime,
  method: DescMethodUnary,
  requestCodec: MessageCodec,
  responseCodec: MessageCodec,
  errorContract: ErrorContract,
  request: unknown,
  options: RequestOptions,
): Promise<unknown> {
  if (signalAborted(options.signal)) {
    throw new PlystraError(0, "cancelled");
  }

  let requestMessage: MessageShape<typeof method.input>;
  try {
    requestMessage = encodeMessage(method.input, requestCodec, request);
    if (toBinary(method.input, requestMessage).byteLength > maximumPayloadBytes) {
      throw new RangeError("request exceeds the 1 MiB transport limit");
    }
  } catch (error) {
    if (error instanceof RangeError) {
      throw error;
    }
    throw new TypeError("request cannot be encoded for the generated Connect contract");
  }

  const headers = new Headers();
  if (runtime.getAccessToken !== undefined) {
    let token: string | null | undefined;
    try {
      token = await runtime.getAccessToken();
    } catch {
      throw new PlystraError(0, "credential_error");
    }
    if (token !== null && token !== undefined && token !== "") {
      if (
        typeof token !== "string" ||
        token.trim() !== token ||
        /[\u0000-\u001f\u007f]/.test(token) ||
        new TextEncoder().encode(token).byteLength > maximumCredentialBytes
      ) {
        throw new TypeError("getAccessToken returned an invalid credential");
      }
      if (/^Bearer(?: |$)/i.test(token)) {
        throw new TypeError(
          "getAccessToken must return the raw token without the Bearer scheme",
        );
      }
      headers.set("Authorization", "Bearer " + token);
    }
  }

  let responseMessage: MessageShape<typeof method.output>;
  try {
    const response = await runtime.transport.unary(
      method,
      options.signal,
      undefined,
      headers,
      requestMessage,
    );
    responseMessage = response.message;
  } catch (error) {
    if (signalAborted(options.signal)) {
      throw new PlystraError(0, "cancelled");
    }
    throw normalizeTransportError(error, errorContract);
  }

  try {
    return decodeMessage(method.output, responseCodec, responseMessage);
  } catch {
    throw new PlystraError(200, "invalid_response");
  }
}

/** @internal */
export function hasOwn(
  value: Readonly<Record<string, unknown>>,
  key: string,
): boolean {
  return Object.prototype.hasOwnProperty.call(value, key);
}

/** @internal */
export function isPlainObject(
  value: unknown,
): value is Readonly<Record<string, unknown>> {
  if (value === null || typeof value !== "object" || Array.isArray(value)) {
    return false;
  }
  try {
    const prototype = Object.getPrototypeOf(value);
    return prototype === Object.prototype || prototype === null;
  } catch {
    return false;
  }
}

/** @internal */
export function isJSONValue(value: unknown): value is JSONValue {
  return isJSONValueAtDepth(value, 0, new Set<object>());
}

/** @internal */
export function isSignedInteger(value: unknown): value is bigint {
  return (
    typeof value === "bigint" &&
    value >= minimumSignedInteger &&
    value <= maximumSignedInteger
  );
}

/** @internal */
export function isStringWithinUnicodeScalarBounds(
  value: unknown,
  minimum: number | undefined,
  maximum: number | undefined,
): value is string {
  if (typeof value !== "string") {
    return false;
  }
  let length = 0;
  for (let index = 0; index < value.length; index++) {
    const codeUnit = value.charCodeAt(index);
    if (codeUnit >= 0xd800 && codeUnit <= 0xdbff) {
      const next = value.charCodeAt(index + 1);
      if (!(next >= 0xdc00 && next <= 0xdfff)) {
        return false;
      }
      index++;
    } else if (codeUnit >= 0xdc00 && codeUnit <= 0xdfff) {
      return false;
    }
    length++;
    if (maximum !== undefined && length > maximum) {
      return false;
    }
  }
  return minimum === undefined || length >= minimum;
}

function encodeMessage<Desc extends DescMessage>(
  descriptor: Desc,
  codec: MessageCodec,
  value: unknown,
): MessageShape<Desc> {
  if (!isPlainObject(value)) {
    throw new TypeError("request must be an object");
  }
  const json: { [key: string]: ProtobufJSONValue } = {};
  for (const field of codec.fields) {
    if (!hasOwn(value, field.canonicalName)) {
      if (field.required) {
        throw new TypeError("required request field is absent");
      }
      continue;
    }
    json[field.protobufJSONName] = encodeField(field, value[field.canonicalName]);
  }
  return fromJson(descriptor, json, {
    ignoreUnknownFields: false,
    recursionLimit: maximumJSONDepth,
  });
}

function encodeField(field: FieldCodec, value: unknown): ProtobufJSONValue {
  if (field.enum !== undefined) {
    const member = field.enum.find((candidate) =>
      Object.is(candidate.canonical, value),
    );
    if (member === undefined) {
      throw new TypeError("request enum is invalid");
    }
    return member.protobufName;
  }
  switch (field.kind) {
    case "string":
      if (typeof value !== "string") throw new TypeError("request string is invalid");
      return value;
    case "integer":
      if (!isSignedInteger(value)) {
        throw new TypeError("request integer is invalid");
      }
      return value.toString();
    case "number":
      if (typeof value !== "number" || !Number.isFinite(value)) {
        throw new TypeError("request number is invalid");
      }
      return value;
    case "boolean":
      if (typeof value !== "boolean") throw new TypeError("request boolean is invalid");
      return value;
    case "object":
      if (!isPlainObject(value) || !isJSONValue(value)) {
        throw new TypeError("request object is invalid");
      }
      return cloneJSONValue(value);
    case "array":
      if (!Array.isArray(value) || field.items === undefined) {
        throw new TypeError("request array is invalid");
      }
      const itemKind = field.items;
      return {
        values: value.map((item) => encodeArrayItem(itemKind, item)),
      };
  }
}

function encodeArrayItem(
  kind: Exclude<FieldKind, "array">,
  value: unknown,
): ProtobufJSONValue {
  switch (kind) {
    case "string":
      if (typeof value !== "string") throw new TypeError("request array item is invalid");
      return value;
    case "integer":
      if (!isSignedInteger(value)) {
        throw new TypeError("request array item is invalid");
      }
      return value.toString();
    case "number":
      if (typeof value !== "number" || !Number.isFinite(value)) {
        throw new TypeError("request array item is invalid");
      }
      return value;
    case "boolean":
      if (typeof value !== "boolean") throw new TypeError("request array item is invalid");
      return value;
    case "object":
      if (!isPlainObject(value) || !isJSONValue(value)) {
        throw new TypeError("request array item is invalid");
      }
      return cloneJSONValue(value);
  }
}

function decodeMessage<Desc extends DescMessage>(
  descriptor: Desc,
  codec: MessageCodec,
  message: MessageShape<Desc>,
): unknown {
  const json = toJson(descriptor, message, {
    alwaysEmitImplicit: true,
    enumAsInteger: false,
    useProtoFieldName: false,
  });
  if (!isPlainObject(json)) {
    throw new TypeError("response is not an object");
  }
  const known = new Set(codec.fields.map((field) => field.protobufJSONName));
  if (!Object.keys(json).every((key) => known.has(key))) {
    throw new TypeError("response contains an unknown field");
  }
  const result: Record<string, unknown> = {};
  for (const field of codec.fields) {
    if (!hasOwn(json, field.protobufJSONName)) {
      if (field.required) {
        throw new TypeError("required response field is absent");
      }
      continue;
    }
    result[field.canonicalName] = decodeField(
      field,
      json[field.protobufJSONName],
    );
  }
  return result;
}

function decodeField(field: FieldCodec, value: unknown): unknown {
  if (field.enum !== undefined) {
    if (typeof value !== "string") {
      throw new TypeError("response enum is invalid");
    }
    const member = field.enum.find(
      (candidate) => candidate.protobufName === value,
    );
    if (member === undefined) {
      throw new TypeError("response enum is unknown");
    }
    return member.canonical;
  }
  switch (field.kind) {
    case "string":
      if (typeof value !== "string") throw new TypeError("response string is invalid");
      return value;
    case "integer":
      return decodeInteger(value);
    case "number":
      if (typeof value !== "number" || !Number.isFinite(value)) {
        throw new TypeError("response number is invalid");
      }
      return value;
    case "boolean":
      if (typeof value !== "boolean") throw new TypeError("response boolean is invalid");
      return value;
    case "object":
      if (!isPlainObject(value) || !isJSONValue(value)) {
        throw new TypeError("response object is invalid");
      }
      return cloneJSONValue(value);
    case "array": {
      if (!isPlainObject(value) || field.items === undefined) {
        throw new TypeError("response array wrapper is invalid");
      }
      const itemKind = field.items;
      const values = value["values"];
      if (
        Object.keys(value).some((key) => key !== "values") ||
        !Array.isArray(values)
      ) {
        throw new TypeError("response array wrapper is invalid");
      }
      return values.map((item) => decodeArrayItem(itemKind, item));
    }
  }
}

function decodeArrayItem(
  kind: Exclude<FieldKind, "array">,
  value: unknown,
): unknown {
  switch (kind) {
    case "string":
      if (typeof value !== "string") throw new TypeError("response array item is invalid");
      return value;
    case "integer":
      return decodeInteger(value);
    case "number":
      if (typeof value !== "number" || !Number.isFinite(value)) {
        throw new TypeError("response array item is invalid");
      }
      return value;
    case "boolean":
      if (typeof value !== "boolean") throw new TypeError("response array item is invalid");
      return value;
    case "object":
      if (!isPlainObject(value) || !isJSONValue(value)) {
        throw new TypeError("response array item is invalid");
      }
      return cloneJSONValue(value);
  }
}

function decodeInteger(value: unknown): bigint {
  let decoded: bigint;
  try {
    if (typeof value === "string" && /^-?(?:0|[1-9][0-9]*)$/.test(value)) {
      decoded = BigInt(value);
    } else if (typeof value === "bigint") {
      decoded = value;
    } else if (typeof value === "number" && Number.isSafeInteger(value)) {
      decoded = BigInt(value);
    } else {
      throw new TypeError("response integer is invalid");
    }
  } catch {
    throw new TypeError("response integer is invalid");
  }
  if (!isSignedInteger(decoded)) {
    throw new TypeError("response integer is outside the signed 64-bit range");
  }
  return decoded;
}

function normalizeBaseUrl(input: string | URL): URL {
  let result: URL;
  try {
    result = new URL(typeof input === "string" ? input : input.href);
  } catch {
    throw new TypeError("baseUrl must be an absolute HTTP or HTTPS URL");
  }
  if (
    (result.protocol !== "http:" && result.protocol !== "https:") ||
    result.username !== "" ||
    result.password !== "" ||
    result.search !== "" ||
    result.hash !== ""
  ) {
    throw new TypeError(
      "baseUrl must be an absolute HTTP or HTTPS URL without credentials, query, or fragment",
    );
  }
  if (!result.pathname.endsWith("/")) {
    result.pathname += "/";
  }
  return result;
}

function connectBaseUrl(value: URL): string {
  return value.href.endsWith("/") ? value.href.slice(0, -1) : value.href;
}

function normalizeTransportError(
  error: unknown,
  contract: ErrorContract,
): PlystraError {
  try {
    if (!(error instanceof ConnectError)) {
      return new PlystraError(0, "network_error");
    }
    if (error.code === Code.Unknown && error.details.length === 0) {
      return new PlystraError(0, "network_error");
    }
    const detail = decodeSafeErrorDetail(error, contract);
    if (detail === undefined) {
      return new PlystraError(500, "internal");
    }
    if (detail.semanticErrorCode !== undefined) {
      return new PlystraError(422, "capability_error", detail);
    }
    return kernelPlystraError(detail.kernelErrorClass, detail);
  } catch {
    return new PlystraError(500, "internal");
  }
}

function decodeSafeErrorDetail(
  error: ConnectError,
  contract: ErrorContract,
): PlystraErrorDetail | undefined {
  if (
    contract.detailDescriptor.typeName !== plystraErrorDetailType ||
    contract.requestedCapabilityID === "" ||
    contract.canonicalCapabilityID === "" ||
    error.details.length !== 1
  ) {
    return undefined;
  }
  const semanticErrorCodes = new Set(contract.semanticErrorCodes);
  if (
    semanticErrorCodes.size !== contract.semanticErrorCodes.length ||
    [...semanticErrorCodes].some((value) => value === "")
  ) {
    return undefined;
  }
  const messages = error.findDetails(contract.detailDescriptor);
  if (messages.length !== 1) {
    return undefined;
  }
  const message = messages[0];
  if (
    message === undefined ||
    (message.$unknown !== undefined && message.$unknown.length !== 0)
  ) {
    return undefined;
  }
  const json = toJson(contract.detailDescriptor, message, {
    alwaysEmitImplicit: true,
    enumAsInteger: false,
    useProtoFieldName: true,
  });
  if (
    !isPlainObject(json) ||
    Object.keys(json).length !== 5 ||
    !hasOwn(json, "requested_interface_id") ||
    !hasOwn(json, "canonical_interface_id") ||
    !hasOwn(json, "semantic_error_code") ||
    !hasOwn(json, "kernel_error_class") ||
    !hasOwn(json, "trace_id")
  ) {
    return undefined;
  }
  const requestedCapabilityID = json["requested_interface_id"];
  const canonicalCapabilityID = json["canonical_interface_id"];
  const semanticErrorCode = json["semantic_error_code"];
  const kernelErrorClass = json["kernel_error_class"];
  const traceID = json["trace_id"];
  if (
    typeof requestedCapabilityID !== "string" ||
    typeof canonicalCapabilityID !== "string" ||
    typeof semanticErrorCode !== "string" ||
    typeof kernelErrorClass !== "string" ||
    typeof traceID !== "string" ||
    requestedCapabilityID !== contract.requestedCapabilityID ||
    canonicalCapabilityID !== contract.canonicalCapabilityID ||
    !validTraceID(traceID) ||
    (semanticErrorCode === "") === (kernelErrorClass === "")
  ) {
    return undefined;
  }
  const trace = traceID === "" ? {} : { traceID };
  if (semanticErrorCode !== "") {
    if (
      error.code !== Code.FailedPrecondition ||
      !semanticErrorCodes.has(semanticErrorCode)
    ) {
      return undefined;
    }
    return Object.freeze({
      requestedCapabilityID,
      canonicalCapabilityID,
      semanticErrorCode,
      ...trace,
    });
  }
  if (
    !isKernelErrorClass(kernelErrorClass) ||
    error.code !== connectCodeForKernelError(kernelErrorClass)
  ) {
    return undefined;
  }
  return Object.freeze({
    requestedCapabilityID,
    canonicalCapabilityID,
    kernelErrorClass,
    ...trace,
  });
}

function isKernelErrorClass(value: string): value is KernelErrorClass {
  switch (value) {
    case "invalid_argument":
    case "not_found":
    case "conflict":
    case "denied":
    case "unauthenticated":
    case "unavailable":
    case "timeout":
    case "cancelled":
    case "result_unknown":
    case "internal":
    case "version_incompatible":
      return true;
    default:
      return false;
  }
}

function connectCodeForKernelError(value: KernelErrorClass): Code {
  switch (value) {
    case "invalid_argument":
      return Code.InvalidArgument;
    case "not_found":
      return Code.NotFound;
    case "conflict":
      return Code.Aborted;
    case "denied":
      return Code.PermissionDenied;
    case "unauthenticated":
      return Code.Unauthenticated;
    case "unavailable":
    case "result_unknown":
      return Code.Unavailable;
    case "timeout":
      return Code.DeadlineExceeded;
    case "cancelled":
      return Code.Canceled;
    case "version_incompatible":
      return Code.Unimplemented;
    case "internal":
      return Code.Internal;
  }
}

function kernelPlystraError(
  code: KernelErrorClass,
  detail: PlystraErrorDetail,
): PlystraError {
  switch (code) {
    case "invalid_argument":
      return new PlystraError(400, code, detail);
    case "not_found":
      return new PlystraError(404, code, detail);
    case "conflict":
      return new PlystraError(409, code, detail);
    case "denied":
      return new PlystraError(403, code, detail);
    case "unauthenticated":
      return new PlystraError(401, code, detail);
    case "unavailable":
    case "result_unknown":
      return new PlystraError(503, code, detail);
    case "timeout":
      return new PlystraError(504, code, detail);
    case "cancelled":
      return new PlystraError(0, code, detail);
    case "version_incompatible":
      return new PlystraError(501, code, detail);
    case "internal":
      return new PlystraError(500, code, detail);
  }
}

function validTraceID(value: string): boolean {
  return (
    value === "" ||
    (value.length <= maximumTraceIDBytes &&
      /^[A-Za-z0-9][A-Za-z0-9._:-]*$/.test(value))
  );
}

function signalAborted(signal: AbortSignal | undefined): boolean {
  return signal?.aborted === true;
}

function cloneJSONValue(value: JSONValue): ProtobufJSONValue {
  if (
    value === null ||
    typeof value === "string" ||
    typeof value === "number" ||
    typeof value === "boolean"
  ) {
    return value;
  }
  if (Array.isArray(value)) {
    return value.map((item) => cloneJSONValue(item));
  }
  const result: { [key: string]: ProtobufJSONValue } = {};
  for (const [key, item] of Object.entries(value)) {
    result[key] = cloneJSONValue(item);
  }
  return result;
}

function isJSONValueAtDepth(
  value: unknown,
  depth: number,
  ancestors: Set<object>,
): value is JSONValue {
  switch (typeof value) {
    case "string":
    case "boolean":
      return true;
    case "number":
      return (
        Number.isFinite(value) &&
        (!Number.isInteger(value) || Number.isSafeInteger(value))
      );
    case "object":
      if (value === null) {
        return true;
      }
      break;
    default:
      return false;
  }
  if (depth >= maximumJSONDepth || ancestors.has(value)) {
    return false;
  }
  ancestors.add(value);
  try {
    if (Array.isArray(value)) {
      return value.every((item) =>
        isJSONValueAtDepth(item, depth + 1, ancestors),
      );
    }
    if (!isPlainObject(value)) {
      return false;
    }
    return Object.values(value).every((item) =>
      isJSONValueAtDepth(item, depth + 1, ancestors),
    );
  } catch {
    return false;
  } finally {
    ancestors.delete(value);
  }
}
`
