// Code generated by Plystra CLI. DO NOT EDIT.

import {
  createRuntime,
  hasOwn,
  invoke,
  isPlainObject,
  PlystraError,
  type ClientOptions,
  type RequestOptions,
  type Runtime,
} from "../../../runtime.js";

export const capabilityID = "foo.bar-send/v1";
export const contractDigest = "sha256:0203205b8651a604925db9af60394d2f3272bd9d5cb969bb87cc6c5594831c4e";
const routePath = "api/v1/capabilities/foo.bar-send/v1/invoke";

export type Request = Readonly<Record<string, never>>;

export type Response = Readonly<Record<string, never>>;

export type ErrorCode = never;

function isRequest(value: unknown): value is Request {
  return (
    isPlainObject(value) &&
    Object.keys(value).length === 0
  );
}

function isResponse(value: unknown): value is Response {
  return (
    isPlainObject(value) &&
    Object.keys(value).length === 0
  );
}

export type Operation = (
  request: Request,
  options?: RequestOptions,
) => Promise<Response>;

export function bindOperation(runtime: Runtime): Operation {
  return bindOperationRoute(runtime, routePath);
}

export function bindOperationRoute(runtime: Runtime, operationRoutePath: string): Operation {
  return async (request, options = {}) => {
    let requestIsValid = false;
    try {
      requestIsValid = isRequest(request);
    } catch {
      requestIsValid = false;
    }
    if (!requestIsValid) {
      throw new TypeError("request does not match foo.bar-send/v1");
    }
    const response = await invoke(runtime, operationRoutePath, request, options);
    if (!isResponse(response)) {
      throw new PlystraError(200, "invalid_response");
    }
    return response;
  };
}

export function createOperation(options: ClientOptions): Operation {
  return bindOperation(createRuntime(options));
}
