// Code generated by Plystra CLI. DO NOT EDIT.

import {
  createRuntime,
  hasOwn,
  invoke,
  isPlainObject,
  PlystraError,
  type ClientOptions,
  type MessageCodec,
  type RequestOptions,
  type Runtime,
} from "../../../../runtime.js";
import { resolveUnaryMethod } from "../../../../descriptors.js";

export const capabilityID = "account.profile.get/v2";
export const contractDigest = "sha256:b867859b40c593d2fb90992083d56c12b97691e7507b69e117c3de5671f0d036";
const method = resolveUnaryMethod(
  "plystra.generated.account.profile.get.v2.AccountProfileGetV2Service",
  "Invoke",
  "plystra.generated.account.profile.get.v2.AccountProfileGetV2Request",
  "plystra.generated.account.profile.get.v2.AccountProfileGetV2Response",
);
const requestCodec: MessageCodec = {
  fields: [
  ],
};
const responseCodec: MessageCodec = {
  fields: [
  ],
};

export type Request = Readonly<Record<string, never>>;

export type Response = Readonly<Record<string, never>>;

export type ErrorCode = never;

function isRequest(value: unknown): value is Request {
  return (
    isPlainObject(value) &&
    Object.keys(value).length === 0
  );
}

function isResponse(value: unknown): value is Response {
  return (
    isPlainObject(value) &&
    Object.keys(value).length === 0
  );
}

export type Operation = (
  request: Request,
  options?: RequestOptions,
) => Promise<Response>;

export function bindOperation(runtime: Runtime): Operation {
  return bindOperationMethod(runtime, method);
}

export function bindOperationMethod(runtime: Runtime, operationMethod: typeof method): Operation {
  return async (request, options = {}) => {
    let requestIsValid = false;
    try {
      requestIsValid = isRequest(request);
    } catch {
      requestIsValid = false;
    }
    if (!requestIsValid) {
      throw new TypeError("request does not match account.profile.get/v2");
    }
    const response = await invoke(runtime, operationMethod, requestCodec, responseCodec, request, options);
    if (!isResponse(response)) {
      throw new PlystraError(200, "invalid_response");
    }
    return response;
  };
}

export function createOperation(options: ClientOptions): Operation {
  return bindOperation(createRuntime(options));
}
