// Package clientgen renders deterministic capability-oriented Go clients from
// capability declarations.
package clientgen

import (
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"go/format"
	"path"
	"strconv"
	"strings"
	"unicode/utf8"

	generation "github.com/plystra/cli/generation/v1"
	"github.com/plystra/cli/internal/capabilityid"
	"github.com/plystra/cli/internal/capabilitymeta"
	"github.com/plystra/cli/internal/goname"
	"golang.org/x/mod/module"
)

// ErrRender reports that a canonical Capability or application-local Alias
// could not produce its generated Go client file.
var ErrRender = errors.New("render Go capability client")

// AliasView is the final immutable Alias surface consumed after canonical
// provider and generation-extension resolution has stabilized.
type AliasView interface {
	ID() generation.CapabilityID
	Target() generation.CapabilityID
	TargetContractDigest() string
	Exposure() generation.Exposure
	Deprecated() string
}

// CanonicalTargetView is the exact resolved contract identity inherited by an
// Alias. generation.CapabilityView satisfies this interface.
type CanonicalTargetView interface {
	ID() generation.CapabilityID
	ContractDigest() string
	Exposure() generation.Exposure
}

// File is one immutable generated Go capability-client output.
type File struct {
	path        string
	packageName string
	data        []byte
}

// Path returns the slash-separated module-relative generated file path.
func (f File) Path() string { return f.path }

// PackageName returns the generated Go package identifier.
func (f File) PackageName() string { return f.packageName }

// Data returns a defensive copy of the formatted generated source.
func (f File) Data() []byte { return append([]byte(nil), f.data...) }

type canonicalContract struct {
	ID string `json:"id"`
}

// Render validates schema and module identity, then emits a version-specific
// client whose operation delegates through a caller-bound Kernel invocation
// handle. Concrete provider packages never enter the generated caller surface.
func Render(modulePath string, schema []byte) (File, error) {
	if err := module.CheckPath(modulePath); err != nil {
		return File{}, fmt.Errorf("%w: invalid Go Module path %q: %v", ErrRender, modulePath, err)
	}
	canonical, err := capabilitymeta.NormalizeSchema(schema)
	if err != nil {
		return File{}, fmt.Errorf("%w: normalize schema: %w", ErrRender, err)
	}
	var contract canonicalContract
	if err := json.Unmarshal(canonical, &contract); err != nil {
		return File{}, fmt.Errorf("%w: decode canonical schema: %w", ErrRender, err)
	}
	identifier, err := capabilityid.Parse(contract.ID)
	if err != nil {
		return File{}, fmt.Errorf("%w: decode canonical identity: %w", ErrRender, err)
	}

	packageName := goname.Package(identifier)
	contractImport := path.Join(modulePath, generatedDirectory("contracts", identifier))
	var source strings.Builder
	fmt.Fprintln(&source, "// Code generated by Plystra CLI. DO NOT EDIT.")
	fmt.Fprintln(&source)
	fmt.Fprintf(&source, "package %s\n\n", packageName)
	fmt.Fprintln(&source, "import (")
	fmt.Fprintln(&source, "\t\"context\"")
	fmt.Fprintln(&source, "\t\"errors\"")
	fmt.Fprintln(&source)
	fmt.Fprintf(&source, "\tcontract %s\n", strconv.Quote(contractImport))
	fmt.Fprintln(&source, ")")
	fmt.Fprintln(&source)
	fmt.Fprintln(&source, "// ErrUnavailable reports an unbound generated Capability client.")
	fmt.Fprintln(&source, "var ErrUnavailable = errors.New(\"generated Capability client is unavailable\")")
	fmt.Fprintln(&source)
	fmt.Fprintln(&source, "// Handle is the typed generated-application boundary required by this client.")
	fmt.Fprintln(&source, "// Application assembly may adapt an exact contract across Go Module boundaries.")
	fmt.Fprintln(&source, "type Handle interface {")
	fmt.Fprintln(&source, "\tAvailable() bool")
	fmt.Fprintln(&source, "\tInvoke(context.Context, contract.Request) (contract.Response, error)")
	fmt.Fprintln(&source, "}")
	fmt.Fprintln(&source)
	fmt.Fprintln(&source, "// Client invokes one exact Capability through its generated application path.")
	fmt.Fprintln(&source, "type Client struct {")
	fmt.Fprintln(&source, "\thandle Handle")
	fmt.Fprintln(&source, "}")
	fmt.Fprintln(&source)
	fmt.Fprintln(&source, "// New binds a generated client to the canonical application invocation path.")
	fmt.Fprintln(&source, "func New(handle Handle) Client {")
	fmt.Fprintln(&source, "\treturn Client{handle: handle}")
	fmt.Fprintln(&source, "}")
	fmt.Fprintln(&source)
	fmt.Fprintln(&source, "// Available reports whether assembly selected a provider for this client.")
	fmt.Fprintln(&source, "func Available(c Client) bool {")
	fmt.Fprintln(&source, "\treturn c.handle != nil && c.handle.Available()")
	fmt.Fprintln(&source, "}")
	fmt.Fprintln(&source)
	fmt.Fprintf(&source, "// %s invokes %s through the generated application path.\n", goname.Operation(identifier), identifier.String())
	fmt.Fprintf(&source, "func (c Client) %s(ctx context.Context, request contract.Request) (contract.Response, error) {\n", goname.Operation(identifier))
	fmt.Fprintln(&source, "\tif !Available(c) {")
	fmt.Fprintln(&source, "\t\treturn contract.Response{}, ErrUnavailable")
	fmt.Fprintln(&source, "\t}")
	fmt.Fprintln(&source, "\treturn c.handle.Invoke(ctx, request)")
	fmt.Fprintln(&source, "}")
	formatted, err := format.Source([]byte(source.String()))
	if err != nil {
		return File{}, fmt.Errorf("%w: format generated source: %w", ErrRender, err)
	}
	return File{
		path:        path.Join(generatedDirectory("clients", identifier), "client_gen.go"),
		packageName: packageName,
		data:        append([]byte(nil), formatted...),
	}, nil
}

// RenderAlias emits one application-local Alias client that exposes the Alias
// operation name and forwards through the exact canonical generated client.
// It never creates an Alias contract, invocation handle, provider, or Kernel
// registration.
func RenderAlias(modulePath string, alias AliasView, target CanonicalTargetView) (File, error) {
	if err := module.CheckPath(modulePath); err != nil {
		return File{}, fmt.Errorf("%w: invalid Go Module path %q: %v", ErrRender, modulePath, err)
	}
	if alias == nil {
		return File{}, fmt.Errorf("%w: Alias view is absent", ErrRender)
	}
	if target == nil {
		return File{}, fmt.Errorf("%w: canonical target view is absent", ErrRender)
	}
	aliasID, err := capabilityid.Parse(alias.ID().String())
	if err != nil {
		return File{}, fmt.Errorf("%w: Alias ID %q is not canonical: %v", ErrRender, alias.ID().String(), err)
	}
	targetID, err := capabilityid.Parse(alias.Target().String())
	if err != nil {
		return File{}, fmt.Errorf("%w: Alias %s target ID %q is not canonical: %v", ErrRender, aliasID, alias.Target().String(), err)
	}
	resolvedTargetID, err := capabilityid.Parse(target.ID().String())
	if err != nil {
		return File{}, fmt.Errorf("%w: resolved target ID %q is not canonical: %v", ErrRender, target.ID().String(), err)
	}
	if targetID != resolvedTargetID {
		return File{}, fmt.Errorf("%w: Alias %s targets %s, but received canonical target %s", ErrRender, aliasID, targetID, resolvedTargetID)
	}
	if aliasID == targetID {
		return File{}, fmt.Errorf("%w: Alias %s cannot target itself", ErrRender, aliasID)
	}
	if strings.HasPrefix(aliasID.Name(), "kernel.") {
		return File{}, fmt.Errorf("%w: Alias %s uses the reserved kernel.* canonical namespace", ErrRender, aliasID)
	}
	if aliasID.Major() != targetID.Major() {
		return File{}, fmt.Errorf("%w: Alias %s and target %s do not use the same version", ErrRender, aliasID, targetID)
	}
	aliasExposure, targetExposure := alias.Exposure(), target.Exposure()
	if !exposureSubset(aliasExposure, targetExposure) {
		return File{}, fmt.Errorf("%w: Alias %s exposure broadens canonical target %s", ErrRender, aliasID, targetID)
	}
	if !aliasExposure.Go {
		return File{}, fmt.Errorf("%w: Alias %s is not exposed to generated Go clients", ErrRender, aliasID)
	}
	if !validContractDigest(target.ContractDigest()) || alias.TargetContractDigest() != target.ContractDigest() {
		return File{}, fmt.Errorf("%w: Alias %s target digest does not match canonical target %s", ErrRender, aliasID, targetID)
	}
	if len(alias.Deprecated()) > 1024 || !utf8.ValidString(alias.Deprecated()) || strings.ContainsRune(alias.Deprecated(), '\x00') {
		return File{}, fmt.Errorf("%w: Alias %s deprecation metadata is invalid", ErrRender, aliasID)
	}

	packageName := goname.Package(aliasID)
	canonicalClientImport := path.Join(modulePath, generatedDirectory("clients", targetID))
	contractImport := path.Join(modulePath, generatedDirectory("contracts", targetID))
	var source strings.Builder
	fmt.Fprintln(&source, "// Code generated by Plystra CLI. DO NOT EDIT.")
	fmt.Fprintln(&source)
	fmt.Fprintf(&source, "package %s\n\n", packageName)
	fmt.Fprintln(&source, "import (")
	fmt.Fprintln(&source, "\t\"context\"")
	fmt.Fprintln(&source)
	fmt.Fprintf(&source, "\tcanonicalclient %s\n", strconv.Quote(canonicalClientImport))
	fmt.Fprintf(&source, "\tcontract %s\n", strconv.Quote(contractImport))
	fmt.Fprintln(&source, ")")
	fmt.Fprintln(&source)
	fmt.Fprintf(&source, "// Client invokes application-local Alias %s through canonical target %s.\n", aliasID, targetID)
	fmt.Fprintln(&source, "type Client struct {")
	fmt.Fprintln(&source, "\ttarget canonicalclient.Client")
	fmt.Fprintln(&source, "}")
	fmt.Fprintln(&source)
	fmt.Fprintf(&source, "// New binds Alias %s to the canonical generated client for %s.\n", aliasID, targetID)
	fmt.Fprintln(&source, "func New(target canonicalclient.Client) Client {")
	fmt.Fprintln(&source, "\treturn Client{target: target}")
	fmt.Fprintln(&source, "}")
	fmt.Fprintln(&source)
	fmt.Fprintln(&source, "// Available reports whether assembly selected the canonical target provider.")
	fmt.Fprintln(&source, "func Available(c Client) bool {")
	fmt.Fprintln(&source, "\treturn canonicalclient.Available(c.target)")
	fmt.Fprintln(&source, "}")
	fmt.Fprintln(&source)
	fmt.Fprintf(
		&source,
		"// %s invokes Alias %s through canonical target %s's generated application path.\n",
		goname.Operation(aliasID),
		aliasID,
		targetID,
	)
	if alias.Deprecated() != "" {
		renderDeprecation(&source, alias.Deprecated())
	}
	fmt.Fprintf(
		&source,
		"func (c Client) %s(ctx context.Context, request contract.Request) (contract.Response, error) {\n",
		goname.Operation(aliasID),
	)
	fmt.Fprintf(&source, "\treturn c.target.%s(ctx, request)\n", goname.Operation(targetID))
	fmt.Fprintln(&source, "}")
	formatted, err := format.Source([]byte(source.String()))
	if err != nil {
		return File{}, fmt.Errorf("%w: format generated Alias source: %w", ErrRender, err)
	}
	return File{
		path:        path.Join(generatedDirectory("clients", aliasID), "client_gen.go"),
		packageName: packageName,
		data:        append([]byte(nil), formatted...),
	}, nil
}

func renderDeprecation(source *strings.Builder, message string) {
	message = strings.ReplaceAll(message, "\r\n", "\n")
	message = strings.ReplaceAll(message, "\r", "\n")
	lines := strings.Split(message, "\n")
	fmt.Fprintln(source, "//")
	fmt.Fprintf(source, "// Deprecated: %s\n", lines[0])
	for _, line := range lines[1:] {
		fmt.Fprintf(source, "// %s\n", line)
	}
}

func exposureSubset(alias, target generation.Exposure) bool {
	return (!alias.Go || target.Go) && (!alias.HTTP || target.HTTP) && (!alias.JavaScript || target.JavaScript)
}

func validContractDigest(value string) bool {
	if !strings.HasPrefix(value, "sha256:") || len(value) != len("sha256:")+64 {
		return false
	}
	_, err := hex.DecodeString(strings.TrimPrefix(value, "sha256:"))
	return err == nil
}

func generatedDirectory(category string, identifier capabilityid.Identifier) string {
	components := append([]string{"generated", "go", category}, strings.Split(identifier.Name(), ".")...)
	components = append(components, "v"+strconv.FormatUint(identifier.Major(), 10))
	return path.Join(components...)
}
