// Package clientgen renders deterministic capability-oriented Go clients from
// capability declarations.
package clientgen

import (
	"encoding/json"
	"errors"
	"fmt"
	"go/format"
	"path"
	"strconv"
	"strings"

	"github.com/plystra/cli/internal/capabilityid"
	"github.com/plystra/cli/internal/capabilitymeta"
	"github.com/plystra/cli/internal/goname"
	"golang.org/x/mod/module"
)

// ErrRender reports that a capability declaration could not produce a Go
// capability client file.
var ErrRender = errors.New("render Go capability client")

// File is one immutable generated Go capability-client output.
type File struct {
	path        string
	packageName string
	data        []byte
}

// Path returns the slash-separated module-relative generated file path.
func (f File) Path() string { return f.path }

// PackageName returns the generated Go package identifier.
func (f File) PackageName() string { return f.packageName }

// Data returns a defensive copy of the formatted generated source.
func (f File) Data() []byte { return append([]byte(nil), f.data...) }

type canonicalContract struct {
	ID string `json:"id"`
}

// Render validates schema and module identity, then emits a version-specific
// client whose operation delegates through a caller-bound Kernel invocation
// handle. Concrete provider packages never enter the generated caller surface.
func Render(modulePath string, schema []byte) (File, error) {
	if err := module.CheckPath(modulePath); err != nil {
		return File{}, fmt.Errorf("%w: invalid Go Module path %q: %v", ErrRender, modulePath, err)
	}
	canonical, err := capabilitymeta.NormalizeSchema(schema)
	if err != nil {
		return File{}, fmt.Errorf("%w: normalize schema: %w", ErrRender, err)
	}
	var contract canonicalContract
	if err := json.Unmarshal(canonical, &contract); err != nil {
		return File{}, fmt.Errorf("%w: decode canonical schema: %w", ErrRender, err)
	}
	identifier, err := capabilityid.Parse(contract.ID)
	if err != nil {
		return File{}, fmt.Errorf("%w: decode canonical identity: %w", ErrRender, err)
	}

	packageName := goname.Package(identifier)
	contractImport := path.Join(modulePath, generatedDirectory("contracts", identifier))
	var source strings.Builder
	fmt.Fprintln(&source, "// Code generated by Plystra CLI. DO NOT EDIT.")
	fmt.Fprintln(&source)
	fmt.Fprintf(&source, "package %s\n\n", packageName)
	fmt.Fprintln(&source, "import (")
	fmt.Fprintln(&source, "\t\"context\"")
	fmt.Fprintln(&source)
	fmt.Fprintf(&source, "\tcontract %s\n", strconv.Quote(contractImport))
	fmt.Fprintln(&source, "\t\"github.com/plystra/kernel/invocation\"")
	fmt.Fprintln(&source, ")")
	fmt.Fprintln(&source)
	fmt.Fprintln(&source, "// Client invokes one exact capability through the Kernel governance boundary.")
	fmt.Fprintln(&source, "type Client struct {")
	fmt.Fprintln(&source, "\thandle invocation.Handle[contract.Request, contract.Response]")
	fmt.Fprintln(&source, "}")
	fmt.Fprintln(&source)
	fmt.Fprintln(&source, "// New binds a generated client to one caller-scoped capability handle.")
	fmt.Fprintln(&source, "func New(handle invocation.Handle[contract.Request, contract.Response]) Client {")
	fmt.Fprintln(&source, "\treturn Client{handle: handle}")
	fmt.Fprintln(&source, "}")
	fmt.Fprintln(&source)
	fmt.Fprintln(&source, "// Available reports whether assembly selected a provider for this client.")
	fmt.Fprintln(&source, "func Available(c Client) bool {")
	fmt.Fprintln(&source, "\treturn c.handle.Available()")
	fmt.Fprintln(&source, "}")
	fmt.Fprintln(&source)
	fmt.Fprintf(&source, "// %s invokes %s through governed Kernel dispatch.\n", goname.Operation(identifier), identifier.String())
	fmt.Fprintf(&source, "func (c Client) %s(ctx context.Context, request contract.Request) (contract.Response, error) {\n", goname.Operation(identifier))
	fmt.Fprintln(&source, "\treturn c.handle.Invoke(ctx, request)")
	fmt.Fprintln(&source, "}")
	formatted, err := format.Source([]byte(source.String()))
	if err != nil {
		return File{}, fmt.Errorf("%w: format generated source: %w", ErrRender, err)
	}
	return File{
		path:        path.Join(generatedDirectory("clients", identifier), "client_gen.go"),
		packageName: packageName,
		data:        append([]byte(nil), formatted...),
	}, nil
}

func generatedDirectory(category string, identifier capabilityid.Identifier) string {
	components := append([]string{"generated", "go", category}, strings.Split(identifier.Name(), ".")...)
	components = append(components, "v"+strconv.FormatUint(identifier.Major(), 10))
	return path.Join(components...)
}
