// Package configurationgen renders module-owned typed plugin configuration
// and the only adapter that may turn private runtime YAML into that type.
package configurationgen

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"go/format"
	"path"
	"strconv"
	"strings"

	"github.com/plystra/cli/internal/goname"
	"github.com/plystra/cli/internal/pluginid"
	"github.com/plystra/kernel/plugin/manifest"
)

var (
	// ErrRender reports an invalid configuration-generation input or source
	// rendering failure.
	ErrRender = errors.New("render plugin configuration")
	// ErrInvalidInput reports an invalid plugin directory name or Plugin ID.
	ErrInvalidInput = errors.New("invalid plugin configuration input")
	// ErrIdentifierCollision reports schema fields that map to the same Go
	// identifier.
	ErrIdentifierCollision = errors.New("plugin configuration Go identifier collision")
)

// Input is the complete schema-only input for one module-root plugin. It never
// contains application runtime values or Secret reference targets.
type Input struct {
	PluginName string
	PluginID   string
	Schema     manifest.Config
}

// File is one immutable generated configuration source file.
type File struct {
	path       string
	data       []byte
	typeName   string
	decodeName string
}

// Path returns the application-relative managed source path.
func (f File) Path() string { return f.path }

// Data returns defensive generated source bytes.
func (f File) Data() []byte { return append([]byte(nil), f.data...) }

// TypeName returns the exported schema-derived configuration type.
func (f File) TypeName() string { return f.typeName }

// DecodeName returns the exported runtime decoder name.
func (f File) DecodeName() string { return f.decodeName }

type fieldPlan struct {
	name      string
	goName    string
	goType    string
	accessor  string
	pointer   bool
	mustExist bool
	comment   string
}

type schemaFieldDocument struct {
	Type     manifest.ConfigType `json:"type"`
	Required bool                `json:"required,omitempty"`
	Default  json.RawMessage     `json:"default,omitempty"`
	Enum     []json.RawMessage   `json:"enum,omitempty"`
	Format   string              `json:"format,omitempty"`
	Items    manifest.ConfigType `json:"items,omitempty"`
}

// Render returns deterministic, gofmt-formatted configuration source. The
// generated decoder parses only the embedded schema and delegates all runtime
// value validation and Secret resolution to Kernel configuration.Decode.
func Render(input Input) (File, error) {
	if !validPluginName(input.PluginName) {
		return File{}, fmt.Errorf("%w: %w: plugin name %q is not canonical lower-case kebab-case", ErrRender, ErrInvalidInput, input.PluginName)
	}
	if err := pluginid.Validate(input.PluginID); err != nil {
		return File{}, fmt.Errorf("%w: %w: Plugin ID %q: %v", ErrRender, ErrInvalidInput, input.PluginID, err)
	}

	stem := exportedPluginName(input.PluginName)
	if stem == "" {
		return File{}, fmt.Errorf("%w: %w: plugin name %q has no Go identifier", ErrRender, ErrInvalidInput, input.PluginName)
	}
	fields, err := planFields(input.Schema)
	if err != nil {
		return File{}, fmt.Errorf("%w: plugin %q: %w", ErrRender, input.PluginID, err)
	}
	schemaJSON, err := encodeSchema(input.Schema)
	if err != nil {
		return File{}, fmt.Errorf("%w: plugin %q schema: %v", ErrRender, input.PluginID, err)
	}

	typeName := stem + "Config"
	decodeName := "Decode" + stem
	privateStem := lowerFirst(stem)
	pluginIDName := stem + "PluginID"
	schemaName := privateStem + "Schema"
	unavailableName := privateStem + "UnavailableField"

	var source bytes.Buffer
	fmt.Fprintln(&source, "// Code generated by Plystra CLI. DO NOT EDIT.")
	fmt.Fprintln(&source)
	fmt.Fprintln(&source, "package configuration")
	fmt.Fprintln(&source)
	fmt.Fprintln(&source, "import (")
	fmt.Fprintln(&source, "\t\"context\"")
	fmt.Fprintln(&source, "\t\"fmt\"")
	fmt.Fprintln(&source, "\t\"log/slog\"")
	if usesType(input.Schema, manifest.ConfigURL) {
		fmt.Fprintln(&source, "\t\"net/url\"")
	}
	fmt.Fprintln(&source, "\t\"sync\"")
	if usesType(input.Schema, manifest.ConfigDuration) {
		fmt.Fprintln(&source, "\t\"time\"")
	}
	fmt.Fprintln(&source)
	fmt.Fprintln(&source, "\tkernelconfiguration \"github.com/plystra/kernel/configuration\"")
	fmt.Fprintln(&source, "\tkernelmanifest \"github.com/plystra/kernel/plugin/manifest\"")
	fmt.Fprintln(&source, ")")
	fmt.Fprintln(&source)
	fmt.Fprintf(&source, "// %s is the immutable Plugin ID whose schema defines %s.\n", pluginIDName, typeName)
	fmt.Fprintf(&source, "const %s = %s\n", pluginIDName, strconv.Quote(input.PluginID))
	fmt.Fprintln(&source)
	fmt.Fprintf(&source, "var %s = sync.OnceValues(func() (kernelmanifest.Config, error) {\n", schemaName)
	fmt.Fprintf(&source, "\treturn kernelmanifest.ParseConfig([]byte(%s))\n", strconv.Quote(string(schemaJSON)))
	fmt.Fprintln(&source, "})")
	fmt.Fprintln(&source)
	fmt.Fprintf(&source, "// %s is the validated typed runtime configuration for %s.\n", typeName, input.PluginID)
	fmt.Fprintf(&source, "type %s struct {\n", typeName)
	for _, field := range fields {
		fmt.Fprintf(&source, "\t// %s\n", field.comment)
		fmt.Fprintf(&source, "\t%s %s\n", field.goName, field.goType)
	}
	fmt.Fprintln(&source, "}")
	fmt.Fprintln(&source)
	fmt.Fprintf(&source, "// %s validates one private mapping, resolves declared Secret references,\n", decodeName)
	fmt.Fprintln(&source, "// and constructs exactly one typed object without retaining the source bytes.")
	fmt.Fprintf(&source, "func %s(ctx context.Context, resolver *kernelconfiguration.Resolver, data []byte) (%s, error) {\n", decodeName, typeName)
	fmt.Fprintf(&source, "\tschema, err := %s()\n", schemaName)
	fmt.Fprintln(&source, "\tif err != nil {")
	fmt.Fprintf(&source, "\t\treturn %s{}, fmt.Errorf(\"decode configuration for plugin %%q: invalid generated schema: %%w\", %s, err)\n", typeName, pluginIDName)
	fmt.Fprintln(&source, "\t}")
	fmt.Fprintln(&source, "\tvalues, err := kernelconfiguration.Decode(ctx, resolver, schema, data)")
	fmt.Fprintln(&source, "\tif err != nil {")
	fmt.Fprintf(&source, "\t\treturn %s{}, fmt.Errorf(\"decode configuration for plugin %%q: %%w\", %s, err)\n", typeName, pluginIDName)
	fmt.Fprintln(&source, "\t}")
	if len(fields) == 0 {
		fmt.Fprintln(&source, "\t_ = values")
	}
	fmt.Fprintf(&source, "\tvar result %s\n", typeName)
	for _, field := range fields {
		access := fmt.Sprintf("values.%s(%s)", field.accessor, strconv.Quote(field.name))
		if field.mustExist {
			fmt.Fprintf(&source, "\t%sValue, ok := %s\n", lowerFirst(field.goName), access)
			fmt.Fprintln(&source, "\tif !ok {")
			fmt.Fprintf(&source, "\t\treturn %s{}, %s(%s)\n", typeName, unavailableName, strconv.Quote(field.name))
			fmt.Fprintln(&source, "\t}")
			fmt.Fprintf(&source, "\tresult.%s = %sValue\n", field.goName, lowerFirst(field.goName))
			continue
		}
		fmt.Fprintf(&source, "\tif value, ok := %s; ok {\n", access)
		if field.pointer {
			fmt.Fprintf(&source, "\t\tresult.%s = &value\n", field.goName)
		} else {
			fmt.Fprintf(&source, "\t\tresult.%s = value\n", field.goName)
		}
		fmt.Fprintln(&source, "\t}")
	}
	fmt.Fprintln(&source, "\treturn result, nil")
	fmt.Fprintln(&source, "}")
	fmt.Fprintln(&source)
	fmt.Fprintf(&source, "func %s(name string) error {\n", unavailableName)
	fmt.Fprintf(&source, "\treturn fmt.Errorf(\"decode configuration for plugin %%q: generated field %%q is unavailable\", %s, name)\n", pluginIDName)
	fmt.Fprintln(&source, "}")
	fmt.Fprintln(&source)
	fmt.Fprintf(&source, "// String redacts every %s value.\n", typeName)
	fmt.Fprintf(&source, "func (%s) String() string { return \"<redacted-plugin-configuration>\" }\n", typeName)
	fmt.Fprintln(&source)
	fmt.Fprintln(&source, "// GoString prevents Go-syntax formatting from exposing private values.")
	fmt.Fprintf(&source, "func (%s) GoString() string { return \"<redacted-plugin-configuration>\" }\n", typeName)
	fmt.Fprintln(&source)
	fmt.Fprintln(&source, "// Format redacts private values for every fmt verb.")
	fmt.Fprintf(&source, "func (%s) Format(state fmt.State, _ rune) {\n", typeName)
	fmt.Fprintln(&source, "\t_, _ = state.Write([]byte(\"<redacted-plugin-configuration>\"))")
	fmt.Fprintln(&source, "}")
	fmt.Fprintln(&source)
	fmt.Fprintln(&source, "// LogValue redacts private values for structured standard-library logging.")
	fmt.Fprintf(&source, "func (%s) LogValue() slog.Value {\n", typeName)
	fmt.Fprintln(&source, "\treturn slog.StringValue(\"<redacted-plugin-configuration>\")")
	fmt.Fprintln(&source, "}")
	fmt.Fprintln(&source)
	fmt.Fprintln(&source, "// MarshalJSON rejects accidental configuration serialization.")
	fmt.Fprintf(&source, "func (%s) MarshalJSON() ([]byte, error) { return nil, kernelconfiguration.ErrSecretExposure }\n", typeName)
	fmt.Fprintln(&source)
	fmt.Fprintln(&source, "// MarshalText rejects accidental configuration serialization.")
	fmt.Fprintf(&source, "func (%s) MarshalText() ([]byte, error) { return nil, kernelconfiguration.ErrSecretExposure }\n", typeName)
	fmt.Fprintln(&source)
	fmt.Fprintln(&source, "// MarshalYAML rejects accidental configuration serialization.")
	fmt.Fprintf(&source, "func (%s) MarshalYAML() (any, error) { return nil, kernelconfiguration.ErrSecretExposure }\n", typeName)

	formatted, err := format.Source(source.Bytes())
	if err != nil {
		return File{}, fmt.Errorf("%w: plugin %q source: %v", ErrRender, input.PluginID, err)
	}
	return File{
		path:       path.Join("generated/go/configuration", input.PluginName+"_gen.go"),
		data:       formatted,
		typeName:   typeName,
		decodeName: decodeName,
	}, nil
}

func planFields(schema manifest.Config) ([]fieldPlan, error) {
	fields := schema.Fields()
	result := make([]fieldPlan, 0, len(fields))
	identifiers := make(map[string]string, len(fields))
	for _, field := range fields {
		goName := goname.Field(field.Name())
		if _, reserved := reservedConfigMembers[goName]; reserved {
			return nil, fmt.Errorf("%w: field %q maps to reserved generated member %s", ErrIdentifierCollision, field.Name(), goName)
		}
		if previous, collision := identifiers[goName]; collision {
			return nil, fmt.Errorf("%w: fields %q and %q both map to %s", ErrIdentifierCollision, previous, field.Name(), goName)
		}
		goType, accessor, pointer, err := fieldType(field)
		if err != nil {
			return nil, err
		}
		mustExist := field.Required() || field.HasDefault()
		comment := goName + " is the value of " + field.Name() + "."
		switch {
		case !mustExist && pointer:
			comment = goName + " is nil when " + field.Name() + " is omitted."
		case !mustExist && (field.Type() == manifest.ConfigObject || field.Type() == manifest.ConfigArray):
			comment = goName + " is nil when omitted and non-nil when " + field.Name() + " is configured, including an empty value."
		}
		identifiers[goName] = field.Name()
		result = append(result, fieldPlan{
			name:      field.Name(),
			goName:    goName,
			goType:    goType,
			accessor:  accessor,
			pointer:   pointer,
			mustExist: mustExist,
			comment:   comment,
		})
	}
	return result, nil
}

var reservedConfigMembers = map[string]struct{}{
	"Format":      {},
	"GoString":    {},
	"LogValue":    {},
	"MarshalJSON": {},
	"MarshalText": {},
	"MarshalYAML": {},
	"String":      {},
}

func fieldType(field manifest.ConfigField) (goType, accessor string, pointer bool, err error) {
	switch field.Type() {
	case manifest.ConfigString:
		goType, accessor = "string", "StringValue"
	case manifest.ConfigInteger:
		goType, accessor = "int64", "IntegerValue"
	case manifest.ConfigNumber:
		goType, accessor = "float64", "NumberValue"
	case manifest.ConfigBoolean:
		goType, accessor = "bool", "BooleanValue"
	case manifest.ConfigDuration:
		goType, accessor = "time.Duration", "DurationValue"
	case manifest.ConfigURL:
		goType, accessor = "url.URL", "URLValue"
	case manifest.ConfigSecret:
		goType, accessor = "kernelconfiguration.Secret", "SecretValue"
	case manifest.ConfigObject:
		goType, accessor = "map[string]any", "ObjectValue"
	case manifest.ConfigArray:
		goType, accessor, err = arrayType(field.Items())
	default:
		err = fmt.Errorf("unsupported field %q type %q", field.Name(), field.Type())
	}
	if err != nil {
		return "", "", false, err
	}
	pointer = !field.Required() && !field.HasDefault() && field.Type() != manifest.ConfigObject && field.Type() != manifest.ConfigArray
	if pointer {
		goType = "*" + goType
	}
	return goType, accessor, pointer, nil
}

func arrayType(items manifest.ConfigType) (string, string, error) {
	switch items {
	case manifest.ConfigString:
		return "[]string", "Strings", nil
	case manifest.ConfigInteger:
		return "[]int64", "Integers", nil
	case manifest.ConfigNumber:
		return "[]float64", "Numbers", nil
	case manifest.ConfigBoolean:
		return "[]bool", "Booleans", nil
	case manifest.ConfigDuration:
		return "[]time.Duration", "Durations", nil
	case manifest.ConfigURL:
		return "[]url.URL", "URLs", nil
	case manifest.ConfigObject:
		return "[]map[string]any", "Objects", nil
	default:
		return "", "", fmt.Errorf("unsupported array item type %q", items)
	}
}

func encodeSchema(schema manifest.Config) ([]byte, error) {
	document := make(map[string]schemaFieldDocument, len(schema.Fields()))
	for _, field := range schema.Fields() {
		enums := field.EnumJSON()
		encodedEnums := make([]json.RawMessage, len(enums))
		for index := range enums {
			encodedEnums[index] = json.RawMessage(enums[index])
		}
		document[field.Name()] = schemaFieldDocument{
			Type:     field.Type(),
			Required: field.Required(),
			Default:  json.RawMessage(field.DefaultJSON()),
			Enum:     encodedEnums,
			Format:   field.Format(),
			Items:    field.Items(),
		}
	}
	return json.Marshal(document)
}

func usesType(schema manifest.Config, target manifest.ConfigType) bool {
	for _, field := range schema.Fields() {
		if field.Type() == target || field.Type() == manifest.ConfigArray && field.Items() == target {
			return true
		}
	}
	return false
}

func exportedPluginName(name string) string {
	parts := strings.Split(name, "-")
	for index := range parts {
		parts[index] = goname.ExportedWord(parts[index])
	}
	return strings.Join(parts, "")
}

func lowerFirst(value string) string {
	if value == "" {
		return ""
	}
	return strings.ToLower(value[:1]) + value[1:]
}

func validPluginName(value string) bool {
	if value == "" || len(value) > 64 || value[0] < 'a' || value[0] > 'z' {
		return false
	}
	previousHyphen := false
	for index := 1; index < len(value); index++ {
		character := value[index]
		switch {
		case character >= 'a' && character <= 'z', character >= '0' && character <= '9':
			previousHyphen = false
		case character == '-' && !previousHyphen:
			previousHyphen = true
		default:
			return false
		}
	}
	return !previousHyphen
}
