package newproject

const goModuleTemplate = `module %s

go 1.26

require (
	github.com/plystra/kernel %s
	go.yaml.in/yaml/v3 %s
	golang.org/x/mod %s
	golang.org/x/sys %s
)
`

const plystraTemplate = `http:
  address: ":8080"
  expose: {}

timeouts:
  startup: 2m

interfaces:
  require: {}
  use: {}
  policies: {}

config: {}
`

const readmeTemplate = `# %s

This is the Plystra Project ` + "`%s`" + `.

Local plugins belong in direct child directories containing ` + "`plugin.yaml`" + `. Do not add a root ` + "`plugins/`" + ` container.

Generation and scaffolding create ignored dist/runtime-baseline.json with native owner-only permissions. Supply --runtime-baseline dist/runtime-baseline.json when starting the generated binary, and preserve private permissions when deploying this file with the matching binary. Missing, malformed, publicly readable, or mismatched baselines fail before application work. Refresh the private baseline with plystra generate after compiled default edits and rebuild authored Go. Startup composes ordered template roots from this private baseline and validates the live root template relationship in every selector mode. No source tree or Module Cache is a runtime input. Named Resource instances receive typed configuration and Secrets through the same private baseline; complete gate acceptance remains unfinished.

The baseline's validation inventory covers every visible constructor independently of current selection. Startup validates dormant choices and effective Config objects, including composition, defaults, requiredness, and Secret-reference syntax, then discards dormant objects without resolving Secrets or constructing values. Dormant-only choice and value edits preserve executable output. Regenerate the baseline and rebuild when its validation schema inventory changes; regenerate older pairs to include this inventory.

## Development

` + "```powershell" + `
plystra plugin create records
plystra capability create records.read --query --plugin records --expose
plystra interface create records.list
plystra implement records.list/v1 --package ./recordlist
plystra generate
plystra generate --check
plystra inspect capabilities --format json
plystra inspect
plystra inspect modules
plystra inspect interfaces
plystra inspect implementations
plystra inspect resources
plystra inspect configuration
plystra explain capability records.read/v1
plystra explain plugin <plugin-id>
plystra explain config config.<plugin-id>.<field>
plystra explain alias <alias-name>/vN
plystra explain exposure <capability-or-alias-name>/vN
plystra check
go test ./...
go build ./...
go vet ./...
` + "```" + `

` + "`plystra implement`" + ` creates a validated compatible candidate; it does not activate that constructor. Effective ` + "`interfaces.require`" + ` and ` + "`http.expose`" + ` entries compose from template roots and the selected current-Project delta. Inherited requirements and exposure create roots immediately without repeated current-Project declarations. To add an internal application root or public root, edit the selected document's respective set or mapping. Discovery alone never creates a root. An exact compatible ` + "`interfaces.use`" + ` choice is validated immediately but remains dormant without a root, binding, reachable constructor, lifecycle entry, or generated Interface runtime until its Interface becomes required. An exact ` + "`config.<constructor-symbol>`" + ` object is accepted only for an effective explicit choice or a constructor already in the reachable graph. A dormant owner's object is immediately checked against its exported same-package ` + "`Config`" + ` schema, including Secret-reference syntax, without reading an environment variable or Secret file; it creates no runtime delivery, bootstrap membership, Secret lookup, or Kernel state.

A Project with zero non-intrinsic roots is valid. With no selected Resource instances, generation emits intrinsic-only static assembly and bootstrap; the application smoke path starts, invokes ` + "`kernel.health/v1`" + `, and stops cleanly without ordinary constructor or configuration membership.

Every required Interface or exact plystra.Optional[T] constructor dependency needs an explicit nonblank Go identifier other than _. Only the optional first Config parameter is exempt. Names retain exact case and authored position through discovery, inspection, static assembly, and provenance. Inspection dependency edges carry exact parameter_name and one-based parameter_position; other edges omit them. Repeated dependencies on one Interface remain distinct, with the same name and position in human output. Renaming or reordering a reachable dependency changes application-model identity and requires regeneration, not a new Interface contract. Unnamed and blank dependencies fail even on unselected visible candidates with PLYSTRA_IMPLEMENTATION_REQUIRED_INVALID or PLYSTRA_IMPLEMENTATION_OPTIONAL_INVALID and the owning constructor source before mutation. Name the reported parameter and rerun the command.

Constructors only assemble values and return a concrete pointer plus error. Acquire resources and start background work in lifecycle Start. Generated assembly cleans all returned lifecycle values after construction failure, including non-nil partial results, and startup rollback includes values whose Start never ran. Stop must tolerate never-started values. Use errors.As with interface { RetryCleanup(context.Context) error } to find the outermost construction-cleanup owner and call RetryCleanup(ctx); retries keep the original cleanup timeout and never restart construction or publish a failed runtime.

Own lifecycle changes through the generated application's Start and Stop. Overlapping or reentrant application transitions return lifecycle.ErrState without changing either manager or admission, including during rollback and drain. Application copies share this guard; independent applications do not. Retry after the active operation returns. Direct lifecycle calls on the lower-level InterfaceRuntime are outside this application guard.

Construct semantic errors with invocation.NewSemanticError(code, cause) from github.com/plystra/kernel/invocation. Use errors.As with *invocation.SemanticError and Code() locally; structural SemanticErrorCode methods are not recognized. Wrap uncertain effects with invocation.NewResultUnknown(cause) before semantic translation. Generated error projection follows ordinary wrapping and joins up to 64 unwrap levels and 1,024 nodes, rejects conflicting or undeclared codes, and exposes no private cause. Completion remains independent of the primary code through Connect, transitional HTTP, and PlystraError.completion in the SDK.

Mutating Plystra commands regenerate automatically. Add an ordinary Go Module dependency with ` + "`plystra add github.com/acme/platform@v1.0.0`" + `, update it with ` + "`plystra update github.com/acme/platform@v1.1.0`" + `, and remove it with ` + "`plystra remove github.com/acme/platform`" + `. A Project created with ` + "`plystra new app --template github.com/acme/platform@v1.0.0`" + ` retains the selected template as the same kind of ordinary direct dependency. Creation persists the exact root template module path and immediately inherits the supported Interface and named Resource baseline. It copies no source or configuration and grants template origin no Implementation candidate priority. Named Resource instances and bindings are inherited; Data inheritance remains unsupported. Generated source and manifest provenance contain neither Secret-reference targets nor resolved values. Run ` + "`plystra generate`" + ` after manual declaration edits and use ` + "`plystra generate --check`" + ` as the read-only consistency gate. Use ` + "`plystra inspect`" + ` for a concise read-only summary of the same selected model, ` + "`plystra inspect modules`" + ` for participating Project modules, and ` + "`plystra inspect interfaces`" + ` for every visible authored and intrinsic Interface, module ownership, root requirements, active selected constructors and reasons, constructor dependency availability, and inactive visible Interfaces. Graph views use the versioned ` + "`plystra.graph`" + ` v1 schema with project-relative sources and no resolved Secrets or unrestricted configuration values; use ` + "`--verbose`" + ` for complete resolution evidence or ` + "`--format json`" + ` for deterministic automation output. Use ` + "`plystra explain capability <capability-name>/vN`" + ` with the same selector to see a Capability's selected Provider, direct reason and source, and the exact configuration field that changes that Provider decision. Use ` + "`plystra explain plugin <plugin-id>`" + ` to see whether a Plugin is selected from the current Project, selected as an exact Capability Provider, or visible but unselected, together with the direct source and selector-matched configuration field. Use ` + "`plystra explain config config.<plugin-id>.<field>`" + ` to see the typed configuration owner, winning source, explicit removal or ancestor suppression, and exact selected document field to edit without exposing configuration values or Secret-reference targets. Use ` + "`plystra explain alias <alias-name>/vN`" + ` to see its direct canonical target, inherited or narrowed exposure, every compatible application or generation-extension source, and the selector-matched field or activation decision that changes the result. Use ` + "`plystra explain exposure <capability-or-alias-name>/vN`" + ` to see why that identity is public or internal and the selected exposure, Alias, or activation decision that changes the surface.

Automation may create with ` + "`--format json`" + ` to receive one ` + "`plystra.result/v1`" + ` document. Success nests ` + "`plystra.project-created/v1`" + ` with a safe relative ` + "`payload.directory`" + `; enter it and run ` + "`plystra check`" + ` independently.

All five explanation commands also return ` + "`plystra.result/v1`" + ` with a ` + "`plystra.explain/v1`" + ` payload, diagnostics, and ` + "`plystra.recovery/v1`" + ` actions. JSON stderr stays empty after initialization; human progress and diagnostics use stderr. Invalid invocation or subject exits 2, invalid Project state or a missing target exits 3, required decisions or missing prerequisites exit 4, and internal failures exit 8 with redacted ` + "`PLYSTRA_EXPLAIN_FAILED`" + `. Provider recovery edits the selected ` + "`capabilities.use`" + ` field; installed ` + "`plystra use`" + ` accepts only Interface Implementation constructors. Executable recovery and supported choice options use exact ` + "`argv`" + ` with the selector and Project-relative working directory. Never execute placeholders or human display strings; run the action's independent verification afterward.

` + "`plystra inspect capabilities --format json`" + ` is Project-independent and returns one ` + "`plystra.result/v1`" + ` document with a ` + "`plystra.capabilities/v1`" + ` payload. It reports exact installed commands and arguments, selectors, stable defaults, interaction and output modes, effect classes, schemas, bounds, toolchain identity, and independent ` + "`specified`" + `, ` + "`parsed`" + `, ` + "`generated`" + `, ` + "`executed`" + `, and ` + "`accepted`" + ` support stages. Planned commands are absent. Result, recovery, inspection, and graph schemas are available; standalone diagnostic and continuation schema roles remain explicitly unavailable. Invalid Projects and ambient selectors cannot change those facts; explicit ` + "`--verbose`" + `, ` + "`--env`" + `, and ` + "`--config`" + ` are invalid.

` + "`plystra inspect implementations`" + ` shows every visible constructor candidate, active, dormant-explicit, or unselected state, implemented Interfaces, declared and resolved dependencies, constructor-owned configuration provenance, and reachable assembly membership.

` + "`plystra inspect configuration`" + ` shows selected layers, redacted field summaries, owners, precedence, effective and overridden contributions, removals, and ancestor suppression.

Malformed ` + "`add`" + ` and ` + "`update`" + ` queries emit ` + "`PLYSTRA_DEPENDENCY_ADD_QUERY_INVALID`" + ` and ` + "`PLYSTRA_DEPENDENCY_UPDATE_QUERY_INVALID`" + `; a malformed exact ` + "`remove`" + ` path emits ` + "`PLYSTRA_DEPENDENCY_REMOVE_PATH_INVALID`" + `. Each failure occurs before Project discovery or mutation and supplies one placeholder-based corrected command. A valid ` + "`remove`" + ` path or ` + "`update`" + ` query absent from ` + "`go.mod`" + ` emits ` + "`PLYSTRA_DEPENDENCY_REMOVE_NOT_SELECTED`" + ` or ` + "`PLYSTRA_DEPENDENCY_UPDATE_NOT_SELECTED`" + ` before mutation, with placeholder-only recovery.

Malformed ` + "`capability create`" + `, ` + "`capability implement`" + `, and ` + "`capability expose`" + ` references emit ` + "`PLYSTRA_CAPABILITY_CREATE_REFERENCE_INVALID`" + `, ` + "`PLYSTRA_CAPABILITY_IMPLEMENT_REFERENCE_INVALID`" + `, and ` + "`PLYSTRA_CAPABILITY_EXPOSE_REFERENCE_INVALID`" + ` before Project discovery or mutation. Recovery uses canonical placeholders and retains only a safe exposure selector. A valid exact action mismatch emits ` + "`PLYSTRA_CAPABILITY_CREATE_ALREADY_VISIBLE`" + ` or ` + "`PLYSTRA_CAPABILITY_IMPLEMENT_NOT_VISIBLE`" + ` and switches to the counterpart authoring command without mutation. An explicit older or skipped new version uses ` + "`PLYSTRA_CAPABILITY_CREATE_CONFIRMATION_REQUIRED`" + ` and requires the same create command with ` + "`--confirm`" + `. An omitted version above the maximum visible major uses ` + "`PLYSTRA_CAPABILITY_CREATE_VERSION_EXHAUSTED`" + ` and requires a new canonical Capability identity. Missing new-identity profiles use ` + "`PLYSTRA_CAPABILITY_CREATE_INTENT_PROFILE_REQUIRED`" + `; profiles on copied later versions use ` + "`PLYSTRA_CAPABILITY_CREATE_INTENT_PROFILE_NOT_ALLOWED`" + `.

Capability creation and implementation are non-interactive by default. Pass ` + "`--plugin <directory-or-plugin-id>`" + ` as complete explicit input, or add ` + "`--interactive`" + ` to request a terminal choice only when enclosing and sole-Plugin inference remain ambiguous. Terminal detection alone never prompts. Default ambiguity emits ` + "`PLYSTRA_PLUGIN_TARGET_AMBIGUOUS`" + ` with every current-Project ` + "`plugin.yaml`" + ` at ` + "`1:1`" + ` as a sorted ` + "`plugin-declaration`" + ` source. Requested interaction without a terminal and failed selections emit ` + "`PLYSTRA_PLUGIN_TARGET_INVALID`" + `. Missing explicit targets and failed selections have no fabricated source.

A well-formed ` + "`capability expose`" + ` target absent from the selected visible catalog emits ` + "`PLYSTRA_CAPABILITY_EXPOSE_NOT_VISIBLE`" + ` before write planning or mutation. Recovery retains a safe selector and substitutes the canonical Capability placeholder instead of copying the missing target.

Root plystra.yaml may name one exact template module path; go.mod selects its version. The resolver follows a finite linear chain in the application's effective Go Module graph, composes oldest to nearest, then applies the selected current-Project delta. It rejects missing modules, non-Project targets, malformed relationships, and cycles before installation. Template roots immediately contribute Interface requirements, exact Implementation choices, policies, typed constructor configuration, exposure, and CORS. Ordinary dependencies stay inactive. Template depth never ranks Implementation candidates. Environment files, replacement documents, resolved Secrets, http.address, and timeouts.startup are not inherited. Named Resource instances, typed configuration, and bindings are inherited; Data inheritance remains unsupported and is rejected before partial activation. This is not complete Gate 5 acceptance.

Remove exact interfaces.use, interfaces.policies, and http.expose entries only with {$remove: true}. Null, empty values, false or string-valued markers, and sibling fields are invalid. Keep the authored tombstone even if no lower entry exists; it prevents later dependency additions from restoring the entry. Regenerate and rebuild for runtime compatibility version 12. Remove http.cors or either of its fields with {$remove: true}; null is invalid. Removing credentials restores false; an effective CORS object still requires origins. Selected template roots contribute CORS, while ordinary dependencies remain inactive.

Remove a whole config.<constructor-symbol> entry only with {$remove: true}. Null, sequences, malformed markers, and sibling fields are invalid at that boundary; {} remains configuration, not removal. The constructor needs a discovered compiled Config schema. Keep exclusions even without lower configuration; inspection retains removal ownership and suppressed sources. Generated runtime loading strips whole-entry markers before construction, but removing required configuration still fails before any constructor runs.

During typed CLI composition, remove a declared field inside a non-pointer fixed struct with {$remove: true}. Exclusions persist without lower values; omission inherits. Literal null, ~, and blank values are atomic nil only for pointers, slices, and maps, distinct from removal and empty collections. Other compiled types reject null. Reserved singleton $remove mappings are invalid inside atomic values, including pointed-to struct members, list elements, and dynamic-map entries. A dynamic map with $remove and other keys remains an ordinary typed value.

Required fields are checked after template roots and selected layers compose, not in partial fragments. Effective dormant objects and all active configurable constructors must be complete; dormant absent or removed objects need no values yet. Requiredness means presence: zero, empty, and schema-permitted nil values count. Omitted fixed structs and fixed-array elements still need nested required fields; absent or nil pointers and empty slices/maps have no child values to validate. PLYSTRA_CONSTRUCTOR_CONFIGURATION_VALUES_INVALID identifies a safe declared path and the selected current document before mutation. Supply the missing field there or in a template root, or correct its tombstone. Generated startup composes template and current-project values before checking requiredness and applying compiled scalar defaults.

During typed CLI composition, a supplied non-null pointer field replaces its complete lower value, including pointers to structs and multiple pointer layers. Omission inherits; {} replaces a pointed-to struct without inheriting omitted fields. Only non-pointer fixed structs compose field by field. Later template pointer values replace earlier values atomically, including when their fields are disjoint. Inspection retains one redacted atomic value and its sources. Generated runtime loading applies the same rules to template and current-project values.

An interfaces.require sequence replaces the complete lower explicit requirement set; [] clears it. Omission and {} inherit, while {add: [...], remove: [...]} changes only named members. Template roots form ordered lower layers from oldest to nearest. A later sparse overlay preserves an earlier complete-set boundary. Exposure, constructor dependencies, and intrinsic Kernel requirements remain independent. Inspection and explanation retain suppressed sources. New Projects use require: {} to preserve inherited template requirements. Generated runtime compatibility version 12 applies these set rules above the private baseline's template roots, preserving current removals and complete-set boundaries.

The public runtime contract binds ordered template module/version identities and the live root relationship. Startup reconstructs the normalized ancestry from the owner-private baseline without dependency sources. Equivalent effective declarations preserve executable identity; a different ancestry still requires a matching baseline and runtime contract. Private values and their hashes never enter public output.

Consumer Resource contracts are discovered independently of instance configuration. Declare one non-generic defined Go interface Resource with exactly one //plystra:resource <resource-id> directive. plystra inspect resources reports every visible contract, its package, sources, and exact transitive public Go shape digest. Interface projection metadata does not apply. Consumer lifecycle-control methods, malformed declarations, and duplicate IDs fail with owning sources. Contract discovery is a separate support stage from named-instance construction, binding, execution, and Data acceptance.

Resource provider discovery validates one //plystra:implements-resource <resource-id> directive on an exported non-generic constructor, optional first same-package Config, explicitly named canonical Resource dependencies, and a concrete pointer plus error result assignable to the visible contract. Mixed Interface directives and invalid signatures fail with owning sources. Installed resource.provider.discovery reports validation separately. Discovery alone does not select or execute providers; resources.instances supplies the named selection.

Ordinary Implementation constructors may declare explicitly named canonical Resource parameters alongside required and optional Interface dependencies. plystra inspect implementations shows resource-contract nodes with exact resource_id and contract_digest, and declares-dependency edges with reason resource, exact parameter_name and one-based parameter_position. Repeated parameters for the same Resource remain distinct. These declarations are not Interface requirements or runtime activation. Selected instances and resolved bindings appear separately in inspect resources. Installed resource.consumer.discovery covers discovery and inspection, including dormant explicit and unselected candidates. Malformed Resource-shaped parameters report PLYSTRA_IMPLEMENTATION_REQUIRED_RESOURCE_INVALID with owning sources. Reachable consumers require named Resource bindings; dormant choices remain inactive.

Named instances are authored under resources.instances.<name> with one exact use provider constructor and typed instance-owned config, not top-level config. Names are exact, 1 through 128 ASCII bytes, matching [a-z][a-z0-9]*(?:-[a-z0-9]+)*(?:\.[a-z][a-z0-9]*(?:-[a-z0-9]+)*)*. A config-only higher layer may inherit use. With the same provider, non-pointer fixed Config structs compose by field and pointers and collections replace atomically. Changing use replaces the whole instance and discards old configuration even when field names match. Requiredness and defaults apply after composition. Template roots compose oldest to nearest before the selected current-Project delta; ordinary dependencies remain inactive.

Bind exact Go parameters with resources.bind.implementations.<constructor>.<parameter> or resources.bind.instances.<consumer-instance>.<parameter>. Each leaf names one exact instance; the old flat binding form is invalid. Explicit targets must exist and conform to the required Resource. Otherwise exactly one compatible selected instance binds implicitly; zero is missing and multiple matches are ambiguous. Provider identity, template depth, and declaration order never break ties. All explicit addresses are validated, including dormant Implementation consumers. Remove an instance or binding leaf only with {$remove: true}; null and empty mappings are not removal. Removal never silently retargets an explicit binding; dangling addresses and dependency cycles fail before generation.

Malformed Resource configuration reports PLYSTRA_RESOURCE_METADATA_INVALID, PLYSTRA_RESOURCE_CONFIGURATION_SCHEMA_INVALID, or PLYSTRA_RESOURCE_CONFIGURATION_VALUES_INVALID without private values. Invalid instance selections report PLYSTRA_RESOURCE_INSTANCE_INVALID. Missing, ambiguous, or invalid dependency targets report PLYSTRA_RESOURCE_BINDING_MISSING, PLYSTRA_RESOURCE_BINDING_AMBIGUOUS, or PLYSTRA_RESOURCE_BINDING_INVALID with owning sources. Correct the selected instance, exact consumer/parameter address, or required typed field, then rerun the same selector; do not remove a still-needed dependency to bypass validation.

Every selected instance is active even when unconsumed. The same provider under different names produces distinct values, Config owners, and lifecycle members. Each named instance is constructed once and shared across its consumers. Providers depend only on Resources; Implementations may mix Resource and Interface dependencies. Resources do not create Interface roots, catalog entries, governed proxies, exposure, or transport output. Dependencies construct and start first; consumers stop first. Constructors only assemble values, with acquisition in Start. Failure cleanup includes non-nil partial constructor results and never-started lifecycle values; Stop must tolerate those states. Nil/nil and panics fail safely, and bounded cleanup failures remain retryable.

Generated typed configuration and Secrets are loaded per instance from the selected documents and source-independent private runtime baseline. Validate every selected object before resolving Secrets or entering constructors. Runtime compatibility version 12 and frozen model version 19 cover named Resource structure. Instance identity, providers, bindings, and build-visible edits require regeneration and rebuilding. Valid runtime-only values and Secret references do not enter public generated identity; public artifacts exclude private values, reference targets, and private hashes.

Resource mutation forms of plystra use and plystra implement are not installed; both remain Interface-only. Author ordinary Go declarations and selected YAML, then run plystra generate, plystra generate --check, and plystra check with the same selector. Never hand-edit generated assembly. Read installed parsed, generated, executed, and accepted stages independently: implemented stages do not establish accepted=yes. Data schema/query generation and data migration plan|apply|status remain unsupported; Gate 5 is incomplete.

The template's complete effective graph must contain only public Go Modules. Creation rejects every direct or transitive module matched by the effective ` + "`GOPRIVATE`" + ` setting, reports its selected ` + "`path@version`" + `, and leaves no target Project. Publish or replace a genuinely private dependency before publishing the template, or correct an overbroad Go privacy setting before retrying.

Every dependency Plystra Project in the template graph must be portable without a relative Go Module ` + "`replace`" + `. Creation reports each remaining directive with stable ` + "`module@version/go.mod`" + ` provenance and leaves no target Project. Publish the referenced module versions and remove the relative replacements before publishing a corrected template.

The staged generated application must be a fixed point. Creation installs generated output and then runs an immediate ` + "`plystra generate --check`" + ` equivalent. Any stale, missing, unexpected, or manually modified generated path rejects the template and restores the transaction. The publisher must make generation deterministic, run ` + "`plystra generate`" + ` followed by ` + "`plystra generate --check`" + ` in a fresh Project directory, and publish a corrected module version.

Template creation next runs the same read-only workflow as ` + "`plystra check`" + `: it rechecks the selected configuration and generated output, then runs ` + "`go test -mod=readonly ./...`" + ` from the staged Project root. Any failure restores the creation transaction and leaves no target Project. The publisher must make that public check pass in a fresh Project directory before publishing a corrected version.

Template creation then builds every staged Go package with ` + "`go build -mod=readonly ./...`" + `. When ` + "`generated/sdk/javascript/package.json`" + ` exists, it also runs ` + "`npm install --ignore-scripts --no-audit --no-fund`" + `, ` + "`npm run typecheck`" + `, ` + "`npm run build`" + `, and ` + "`npm pack --dry-run --json`" + ` through npm using that generated package's declared scripts and dependencies. Validation-only ` + "`node_modules/`" + ` and ` + "`dist/`" + ` output is removed before installation. It then builds the generated application entrypoint with ` + "`GOWORK=off`" + ` into isolated temporary output, starts the real assembled runtime, invokes intrinsic ` + "`kernel.health/v1`" + `, and stops lifecycle providers cleanly. Child output is suppressed and temporary smoke output is removed on every path. Any failure restores the creation transaction and leaves no target Project. This private qualification executable does not create public distribution output.

Root ` + "`plystra.yaml`" + ` is the mandatory Project marker and shared default configuration. A sparse project-root ` + "`plystra.production.yaml`" + ` can be selected with ` + "`plystra generate --env production`" + ` and checked with the same selector; it is never created or loaded implicitly. To use one complete alternative current-Project document, run ` + "`plystra generate --config deploy/customer-a.yaml`" + `. Root configuration is not merged beneath an explicitly selected file. ` + "`PLYSTRA_ENV`" + ` and ` + "`PLYSTRA_CONFIG`" + ` supply the corresponding selector for automation; select exactly one mode.

Start the generated application with the required explicit configuration root and the same selector used for generation: ` + "`go run ./generated/go/application --configuration-root . --runtime-baseline dist/runtime-baseline.json --env production`" + ` selects one sparse overlay, while ` + "`go run ./generated/go/application --configuration-root . --runtime-baseline dist/runtime-baseline.json --config deploy/customer-a.yaml`" + ` selects one complete replacement. Generated startup uses root ` + "`plystra.yaml`" + ` when no selector is present and accepts ` + "`PLYSTRA_ENV`" + ` or ` + "`PLYSTRA_CONFIG`" + ` when the corresponding flag is omitted. An explicit selector overrides both ambient variables, and the two modes cannot be combined. Replacement mode still requires a regular root Project marker but does not parse or merge its top-level application declarations. The selected replacement must be an existing nonsymbolic regular file inside the explicit configuration root. Unsafe or missing selections and invalid typed changes fail before Implementation construction, and unselected files are ignored. Generated manifest configuration provenance records the matching selected document and explicit template composition, each exact dormant Interface choice, and one constructor-keyed dormant configuration record with normalized field digests, redacted summaries, owners, suppressed descendants, and replacement/removal history. It contains no raw configuration values or Secret targets. Activation removes the affected dormant records and places the same choice and configuration ownership in reachable binding provenance. Bootstrap records only the bounded build-affecting projection of public exposure entries with their transports, CORS, requirements, executable Implementation choices, and Interface timeout and retry policies tied to the complete compiled application-model digest. Dormant choices and dormant constructor configuration create no bootstrap runtime membership or artifact-provenance change. Startup rejects a different build-affecting projection with rebuild guidance before reading startup settings, resolving Secrets, or constructing Implementations. Runtime-only address, ` + "`timeouts.startup`" + `, ordinary configuration, and Secret-reference changes remain valid when their typed values are valid. Generated source never embeds YAML values, Secret-reference targets, resolved Secrets, or machine paths.

Authored static Interface timeout and replay-safe retry policies execute through the selected binding. Retry requires timeout and the explicit eligibility: replay_safe assertion about the binding and its downstream effects; safety is never inferred. max_attempts counts the first attempt, defaults to 2, and permits 2 through 16; backoff defaults to 0s and accepts nonnegative Go durations. One total budget starts before request validation and copying, is capped by an earlier caller deadline, and includes all attempts, backoff, and response processing. Each attempt receives a fresh copy of the original request snapshot and starts only after the previous target terminates. The outermost retry-enabled binding owns replay; nested bindings suppress their own retries. Only not_started resource exhaustion and result_known unavailable or resource exhaustion can retry. Semantic errors, cancellation, deadlines, internal or validation failures, and result_unknown never replay; exhaustion retains the final safe category, completion, and bounded attempt count. Without retry there is one attempt; without timeout there is no added deadline. Complete compiled policy values and literal schema/compiler/defaults versions are frozen before runtime; mismatches fail closed. Dormant policies remain intent outside executable identity until activation. Inspect capabilities reports support stages, exact defaults, and duration bounds. Authored concurrency, queue, and circuit forms remain unsupported. Transitional legacy Capability wrappers do not include preparation and completion in the Kernel budget; active authored policies on that path still fail with PLYSTRA_POLICY_NOT_ENFORCED. Capability discovery reports that exception as legacy.capability-timeout with executed=no and accepted=no.

New Projects write ` + "`http.expose: {}`" + ` as an empty delta that preserves inherited template exposure. No external transport is selected only when the effective exposure is empty. Each exact Interface key requires ` + "`transport: connect`" + `; JavaScript SDK generation requires Connect and follows those selected entries. In a later template root or selected current-Project layer, omitted entries inherit, complete entries replace, and an exact-key ` + "`{$remove: true}`" + ` removes inherited exposure. Empty mappings preserve inherited entries. Exposure lists, set edits, global transport switches, and unsupported REST fields are invalid.

Cross-origin browser access is opt-in. Add ` + "`http.cors.allowed_origins`" + ` to the selected current-Project configuration, and set ` + "`allow_credentials: true`" + ` only for exact origins. Generated Connect handlers require one canonical normalized HTTP/HTTPS request origin of at most 4096 bytes; literal ` + "`null`" + ` is accepted only by a noncredentialed wildcard policy. Preflight accepts only ` + "`POST`" + ` and the fixed ` + "`Authorization`" + `, ` + "`Connect-Protocol-Version`" + `, ` + "`Connect-Timeout-Ms`" + `, and ` + "`Content-Type`" + ` headers, with each name present at most once across no more than four field values totaling at most 4096 bytes. Malformed, noncanonical, duplicate, over-bound, or disallowed input fails before trusted-root creation or Implementation invocation. Without ` + "`http.cors`" + `, generated handlers emit no CORS response headers.

When several compatible Implementations satisfy one required Interface, select one with ` + "`plystra use <interface-id> <constructor-symbol>`" + `. The same command may record a validated dormant choice before the Interface becomes required without activating its constructor. Constructor configuration for that dormant choice is type-checked immediately, but its Secret references remain unresolved and it enters no runtime, bootstrap, or Kernel state. Add ` + "`--env <environment>`" + ` to write only that sparse overlay or ` + "`--config <yaml-path>`" + ` to write only one complete replacement configuration; the command regenerates and validates with the same selection.

Common actionable Plystra CLI failures end with exactly one ` + "`Recovery:`" + ` block followed by one stable ` + "`Diagnostic: PLYSTRA_<AREA>_<CONDITION>`" + ` code. Authored Interface and Implementation failures, plus ` + "`PLYSTRA_CAPABILITY_REQUIREMENT_CONFLICT`" + `, ` + "`PLYSTRA_CAPABILITY_CONTRACT_CONFLICT`" + `, ` + "`PLYSTRA_CAPABILITY_SCHEMA_CONFLICT`" + `, ` + "`PLYSTRA_PROVIDER_MISSING`" + `, ` + "`PLYSTRA_PROVIDER_AMBIGUOUS`" + `, ` + "`PLYSTRA_PROVIDER_SELECTION_INVALID`" + `, ` + "`PLYSTRA_PROVIDER_CONTRACT_CONFLICT`" + `, ` + "`PLYSTRA_PROVIDER_CONTRACT_MISMATCH`" + `, ` + "`PLYSTRA_RESOLVE_MULTIPLE_IMPLEMENTATIONS`" + `, ` + "`PLYSTRA_RESOLVE_MISSING_IMPLEMENTATION`" + `, ` + "`PLYSTRA_RESOLVE_CONSTRUCTOR_CYCLE`" + `, ` + "`PLYSTRA_RESOLVE_UNKNOWN_IMPLEMENTATION`" + `, ` + "`PLYSTRA_RESOLVE_INCOMPATIBLE_IMPLEMENTATION`" + `, and ` + "`PLYSTRA_RESOLVE_INTRINSIC_INTERFACE_SELECTION`" + `, insert sorted ` + "`Source: <module>:<module-relative-path>[:<line>:<column>] (<kind>)`" + ` lines before recovery; Capability requirement conflict includes every source for each incompatible exact contract, visible Capability contract conflict includes every conflicting Provider declaration, Capability schema conflict includes both declarations that block authoring, Provider ambiguity includes every compatible Provider declaration, invalid selection includes every effective choice declaration, Provider contract conflict includes every reference-only requirement plus each conflicting Provider declaration, contract mismatch includes every exact-contract requirement plus each incompatible Provider declaration, Interface Implementation ambiguity includes every compatible constructor declaration, missing Implementation includes every root declaration or exposure plus every requiring constructor in each complete dependency path, a constructor cycle includes every requiring constructor declaration in the complete cycle, and an unknown, incompatible, or intrinsic explicit Interface Implementation choice includes every effective ` + "`interfaces.use`" + ` declaration as ` + "`implementation-selection`" + `. For an intrinsic choice, set the selected current-Project entry to ` + "`{$remove: true}`" + ` to remove either a local or inherited effective selection because Kernel supplies that Interface intrinsically. They never expose absolute or Module Cache paths. Follow that one command or file edit with the same default, ` + "`--env`" + `, or ` + "`--config`" + ` selection, and use the code rather than human wording as the automation or support identity. Recovery output preserves safe explicit and ambient selectors, but uses ` + "`<environment>`" + ` or ` + "`<yaml-path>`" + ` instead of echoing an unsafe or absolute selector. An unclassified internal error remains unchanged and does not receive guessed advice or a code.

` + "`PLYSTRA_PROJECT_MANIFEST_INVALID`" + ` reports exactly one current or dependency Project ` + "`plystra.yaml`" + ` as a ` + "`project-marker`" + ` source. A malformed readable document uses the conservative ` + "`1:1`" + ` span; an unsafe or unreadable marker omits the unavailable line and column. Correct the owning Project, or select a corrected dependency version, rather than editing a Module Cache copy.

` + "`PLYSTRA_CAPABILITY_MANIFEST_INVALID`" + ` reports an invalid current or dependency Provider ` + "`capability.yaml`" + ` at ` + "`1:1`" + ` as a ` + "`provider-declaration`" + ` source. Correct it in the owning Project or select a corrected dependency version. Generation, checks, inspection, explanation, and Capability creation, implementation, or exposure fail before mutation and never print an absolute or Module Cache path.

` + "`PLYSTRA_RESOLVE_UNKNOWN_INTERFACE`" + ` reports every effective ` + "`interfaces.require`" + ` or ` + "`http.expose`" + ` declaration as a ` + "`declaration`" + ` or ` + "`exposure`" + ` source, or every effective ` + "`interfaces.use`" + ` declaration as ` + "`implementation-selection`" + `. Current selected documents and effective template contributors retain their owning Project module and module-relative path.

` + "`PLYSTRA_RESOLVE_RESERVED_INTERFACE`" + ` reports an application-authored ` + "`kernel.*`" + ` Interface as one ` + "`interface-declaration`" + ` source in its owning current or dependency Project. Remove that declaration there and import the canonical Kernel Interface package; never edit a Module Cache copy.

` + "`PLYSTRA_CONFIGURATION_INVALID`" + ` reports a malformed selected environment or complete-replacement document at ` + "`1:1`" + ` as a ` + "`configuration-declaration`" + ` source. Correct that selected file; source facts contain no configured values or machine paths.

` + "`PLYSTRA_ENVIRONMENT_OVERLAY_INVALID`" + ` reports the selected ` + "`plystra.<environment>.yaml`" + ` at ` + "`1:1`" + ` as a ` + "`configuration-declaration`" + ` source when typed overlay application is invalid. Correct the reported field relationship there; values and machine paths remain excluded.

` + "`PLYSTRA_GENERATED_DRIFT`" + ` reports every stale, missing, or manually modified managed path as a sorted ` + "`generated-artifact`" + ` source in the current Project module. These path-only facts omit line and column rather than inventing a span. Regenerate with the same selection instead of editing owned output. ` + "`PLYSTRA_GENERATED_OWNERSHIP_CONFLICT`" + ` reports the single desired managed path occupied by different unowned bytes or a non-regular entry as a ` + "`generated-artifact`" + ` source, without a fabricated span. Move the reported entry outside ` + "`generated/`" + `, then rerun generation with the same selection; it is never overwritten. ` + "`PLYSTRA_GENERATED_UNEXPECTED_OUTPUT`" + ` reports every unexpected unowned path as a sorted ` + "`generated-artifact`" + ` source. Move each reported path outside ` + "`generated/`" + `; strict compound mutations remain rolled back until those paths are moved.

` + "`PLYSTRA_GENERATED_MANIFEST_INVALID`" + ` reports ` + "`generated/.plystra-manifest.json`" + ` as a path-only ` + "`generated-artifact`" + ` source. Restore it from a known-good generated state, then regenerate with the same selection.

` + "`PLYSTRA_PROTOBUF_WIRE_HISTORY_INVALID`" + ` reports ` + "`generated/proto/wire-map.json`" + ` as a path-only ` + "`generated-artifact`" + ` source. Restore its exact last known-good generated state, then regenerate with the same selection.

` + "`PLYSTRA_PROTOBUF_IDENTITY_COLLISION`" + ` reports the owning Interface Go file at the trusted declaration position as an ` + "`interface-contract`" + ` source. Rename one conflicting authored field or enum member, then regenerate with the same selection; never patch generated names or wire history.

` + "`PLYSTRA_PROTOBUF_OPERATION_KIND_UNSUPPORTED`" + ` reports the effective ` + "`http.expose`" + ` document at ` + "`1:1`" + ` as an ` + "`exposure`" + ` source. Remove the named event or stream there, then regenerate with the same selector; never relabel the canonical contract to bypass the unary boundary.

` + "`PLYSTRA_PROTOBUF_POINTER_PROJECTION_UNSUPPORTED`" + ` reports the effective declaration's owning ` + "`http.expose`" + ` document at ` + "`1:1`" + ` as an ` + "`exposure`" + ` source when an active Interface requires pointer-presence wrappers that this CLI does not yet generate. Remove the pointer-bearing Interface there and regenerate with the same selector. A sparse environment overlay may inherit the declaration from ` + "`plystra.yaml`" + `, so edit the reported source rather than an empty overlay. The failed command changes no authored, generated, module, compatibility, or transaction file and exposes neither an absolute path nor a pointer value.

` + "`PLYSTRA_GO_MODULE_INVALID`" + ` reports the exact current-Project ` + "`go.mod`" + ` module or requirement position as a ` + "`module-dependency`" + ` source once Project identity is valid. Correct that declaration; a file that cannot establish a trustworthy module identity receives no invented source.

` + "`PLYSTRA_APPLICATION_DEPENDENCY_DRIFT`" + ` reports the current Project ` + "`go.mod`" + ` at ` + "`1:1`" + ` as a ` + "`module-dependency`" + ` source when the Kernel is missing or only transitive, or a generated runtime requirement has drifted. ` + "`plystra generate --check`" + ` and ` + "`plystra check`" + ` are read-only; normal generation transactionally restores the CLI-supported direct Kernel release and required runtime modules before validation.

` + "`PLYSTRA_PROJECT_CONCURRENT_CHANGE`" + ` reports every deterministically known path that changed while resolution or generation verified a stable snapshot. Current-Project and dependency ` + "`plystra.yaml`" + ` documents use ` + "`configuration-declaration`" + `; current-Project ` + "`go.mod`" + ` or ` + "`go.sum`" + ` uses ` + "`module-dependency`" + `; and managed ` + "`generated/...`" + ` paths use ` + "`generated-artifact`" + `. Sources are sorted, deduplicated, module-relative, and omit a fabricated span. Stop concurrent Project edits and rerun against unchanged inputs; rollback preserves bytes written by the other editor.

` + "`PLYSTRA_GENERATION_ACTIVATION_CONFLICT`" + ` reports every conflicting visible ` + "`generation.activations`" + ` entry at its exact ` + "`plugin.yaml`" + ` position as a ` + "`plugin-declaration`" + ` source. Shared canonicalization sorts and deduplicates current-Project and dependency-Project declarations. The bare internal conflict sentinel remains source-less rather than fabricating an entry. Make every declaration for the reported namespace name one exact activation Capability, then rerun with the same selection.

` + "`PLYSTRA_GENERATION_ACTIVATION_MISSING`" + ` reports every retained typed Capability requirement source for the reported unclaimed extension namespace in its owning Project module. Declaration and exposure sources are included; shared canonicalization sorts and deduplicates the facts. Because no visible ` + "`generation.activations`" + ` declaration exists, the diagnostic never fabricates an activation source. Add the association to the intended Plugin's ` + "`plugin.yaml`" + `, then rerun with the same selection.

` + "`PLYSTRA_GENERATION_PROVIDER_EXTENSION_MISSING`" + ` reports the selected Provider's existing ` + "`capability.yaml`" + ` at ` + "`1:1`" + ` as a ` + "`provider-declaration`" + ` source and every effective current-Project or dependency-Project ` + "`capabilities.use`" + ` document at ` + "`1:1`" + ` as a ` + "`provider-selection`" + ` source. Shared canonicalization sorts and deduplicates those authored facts. It never fabricates a source for the absent generation declaration, and the bare internal sentinel remains source-less. Add compatible generation support to the selected Provider in its owning Project or choose a compatible Provider reported by the diagnostic, then rerun with the same selection.

` + "`PLYSTRA_GENERATION_ACTIVATION_CYCLE`" + ` reports every retained typed requirement source carried by the complete deterministic activation cycle. Authored ` + "`declaration`" + ` and ` + "`exposure`" + ` facts and derived ` + "`activation`" + ` facts retain their originating module-relative path and span. Shared canonicalization sorts and deduplicates repeated edge facts, while the bare internal cycle sentinel remains source-less. Use the cycle details to edit the owning Capability metadata or ` + "`generation.activations`" + ` declarations so the semantic cycle is removed; changing execution order is not a fix.

` + "`PLYSTRA_GENERATION_DEPENDENCY_CYCLE`" + ` reports every retained typed requirement source carried by the complete deterministic mixed activation and generated-requirement cycle. Authored ` + "`declaration`" + ` and ` + "`exposure`" + ` facts and derived ` + "`activation`" + ` and ` + "`generation-rule`" + ` facts retain their originating module-relative location; generation-rule facts identify the generating Plugin's ` + "`plugin.yaml`" + ` at ` + "`1:1`" + `. Shared canonicalization sorts and deduplicates repeated edge facts, while the bare internal dependency-cycle sentinel remains source-less. Use the complete edge path and reported sources to remove the semantic cycle from Capability metadata or the owning generation rule; changing execution order cannot make the dependency cycle valid.

` + "`PLYSTRA_GENERATION_CONTRIBUTION_CYCLE`" + ` reports the typed ` + "`generation-rule`" + ` source for every contribution that provides or consumes a token in the complete deterministic cycle. Each fact identifies the selected contribution owner by its Project module and module-relative ` + "`plugin.yaml`" + ` at ` + "`1:1`" + `; shared canonicalization sorts and deduplicates repeated endpoint facts. The bare internal contribution-cycle sentinel remains source-less. Use the contribution and token path to remove the semantic cycle from the owning generation rules; discovery or execution order cannot make the token cycle valid.

` + "`PLYSTRA_GENERATION_CONTRIBUTIONS_UNORDERED`" + ` reports the typed ` + "`generation-rule`" + ` source for every simultaneously ready contribution at an ordered generation point. Each fact identifies the selected contribution owner by its Project module and module-relative ` + "`plugin.yaml`" + ` at ` + "`1:1`" + `; shared canonicalization sorts the sources and deduplicates multiple contributions from one declaration. The bare internal unordered sentinel remains source-less. Add ` + "`requires`" + ` and ` + "`provides`" + ` tokens that establish one semantic order among the reported contributions; discovery order is never used as an implicit tie-break.

` + "`PLYSTRA_GENERATION_STATE_REPEATED`" + ` reports each selected extension whose normalized output changed for the identical immutable context. Every ` + "`plugin-declaration`" + ` source identifies the owning Project module and module-relative ` + "`plugin.yaml`" + ` at ` + "`1:1`" + `; shared canonicalization sorts and deduplicates the declarations, stable extensions are excluded, and the bare internal sentinel remains source-less. Make each reported generation package deterministic and convergent for identical normalized input.

` + "`PLYSTRA_GENERATION_NONCONVERGENT`" + ` reports the typed ` + "`generation-rule`" + ` sources from the most recent pass that introduced previously unseen canonical requirements. Each source identifies the selected extension owner's Project module and module-relative ` + "`plugin.yaml`" + ` at ` + "`1:1`" + `; shared canonicalization sorts the sources and deduplicates multiple rules from one declaration. Stable extensions and rules that added no requirement in that growth pass are excluded, and the bare internal sentinel remains source-less. Remove or bound the reported generation-rule chain so it reaches a stable closure within the finite catalog-derived pass bound.

` + "`PLYSTRA_GENERATION_EXTENSION_DIAGNOSTIC`" + ` reports the typed ` + "`generation-rule`" + ` sources for every distinct selected-extension rule that returned a structured error diagnostic. Each source identifies the selected extension owner's Project module and module-relative ` + "`plugin.yaml`" + ` at ` + "`1:1`" + `; shared canonicalization sorts the sources and collapses multiple error diagnostics or rules from one declaration to one human location. Info and warning diagnostics do not fail generation, and the bare internal sentinel remains source-less. Fix the reported selected generation package so its error diagnostics are resolved, then rerun the same command.

` + "`PLYSTRA_GENERATION_API_UNSUPPORTED`" + ` reports the exact unsupported ` + "`generation.api`" + ` scalar at its current-Project or dependency-Project ` + "`plugin.yaml`" + ` position as a ` + "`plugin-declaration`" + ` source. A bare helper or manifest API sentinel remains source-less rather than inventing a declaration. Change the reported declaration to the supported generation API, then rerun the same command.

` + "`PLYSTRA_GENERATION_PACKAGE_INVALID`" + ` reports the exact ` + "`generation.package`" + ` scalar at its current-Project or dependency-Project ` + "`plugin.yaml`" + ` position as a ` + "`plugin-declaration`" + ` source. A bare package sentinel remains source-less rather than inventing a declaration. Create a real non-symbolic Go package at the reported confined path or update the declaration to an existing safe package, then rerun the same command.

` + "`PLYSTRA_GENERATION_COMPILE_FAILED`" + ` reports the exact ` + "`generation.package`" + ` scalar for the selected helper at its current-Project or dependency-Project ` + "`plugin.yaml`" + ` position as a ` + "`plugin-declaration`" + ` source. A bare compile sentinel remains source-less rather than inventing a declaration. Fix the reported package's source, imports, dependencies, or ` + "`Generate`" + ` signature, then rerun the same command. Compiler output never exposes checkout, Module Cache, or helper temporary paths.

Selected-helper invocation failures use ` + "`PLYSTRA_GENERATION_EXECUTION_FAILED`" + `, ` + "`PLYSTRA_GENERATION_EXTENSION_FAILED`" + `, ` + "`PLYSTRA_GENERATION_CRASHED`" + `, ` + "`PLYSTRA_GENERATION_TIMEOUT`" + `, ` + "`PLYSTRA_GENERATION_REQUEST_TOO_LARGE`" + `, ` + "`PLYSTRA_GENERATION_OUTPUT_TOO_LARGE`" + `, ` + "`PLYSTRA_GENERATION_OUTPUT_MALFORMED`" + `, or ` + "`PLYSTRA_GENERATION_OUTPUT_INVALID`" + `. Each reports the exact ` + "`generation.package`" + ` scalar at its current-Project or dependency-Project ` + "`plugin.yaml`" + ` position as a ` + "`plugin-declaration`" + ` source. A compile deadline is classified as ` + "`PLYSTRA_GENERATION_TIMEOUT`" + ` and retains the same source. Bare or unlocated invocation and orchestration sentinels and aggregate helper-cleanup failures remain source-less rather than inventing one selected declaration. The source identifies the selected invocation boundary; it does not by itself imply faulty helper code. Use the diagnostic code to correct local execution prerequisites, request size, helper behavior, or returned output, then rerun the same command.

` + "`PLYSTRA_CONFIGURATION_SELECTION_INVALID`" + ` identifies conflicting explicit or ambient modes, duplicated selector variables, unsafe selectors, and missing selected documents. A normalized Project-contained document that cannot be loaded reports one path-only ` + "`configuration-selection`" + ` source without a fabricated span. Conflicting, duplicated, or unsafe selectors report no source because no document is trustworthy. Use exactly one intended selector; an explicit mode conflict fails before Project discovery or mutation, and its recovery never echoes either value.

` + "`plystra plugin create`" + ` uses ` + "`PLYSTRA_PLUGIN_CREATE_NAME_INVALID`" + ` for an invalid or reserved root-level name, ` + "`PLYSTRA_PLUGIN_CREATE_ID_INVALID`" + ` when the Project module namespace and name cannot form a canonical Plugin ID, and ` + "`PLYSTRA_PLUGIN_CREATE_TARGET_EXISTS`" + ` for an existing Plugin directory. Each failure occurs before scaffold installation, leaves the Project unchanged, and emits recovery with placeholders instead of rejected input.

Authored Interface failures distinguish invalid directives, canonical Go contracts, optional interface.yaml metadata, duplicate visible IDs, and packages ordinary Go tooling cannot load. Apply the emitted recovery to the reported ` + "`Source:`" + ` in its owning Project; never edit a dependency's Module Cache copy.

Authored Implementation failures distinguish invalid directives, Config schemas, required or optional Interface parameters, constructor results, and structural conformance. Apply the emitted recovery to the reported ` + "`Source:`" + `. Fix dependency-owned source in its owning Project or select a corrected module version; never edit the Module Cache copy.

` + "`plystra use`" + ` rejects malformed canonical Interface IDs with ` + "`PLYSTRA_USE_INTERFACE_INVALID`" + ` and malformed fully qualified constructor symbols with ` + "`PLYSTRA_USE_CONSTRUCTOR_INVALID`" + ` before Project mutation. Run the emitted corrected command with the same default, environment, or complete-replacement selection.

` + "`PLYSTRA_CONSTRUCTOR_CONFIGURATION_SCHEMA_INVALID`" + ` identifies constructor-keyed configuration whose constructor has no discovered compiled same-package ` + "`Config`" + ` schema. Select a discovered constructor with one or remove the entry in the reported owning Project document. The diagnostic emits exactly one ` + "`configuration-declaration`" + ` source at ` + "`1:1`" + ` and never prints configured values, Secret-reference targets, absolute paths, or Module Cache paths.

` + "`PLYSTRA_CONSTRUCTOR_CONFIGURATION_VALUES_INVALID`" + ` identifies a safe declared field whose value does not match the discovered compiled same-package ` + "`Config`" + ` schema. Correct it in the selected current-Project document or the owning template root. The diagnostic emits exactly one ` + "`configuration-declaration`" + ` source at ` + "`1:1`" + ` and never prints configured values, unknown authored keys, Secret-reference targets, absolute paths, or Module Cache paths.

` + "`PLYSTRA_CONSTRUCTOR_CONFIGURATION_UNSELECTED`" + ` identifies constructor-keyed configuration whose constructor is neither named by an effective ` + "`interfaces.use`" + ` choice nor reachable from an active Interface. Name it in an effective choice, make it reachable through an Interface requirement, or remove its configuration from the selected document. The diagnostic reports every effective contributing Project document at ` + "`1:1`" + ` as a sorted ` + "`configuration-declaration`" + ` source and never prints configured values or Secret-reference targets.

Interface and Implementation scaffold failures distinguish invalid or missing identities, unsafe package paths, and existing targets before mutation. Interface creation collisions report the occupied module-relative package path without a fabricated span, or the owning current or dependency Interface declaration with its exact span. Follow the emitted corrected command or replacement choice; existing source remains unchanged.

Generated source under ` + "`generated/`" + ` is owned by the Plystra CLI. Do not edit it manually; commit it to Git.

An ordinary Interface message field ` + "`T`" + ` has no business-observable presence state: omission and its Go zero value normalize identically. A direct ` + "`*T`" + ` distinguishes absent from a present value, including zero or empty, while a direct ` + "`**T`" + ` adds explicit null. Pointers are accepted only as one or two direct layers at a message-field boundary; they are invalid inside repeated elements, map keys or values, or another supported type, and a pointer-to-message edge cannot create a recursive cycle.

A ` + "`required`" + ` ordinary field is meaningful only at a representation that retains occurrence, such as a validated example or transport input. A required ` + "`*T`" + ` rejects absence. A required ` + "`**T`" + ` also rejects absence but still permits explicit null because requiredness checks the outer pointer state. The contract model applies constraints through pointer layers to a present, non-null innermost value and treats nil and allocated-empty bytes, repeated values, and maps as the same canonical empty value without changing a pointer field's outer absent, null, or present state.

Current support implements that model for Interface declaration parsing, ` + "`interface.yaml`" + ` constraint and example validation, compatibility classification, and generated governed calls. Generated proxies check pointer requiredness before constraints and copy normalized requests into isolated snapshots. Adapters give each target execution a fresh copy, and proxies validate and copy successful responses into caller-owned storage. The generated proxy's ` + "`CopyRequest`" + ` and ` + "`CopyResponse`" + ` apply those checks in direct Implementation tests. Traversal is bounded to 64 levels and 65,536 nodes. Use errors.As to inspect a generated ` + "`ValueError`" + ` for the Interface, side, field path, and rule; it retains no submitted value or map key. Invalid requests never enter the target, and invalid responses return an internal contract error without a result. Pointer-bearing Connect exposure still fails closed until transport projections preserve those states. Caller cancellation returns independently with result_unknown after target entry; late results are discarded. Response validation and copying remain inside the tracked attempt. Generated InterfaceRuntime.Drain closes admission and waits for actual termination; Stop drains before any lifecycle cleanup. Drain and cleanup share the construction/startup cleanup timeout and any earlier caller deadline. Failed drain keeps dependencies live for a fresh bounded Stop retry. Each exact binding admits 64 attempts with no queue; permits remain held through target termination and response copying, even after caller cancellation. Saturation returns resource_exhausted with not_started (Connect/HTTP 429); JavaScript preserves both facts. The frozen model version 19 and Interface provenance v3 record every compiled policy field, including disabled stages and literal compatibility identities. No authored timeout means no added deadline. Authored replay-safe retries use one total timeout budget, fresh request copies, and outermost ownership without overlapping attempts. Authored concurrency, queue, and circuit policies remain unsupported. Generated static calls emit separate Kernel OpenTelemetry caller.duration and target.duration histograms under plystra.invocation; counts distinguish logical calls from entered target attempts, including late termination. Configure the global MeterProvider before bootstrap and shut it down only after successful drain. Labels contain only resolved binding and safe bounded outcome facts, never request values or dynamic identities; no SDK means no-op metrics. Governed spans and broader telemetry remain unfinished.

` + "`generated/compatibility/interfaces.json`" + ` is the committed, CLI-owned replaceable shape working record for every visible authored Interface, whether or not it is selected or exposed. It records package and method identity, request and response names, reachable messages, stable field numbers, Go and JSON names, requiredness, direct pointer depth, and canonical Go types while excluding metadata, projections, Implementations, configuration, Secrets, source paths, and module versions. ` + "`plystra generate`" + ` refreshes it transactionally and ` + "`plystra generate --check`" + ` reports drift without mutation. Never edit it manually.

` + "`generated/compatibility/interface-metadata.json`" + ` is the matching committed, CLI-owned compatibility-class working record. Schema ` + "`plystra.interface-metadata-baseline/v2`" + ` stores the normalized exact-contract, ` + "`contract_supplement_digest`" + `, documentation, and example digests, never metadata values. The supplement covers semantics, semantic-error codes, constraints, and Behavioral Conformance independently of Go shape. Generation migrates an owned canonical v1 record to v2 in the same transaction as its ownership manifest and restores both on rollback; ` + "`plystra generate --check`" + ` reports the migration as stale without mutation. Never edit it manually.

` + "`generated/compatibility/interface-transport.json`" + ` is the committed, CLI-owned working record for every Interface on the selected Connect surface. It stores separate Protobuf-descriptor, Connect-procedure, and active wire-map digests, including the shared safe-error descriptor but no raw contract, Implementation, configuration, Secret, path, or module-version values. ` + "`plystra generate`" + ` updates it transactionally, and ` + "`plystra generate --check`" + ` compares those classes without mutation. Never edit it manually.

` + "`generated/compatibility/interface-javascript.json`" + ` is the committed, CLI-owned caller-visible JavaScript API working record for every successfully projected exposed Interface. It stores separate shared package-root, client/factory surface, public TypeScript shape, and semantic-error-union digests without Implementation, configuration, Secret, source-location, or module-version values. ` + "`plystra generate`" + ` updates it transactionally, and ` + "`plystra generate --check`" + ` compares those classes without mutation. Never edit it manually.

` + "`generated/compatibility/interface-documentation.json`" + ` is the committed, CLI-owned working record for the current ` + "`generated/docs/api.md`" + ` and ` + "`generated/docs/openapi.json`" + ` artifacts. It stores only each closed artifact kind, stable managed path, and exact content digest, including a valid empty record when no documentation surface is selected. It contains no documentation bytes, Implementation, configuration, Secret, source-location, or module-version values. ` + "`plystra generate`" + ` updates it transactionally, and ` + "`plystra generate --check`" + ` reports documentation drift without mutation. Never edit it manually.

The five compatibility working records listed above are replaceable current-source state whose ownership-manifest output kind is ` + "`compatibility-working-record`" + `. Classification is per record and ownership entry, not directory-wide. They are not accepted release baselines. Accepted baselines are separate immutable release evidence keyed to an exact released artifact and source lineage; ordinary generation, check, cleanup, transaction recovery, or relabeling cannot create, overwrite, or delete them.

Changing an existing field among ` + "`T`" + `, ` + "`*T`" + `, and ` + "`**T`" + `, changing its innermost type, or otherwise adding or removing an observable state is a breaking compatibility classification. Pre-stable development may refresh the replaceable working records in place; once an accepted stable baseline applies, the change requires a new Interface version. A newly numbered non-required pointer field is retained as an additive candidate only when shape and v2 supplement evidence show that the edit is shape-only. The stable-release assessment still reports a version requirement until every public projection and immutable accepted ancestor also classifies the new field as optional.

The required top-level ` + "`interface_provenance`" + ` record in ` + "`generated/manifest.json`" + ` uses schema ` + "`plystra.interface-provenance/v3`" + `. It joins every visible authored Interface to reachable bindings, explicit or unique-compatible constructor selections, the complete dependency-first constructor graph, configuration ownership, root and exposure sources, effective Interface-policy inputs, and exact generated proxy, adapter, assembly, Protobuf, wire-map, Connect, HTTP-route, and JavaScript mappings and digests. Required intrinsic ` + "`kernel.*`" + ` Interfaces are recorded separately without an ordinary constructor or Implementation adapter. The exact same canonical record is embedded in ` + "`generated/.plystra-manifest.json`" + `. It contains no configuration values, Secret-reference targets, resolved Secrets, process environment, or machine-specific absolute paths. Never edit either manifest; change authored inputs, regenerate, and require a clean ` + "`plystra generate --check`" + `.

Ownership-manifest schema 3 records one immutable entry for every managed artifact: Project-relative path and SHA-256, exact generator/version, closed output kind, normalized non-secret input-record IDs, stable source references, and ` + "`cli-owned`" + ` cleanup authority. The manifest's own provenance is implicit because it cannot contain its own stable digest. An entry remains useful when its target is missing or manually modified. Never edit this evidence; use it to find the authored input, then regenerate.

The required top-level ` + "`transport_toolchain`" + ` record in ` + "`generated/manifest.json`" + ` identifies the exact embedded ` + "`go/format`" + ` runtime; built-in Protobuf-model, descriptor, wire-map, Connect, JavaScript, and API-documentation generator versions; pinned generated Go and npm dependency versions; and its canonical digest. ` + "`plystra generate --check`" + ` reports drift when that identity changes. Plystra generation does not invoke an implicit global ` + "`protoc`" + ` or generator executable and does not use a hosted generation service.

For each pointer-free Interface successfully projected through Connect, the generated JavaScript SDK publishes one nested client method, one tree-shakable factory, its declared semantic-error-code union, and deterministic request, response, and reachable nested-message types from the authored Go contract. For ` + "`records.echo/v1`" + `, call ` + "`client.records.echo.v1(request)`" + ` or ` + "`createRecordsEchoV1(options)(request)`" + `. Both forms use the same exact Connect procedure and safe runtime boundary. Effective JSON names and required markers remain exact. ` + "`int32`" + ` and ` + "`uint32`" + ` become JavaScript ` + "`number`" + `; ` + "`int64`" + ` and ` + "`uint64`" + ` become ` + "`bigint`" + `; floating-point fields become ` + "`number`" + `; bytes become ` + "`Uint8Array`" + `; timestamps and durations use their canonical transport strings; repeated values are readonly arrays; and maps are readonly string-keyed records. The unsafe JavaScript object key ` + "`__proto__`" + ` is rejected before dispatch rather than silently changed or dropped.

Import the generated JavaScript SDK only through its package root. Internal runtime, descriptor, codec, operation-binder, and raw Connect surfaces are blocked by the package export map and omitted from public declarations.

Generated client construction requires one explicit ` + "`credentialPolicy`" + `. Select ` + "`{mode: \"anonymous\"}`" + ` for no browser credentials, ` + "`{mode: \"cookie\", fetchCredentials: \"same-origin\"}`" + ` or ` + "`include`" + ` for an exact cookie policy, or ` + "`{mode: \"bearer\", getAccessToken}`" + ` for one bounded raw bearer token. Anonymous and bearer modes use Fetch credentials ` + "`omit`" + `; cookie mode sends no bearer header. Bearer callback rejection and nullish, empty, malformed, prefixed, control-containing, non-string, or oversized results fail before dispatch as ` + "`PlystraError`" + ` code ` + "`credential_error`" + ` without exposing credential data. A selected mode never falls back to another.

Pass an AbortSignal as the generated operation's second argument to cancel before dispatch, while bearer acquisition is pending, or while fetch is in flight. Cancellation rejects with PlystraError code cancelled. Once server invocation has begun, the generated Connect handler preserves that caller cancellation through the trusted Kernel root, canonical application invocation, and Implementation context. The same handler preserves the earlier caller or trusted-root Go context deadline and reports deadline_exceeded without a response when invocation observes it. Cancellation and deadlines are best-effort interruption and do not promise Implementation rollback or compensation.

` + "`generated/proto/wire-map.json`" + ` is committed compatibility history for the request, response, and reachable same-package messages of every visible authored Interface, whether or not the Interface is exposed or Connect is enabled. Exposed Connect Interfaces additionally retain their exact stable service, method, and procedure identity. Authored positive ` + "`plystra`" + ` field numbers are the wire numbers. Generation rejects renumbering and reuse across all visible Interface history, permanently reserves every removed Protobuf field name and number, and carries active reservations into generated source and the descriptor set. Never-exposed Interfaces, removed exposure, and disabled Connect remain inactive and create no schema, descriptor, handler, or SDK output, while their field names and numbers remain in wire history and pointer depth remains in the authored-shape working record. The ledger temporarily retains separately labelled legacy transport history required by pre-Gate-14 handlers; that bridge is not Interface contract authority. Never edit or delete the ledger. If it drifts, recover the exact previously generated content before running ` + "`plystra generate`" + `.

Generation emits one deterministic ` + "`.proto`" + ` schema with the canonical messages and exactly one unary service from every supported pointer-free exposed Interface package, plus a self-contained ` + "`generated/proto/descriptor-set.pb`" + `. The Connect procedure path is derived from the exact Interface ID. An overlapping pre-Gate-14 legacy schema is import-only and owns no competing service. A Project without a selected Connect surface retains a valid empty descriptor set. These files contain no Implementation, configuration, or Secret data, are CLI-owned, and are checked by ` + "`plystra generate --check`" + `.

Every selected Connect application failure carries one shared ` + "`PlystraErrorDetail`" + `. Its ` + "`requested_interface_id`" + ` records the requested canonical Interface or temporary pre-removal Alias, ` + "`canonical_interface_id`" + ` records the canonical Interface target, and exactly one declared semantic code or closed Kernel class is present. Alias handlers preserve the requested Alias while invoking only the canonical target. Implementation text, causes, payloads, panic data, configuration, credentials, Secrets, and internal Kernel detail codes never enter this descriptor. The generated JavaScript wrapper exposes only the validated immutable Plystra detail; a missing, duplicate, malformed, unknown, mismatched, or undeclared detail fails closed to ` + "`internal`" + `.

Catalog publication does not accept public work. Application Start opens both dispatchers only after complete dependency-ordered readiness. Lifecycle hooks pass their bounded context to already-ready injected dependencies, including during Stop after public admission closes; never retain that context for later work. Application Stop initiates both static and legacy dispatcher drains before waiting and retains both lifecycle sets if either drain fails. Standalone InterfaceRuntime owners call Start and then OpenAdmission; Application owners use Start alone.

Completion is independent of the primary error code: not_started, result_known, or result_unknown. The wire completion field is required, and the SDK exposes PlystraError.completion as well as detail.completion. Predispatch cancellation is not_started; in-flight interruption or an untrusted failure is result_unknown. An uncertain semantic error does not prove rollback or permit automatic resubmission.

Binary Protobuf requests are limited to 1 MiB, decoded with a maximum message depth of 64, and validated with a 65,536-node budget. Malformed or truncated wire data, unknown fields at any message depth, and requests that exceed any bound fail before root-context creation or Provider invocation; direct handler calls apply the same recursive validation. Binary Protobuf responses use the same size, depth, and node bounds. Generated conversion preflights canonical content before proportional wire-projection allocation, validates the exact response message, and serializes deterministically. Invalid or oversized responses produce only the safe internal response failure and no partial response on canonical, Alias, or direct handler paths. ProtoJSON requests independently accept at most 1 MiB, 64 nested JSON containers, and 65,536 structural tokens before strict decoding and the same canonical validation. Unknown or duplicate fields, malformed or trailing documents, invalid UTF-8, invalid required nulls, enum sentinels, non-finite numbers, and breached bounds fail before root-context creation or Provider invocation. Optional non-nullable null becomes absence. For non-required non-pointer scalar and value-message Interface fields, omission and an explicit Go zero value normalize to the same ordinary Go value; wire presence is not business-observable, and full-range integers remain exact. ProtoJSON responses use the same exact generated message and canonical response validation plus an independent 1 MiB serialized limit, with no partial response. Canonical and Alias binary and ProtoJSON paths agree.
`

const githubCIReadmeTemplate = `
## Continuous integration

GitHub Actions runs ` + "`go test ./...`" + ` and ` + "`go vet ./...`" + ` on Linux, Windows, and macOS, plus the Go race suite on Linux. Keep ` + "`.github/workflows/ci.yml`" + ` aligned with the local validation commands.
`

const agentGuidanceReadmeTemplate = `
## AI coding agents

Version-matched Plystra guidance lives in ` + "`.agents/skills/plystra/`" + `. The CLI owns ` + "`SKILL.md`" + `, ` + "`manifest.json`" + `, and the task files listed by that manifest. Project-specific additions belong in optional user-owned ` + "`local.md`" + `; the CLI never creates or edits that file, unlisted files, sibling skills, or repository-wide instructions.

Run ` + "`plystra guidance check`" + ` to compare the projection with the installed catalog without mutation. Ordinary ` + "`plystra guidance sync`" + ` installs an absent projection only when desired paths are free, then refreshes or removes only unchanged prior-manifest-owned files. A desired path absent from previous ownership blocks sync whether missing or occupied. Any blocking drift leaves the complete Project unchanged.

` + "`plystra guidance sync --replace-generated`" + ` may discard edits only in existing bounded regular prior-manifest-owned files. Missing prior-owned paths and desired paths absent from previous ownership remain blocked. Restore one complete matching generated projection or move an occupied conflict first. Drift reports ` + "`PLYSTRA_AGENT_GUIDANCE_DRIFT`" + `; an invalid ownership manifest reports ` + "`PLYSTRA_AGENT_GUIDANCE_MANIFEST_INVALID`" + `; and a path that changes after inspection reports ` + "`PLYSTRA_PROJECT_CONCURRENT_CHANGE`" + `. Each affected guidance path is reported as a path-only ` + "`agent-guidance`" + ` source.
`

const gitignoreTemplate = `/dist/
/generated/sdk/javascript/node_modules/
/generated/sdk/javascript/dist/
.env
.env.local
go.work
go.work.sum
`

const gitattributesTemplate = `* text=auto eol=lf
/generated/** linguist-generated=true
`

const ciTemplate = `name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v6
        with:
          go-version: "1.26.x"
          cache: true
      - run: go test ./...
      - run: go vet ./...

  race:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v6
        with:
          go-version: "1.26.x"
          cache: true
      - run: go test -race ./...
`
