// Code generated by Plystra CLI. DO NOT EDIT.

package emailsendv1

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"io"
	"mime"
	"net/http"
	"strings"

	contract "example.com/acme/project/generated/go/contracts/email/send/v1"
	applicationinvocation "example.com/acme/project/generated/go/invocation/email/send/v1"
	kernelinvocation "github.com/plystra/kernel/invocation"
)

const (
	RoutePath                  = "/api/v1/capabilities/email.send/v1/invoke"
	RoutePattern               = http.MethodPost + " " + RoutePath
	MaximumRequestBytes  int64 = 1048576
	MaximumResponseBytes       = 1048576
)

var ErrInvalidHandler = errors.New("invalid generated HTTP capability handler")

// RootContext establishes the trusted Kernel root for one external request.
type RootContext func(*http.Request) (context.Context, error)

// Handler validates HTTP transport before invoking the canonical generated application path.
type Handler struct {
	root   RootContext
	target applicationinvocation.Handle
}

// New binds the canonical exposed route to its generated invocation handle.
func New(root RootContext, target applicationinvocation.Handle) (Handler, error) {
	if root == nil || !applicationinvocation.Available(target) {
		return Handler{}, ErrInvalidHandler
	}
	return Handler{root: root, target: target}, nil
}

// Available reports whether the canonical generated handler is fully bound.
func Available(handler Handler) bool {
	return handler.root != nil && applicationinvocation.Available(handler.target)
}

// ServeHTTP accepts only the generated exact route and strict JSON contract.
func (h Handler) ServeHTTP(writer http.ResponseWriter, request *http.Request) {
	h.ServeRoute(writer, request, RoutePath)
}

// ServeRoute serves one CLI-validated canonical or Alias route through this canonical target.
func (h Handler) ServeRoute(writer http.ResponseWriter, request *http.Request, routePath string) {
	if request == nil || request.URL == nil {
		plystraWriteError(writer, http.StatusInternalServerError, "internal", "")
		return
	}
	if request.URL.Path != routePath || request.URL.RawPath != "" {
		plystraWriteError(writer, http.StatusNotFound, "not_found", "")
		return
	}
	if request.Method != http.MethodPost {
		writer.Header().Set("Allow", http.MethodPost)
		plystraWriteError(writer, http.StatusMethodNotAllowed, "method_not_allowed", "")
		return
	}
	if request.URL.RawQuery != "" {
		plystraWriteError(writer, http.StatusBadRequest, "invalid_request", "")
		return
	}
	contentEncodings := request.Header.Values("Content-Encoding")
	if len(contentEncodings) > 1 {
		plystraWriteError(writer, http.StatusUnsupportedMediaType, "unsupported_media_type", "")
		return
	}
	if len(contentEncodings) == 1 {
		contentEncoding := strings.TrimSpace(contentEncodings[0])
		if contentEncoding != "" && !strings.EqualFold(contentEncoding, "identity") {
			plystraWriteError(writer, http.StatusUnsupportedMediaType, "unsupported_media_type", "")
			return
		}
	}
	contentTypes := request.Header.Values("Content-Type")
	if len(contentTypes) != 1 || !plystraJSONContentType(contentTypes[0]) {
		plystraWriteError(writer, http.StatusUnsupportedMediaType, "unsupported_media_type", "")
		return
	}
	decoded, status, code := plystraDecodeRequest(writer, request)
	if code != "" {
		plystraWriteError(writer, status, code, "")
		return
	}
	if h.root == nil || !applicationinvocation.Available(h.target) {
		plystraWriteError(writer, http.StatusInternalServerError, "internal", "")
		return
	}
	ctx, err := plystraCreateRoot(h.root, request)
	if err != nil || ctx == nil {
		plystraWriteInvocationError(writer, err)
		return
	}
	response, err := plystraInvoke(ctx, h.target, decoded)
	if err != nil {
		plystraWriteInvocationError(writer, err)
		return
	}
	if !plystraValidResponse(response) {
		plystraWriteError(writer, http.StatusInternalServerError, "internal", "")
		return
	}
	payload, err := json.Marshal(response)
	if err != nil || len(payload) > MaximumResponseBytes {
		plystraWriteError(writer, http.StatusInternalServerError, "internal", "")
		return
	}
	plystraWriteJSON(writer, http.StatusOK, payload)
}

func plystraJSONContentType(value string) bool {
	mediaType, parameters, err := mime.ParseMediaType(value)
	if err != nil || mediaType != "application/json" || len(parameters) > 1 {
		return false
	}
	charset, hasCharset := parameters["charset"]
	return !hasCharset || strings.EqualFold(charset, "utf-8")
}

func plystraDecodeRequest(writer http.ResponseWriter, request *http.Request) (contract.Request, int, string) {
	var result contract.Request
	if request.Body == nil {
		return result, http.StatusBadRequest, "invalid_request"
	}
	body, err := io.ReadAll(http.MaxBytesReader(writer, request.Body, MaximumRequestBytes))
	if err != nil {
		var tooLarge *http.MaxBytesError
		if errors.As(err, &tooLarge) {
			return result, http.StatusRequestEntityTooLarge, "payload_too_large"
		}
		return result, http.StatusBadRequest, "invalid_request"
	}
	if !plystraValidRequestObject(body) || json.Unmarshal(body, &result) != nil || !plystraValidRequest(result) {
		return contract.Request{}, http.StatusBadRequest, "invalid_request"
	}
	return result, 0, ""
}

func plystraValidRequestObject(body []byte) bool {
	decoder := json.NewDecoder(bytes.NewReader(body))
	opening, err := decoder.Token()
	if err != nil || opening != json.Delim('{') {
		return false
	}
	var hasHTML bool
	var hasPriority bool
	var hasSubject bool
	var hasText bool
	var hasTo bool
	for decoder.More() {
		token, err := decoder.Token()
		name, ok := token.(string)
		if err != nil || !ok {
			return false
		}
		var value json.RawMessage
		if decoder.Decode(&value) != nil {
			return false
		}
		switch name {
		case "html":
			if hasHTML {
				return false
			}
			hasHTML = true
		case "priority":
			if hasPriority {
				return false
			}
			hasPriority = true
		case "subject":
			if hasSubject || bytes.Equal(bytes.TrimSpace(value), []byte("null")) {
				return false
			}
			hasSubject = true
		case "text":
			if hasText {
				return false
			}
			hasText = true
		case "to":
			if hasTo || bytes.Equal(bytes.TrimSpace(value), []byte("null")) {
				return false
			}
			hasTo = true
		default:
			return false
		}
	}
	closing, err := decoder.Token()
	if err != nil || closing != json.Delim('}') {
		return false
	}
	var trailing any
	if !errors.Is(decoder.Decode(&trailing), io.EOF) {
		return false
	}
	if !hasSubject {
		return false
	}
	if !hasTo {
		return false
	}
	return true
}

func plystraValidRequest(request contract.Request) bool {
	if request.Priority != nil {
		switch string(*request.Priority) {
		case "normal", "urgent":
		default:
			return false
		}
	}
	return true
}

func plystraValidResponse(response contract.Response) bool {
	switch string(response.Status) {
	case "queued", "sent":
	default:
		return false
	}
	return true
}

func plystraCreateRoot(root RootContext, request *http.Request) (ctx context.Context, err error) {
	defer func() {
		if recover() != nil {
			ctx = nil
			err = ErrInvalidHandler
		}
	}()
	return root(request)
}

func plystraInvoke(ctx context.Context, target applicationinvocation.Handle, request contract.Request) (response contract.Response, err error) {
	defer func() {
		if recover() != nil {
			response = contract.Response{}
			err = ErrInvalidHandler
		}
	}()
	return target.Invoke(ctx, request)
}

func plystraWriteInvocationError(writer http.ResponseWriter, err error) {
	defer func() {
		if recover() != nil {
			plystraWriteError(writer, http.StatusInternalServerError, "internal", "")
		}
	}()
	if semantic, ok := plystraSemanticError(err); ok {
		plystraWriteError(writer, http.StatusUnprocessableEntity, "capability_error", semantic)
		return
	}
	var classified *kernelinvocation.Error
	if errors.As(err, &classified) && classified.Code().Valid() && kernelinvocation.ValidDetailCode(classified.DetailCode()) {
		plystraWriteError(writer, plystraStatus(classified.Code()), classified.Code().String(), classified.DetailCode())
		return
	}
	switch {
	case errors.Is(err, context.DeadlineExceeded):
		plystraWriteError(writer, http.StatusServiceUnavailable, kernelinvocation.ErrorTimeout.String(), "")
	case errors.Is(err, context.Canceled):
		plystraWriteError(writer, 499, kernelinvocation.ErrorCancelled.String(), "")
	default:
		plystraWriteError(writer, http.StatusInternalServerError, "internal", "")
	}
}

func plystraStatus(code kernelinvocation.ErrorCode) int {
	switch code {
	case kernelinvocation.ErrorInvalidArgument:
		return http.StatusBadRequest
	case kernelinvocation.ErrorUnauthenticated:
		return http.StatusUnauthorized
	case kernelinvocation.ErrorDenied:
		return http.StatusForbidden
	case kernelinvocation.ErrorNotFound:
		return http.StatusNotFound
	case kernelinvocation.ErrorConflict, kernelinvocation.ErrorVersionIncompatible:
		return http.StatusConflict
	case kernelinvocation.ErrorTimeout, kernelinvocation.ErrorUnavailable, kernelinvocation.ErrorResultUnknown:
		return http.StatusServiceUnavailable
	case kernelinvocation.ErrorCancelled:
		return 499
	default:
		return http.StatusInternalServerError
	}
}

type plystraSemanticErrorCoder interface {
	error
	SemanticErrorCode() string
}

func plystraSemanticError(err error) (string, bool) {
	var semantic plystraSemanticErrorCoder
	if !errors.As(err, &semantic) {
		return "", false
	}
	code := semantic.SemanticErrorCode()
	switch code {
	case "authentication_failed", "invalid_recipient", "temporarily_unavailable":
		return code, true
	default:
		return "", false
	}
}

type plystraErrorEnvelope struct {
	Error plystraErrorBody `json:"error"`
}

type plystraErrorBody struct {
	Code       string `json:"code"`
	DetailCode string `json:"detail_code,omitempty"`
}

func plystraWriteError(writer http.ResponseWriter, status int, code, detailCode string) {
	payload, err := json.Marshal(plystraErrorEnvelope{Error: plystraErrorBody{Code: code, DetailCode: detailCode}})
	if err != nil {
		payload = []byte(`{"error":{"code":"internal"}}`)
		status = http.StatusInternalServerError
	}
	plystraWriteJSON(writer, status, payload)
}

func plystraWriteJSON(writer http.ResponseWriter, status int, payload []byte) {
	writer.Header().Set("Content-Type", "application/json")
	writer.Header().Set("Cache-Control", "no-store")
	writer.Header().Set("X-Content-Type-Options", "nosniff")
	writer.WriteHeader(status)
	_, _ = writer.Write(payload)
}
