// Code generated by Plystra CLI. DO NOT EDIT.

package emailsendv1

import (
	"context"

	contract "example.com/acme/project/generated/go/contracts/email/send/v1"
	"github.com/plystra/kernel/invocation"
)

// Client invokes one exact capability through the Kernel governance boundary.
type Client struct {
	handle invocation.Handle[contract.Request, contract.Response]
}

// New binds a generated client to one caller-scoped capability handle.
func New(handle invocation.Handle[contract.Request, contract.Response]) Client {
	return Client{handle: handle}
}

// Available reports whether assembly selected a provider for this client.
func Available(c Client) bool {
	return c.handle.Available()
}

// Send invokes email.send/v1 through governed Kernel dispatch.
func (c Client) Send(ctx context.Context, request contract.Request) (contract.Response, error) {
	return c.handle.Invoke(ctx, request)
}
