// Code generated by Plystra CLI. DO NOT EDIT.

package maildeliverv1

import (
	"context"

	canonicalclient "example.com/acme/project/generated/go/clients/email/send/v1"
	contract "example.com/acme/project/generated/go/contracts/email/send/v1"
)

// Client invokes application-local Alias mail.deliver/v1 through canonical target email.send/v1.
type Client struct {
	target canonicalclient.Client
}

// New binds Alias mail.deliver/v1 to the canonical generated client for email.send/v1.
func New(target canonicalclient.Client) Client {
	return Client{target: target}
}

// Available reports whether assembly selected the canonical target provider.
func Available(c Client) bool {
	return canonicalclient.Available(c.target)
}

// Deliver invokes Alias mail.deliver/v1 through canonical target email.send/v1's generated application path.
//
// Deprecated: Use email.send/v1 instead.
// Scheduled removal in v2.
func (c Client) Deliver(ctx context.Context, request contract.Request) (contract.Response, error) {
	return c.target.Send(ctx, request)
}
