// Code generated by Plystra CLI. DO NOT EDIT.

import {
  createRuntime,
  invokeInterface,
  type ClientOptions,
  type ErrorContract,
  type InterfaceCodec,
  type RequestOptions,
  type Runtime,
} from "../../../runtime.js";
import { resolveMessage, resolveUnaryMethod } from "../../../descriptors.js";

export interface RecordsEchoV1Detail {
  readonly "code": string;
  readonly "amount"?: bigint;
  readonly "children"?: ReadonlyArray<RecordsEchoV1Detail>;
}

export interface RecordsEchoV1Envelope {
  readonly "active": boolean;
  readonly "count_32"?: number;
  readonly "count_64"?: bigint;
  readonly "unsigned_32"?: number;
  readonly "unsigned_64"?: bigint;
  readonly "ratio_32"?: number;
  readonly "ratio_64"?: number;
  readonly "name": string;
  readonly "payload": Uint8Array;
  readonly "tags"?: ReadonlyArray<string>;
  readonly "scores"?: Readonly<Record<string, bigint>>;
  readonly "detail": RecordsEchoV1Detail;
  readonly "items"?: ReadonlyArray<RecordsEchoV1Detail>;
  readonly "lookup"?: Readonly<Record<string, RecordsEchoV1Detail>>;
  readonly "at": string;
  readonly "delay": string;
  readonly "payloads"?: ReadonlyArray<Uint8Array>;
  readonly "identifiers"?: Readonly<Record<string, bigint>>;
  readonly "DefaultName"?: string;
}

export interface RecordsEchoV1Request {
  readonly "value": RecordsEchoV1Envelope;
}

export interface RecordsEchoV1Response {
  readonly "value": RecordsEchoV1Envelope;
}

export type ErrorCode = "record_rejected";

export type Operation = (
  request: RecordsEchoV1Request,
  options?: RequestOptions,
) => Promise<RecordsEchoV1Response>;
export const interfaceID = "records.echo/v1";
export const contractDigest = "sha256:9edac981e07d60dff81938719b99315face2aa89e8111426f76030fc1de6fe4d";
const method = resolveUnaryMethod(
  "plystra.generated.records.echo.v1.RecordsEchoV1Service",
  "Invoke",
  "plystra.generated.records.echo.v1.RecordsEchoV1Request",
  "plystra.generated.records.echo.v1.RecordsEchoV1Response",
);
const errorDetailDescriptor = resolveMessage("plystra.generated.transport.v1.PlystraErrorDetail");
const semanticErrorCodes = Object.freeze([
  "record_rejected",
]);

const interfaceCodec: InterfaceCodec = {
  request: "Request",
  response: "Response",
  messages: {
    "Detail": {
      fields: [
        {
          canonicalName: "code",
          protobufJSONName: "code",
          required: true,
          value: { kind: "string" },
        },
        {
          canonicalName: "amount",
          protobufJSONName: "amount",
          required: false,
          value: { kind: "int64" },
        },
        {
          canonicalName: "children",
          protobufJSONName: "children",
          required: false,
          value: { kind: "repeated", element: { kind: "message", message: "Detail" } },
        },
      ],
    },
    "Envelope": {
      fields: [
        {
          canonicalName: "active",
          protobufJSONName: "active",
          required: true,
          value: { kind: "boolean" },
        },
        {
          canonicalName: "count_32",
          protobufJSONName: "count_32",
          required: false,
          value: { kind: "int32" },
        },
        {
          canonicalName: "count_64",
          protobufJSONName: "count_64",
          required: false,
          value: { kind: "int64" },
        },
        {
          canonicalName: "unsigned_32",
          protobufJSONName: "unsigned_32",
          required: false,
          value: { kind: "uint32" },
        },
        {
          canonicalName: "unsigned_64",
          protobufJSONName: "unsigned_64",
          required: false,
          value: { kind: "uint64" },
        },
        {
          canonicalName: "ratio_32",
          protobufJSONName: "ratio_32",
          required: false,
          value: { kind: "float32" },
        },
        {
          canonicalName: "ratio_64",
          protobufJSONName: "ratio_64",
          required: false,
          value: { kind: "float64" },
        },
        {
          canonicalName: "name",
          protobufJSONName: "name",
          required: true,
          value: { kind: "string" },
        },
        {
          canonicalName: "payload",
          protobufJSONName: "payload",
          required: true,
          value: { kind: "bytes" },
        },
        {
          canonicalName: "tags",
          protobufJSONName: "tags",
          required: false,
          value: { kind: "repeated", element: { kind: "string" } },
        },
        {
          canonicalName: "scores",
          protobufJSONName: "scores",
          required: false,
          value: { kind: "map", key: "string", value: { kind: "int64" } },
        },
        {
          canonicalName: "detail",
          protobufJSONName: "detail",
          required: true,
          value: { kind: "message", message: "Detail" },
        },
        {
          canonicalName: "items",
          protobufJSONName: "items",
          required: false,
          value: { kind: "repeated", element: { kind: "message", message: "Detail" } },
        },
        {
          canonicalName: "lookup",
          protobufJSONName: "lookup",
          required: false,
          value: { kind: "map", key: "string", value: { kind: "message", message: "Detail" } },
        },
        {
          canonicalName: "at",
          protobufJSONName: "at",
          required: true,
          value: { kind: "timestamp" },
        },
        {
          canonicalName: "delay",
          protobufJSONName: "delay",
          required: true,
          value: { kind: "duration" },
        },
        {
          canonicalName: "payloads",
          protobufJSONName: "payloads",
          required: false,
          value: { kind: "repeated", element: { kind: "bytes" } },
        },
        {
          canonicalName: "identifiers",
          protobufJSONName: "identifiers",
          required: false,
          value: { kind: "map", key: "int64", value: { kind: "uint64" } },
        },
        {
          canonicalName: "DefaultName",
          protobufJSONName: "DefaultName",
          required: false,
          value: { kind: "string" },
        },
      ],
    },
    "Request": {
      fields: [
        {
          canonicalName: "value",
          protobufJSONName: "value",
          required: true,
          value: { kind: "message", message: "Envelope" },
        },
      ],
    },
    "Response": {
      fields: [
        {
          canonicalName: "value",
          protobufJSONName: "value",
          required: true,
          value: { kind: "message", message: "Envelope" },
        },
      ],
    },
  },
};

/** @internal */
export function bindOperation(runtime: Runtime): Operation {
  const errorContract: ErrorContract = {
    requestedCapabilityID: interfaceID,
    canonicalCapabilityID: interfaceID,
    semanticErrorCodes,
    detailDescriptor: errorDetailDescriptor,
  };
  return async (request, options = {}) =>
    (await invokeInterface(runtime, method, interfaceCodec, errorContract, request, options)) as RecordsEchoV1Response;
}

export function createOperation(options: ClientOptions): Operation {
  return bindOperation(createRuntime(options));
}
