// Package applicationentrygen renders the generated application process entrypoint.
package applicationentrygen

import (
	"errors"
	"fmt"
	"go/format"
	"path"
	"strconv"
	"strings"
	"time"

	"github.com/plystra/cli/internal/modulepath"
)

const (
	// Path is the application-relative generated process entrypoint path.
	Path = "generated/go/application/main_gen.go"
	// DefaultShutdownTimeout bounds generated application shutdown until the
	// runtime configuration model gains an explicit shutdown setting.
	DefaultShutdownTimeout = 30 * time.Second
)

var (
	// ErrRender reports invalid entrypoint inputs or generated source.
	ErrRender = errors.New("render application entrypoint")
	// ErrInvalidOptions reports an invalid module path or shutdown bound.
	ErrInvalidOptions = errors.New("invalid application entrypoint options")
)

// Options contains the stable build inputs needed by the generated process.
type Options struct {
	ModulePath      string
	ShutdownTimeout time.Duration
}

// Render emits the signal-driven process boundary, its internal lifecycle
// smoke mode, and transparent runtime-selector forwarding to bootstrap.
func Render(options Options) ([]byte, error) {
	if err := modulepath.CheckProject(options.ModulePath); err != nil {
		return nil, fmt.Errorf("%w: %w: invalid Go Module path %q", ErrRender, ErrInvalidOptions, options.ModulePath)
	}
	if options.ShutdownTimeout <= 0 {
		return nil, fmt.Errorf("%w: %w: shutdown timeout must be positive", ErrRender, ErrInvalidOptions)
	}

	bootstrapPath := path.Join(options.ModulePath, "generated/go/bootstrap")
	var source strings.Builder
	fmt.Fprintln(&source, "// Code generated by Plystra CLI. DO NOT EDIT.")
	fmt.Fprintln(&source)
	fmt.Fprintln(&source, "package main")
	fmt.Fprintln(&source)
	fmt.Fprintln(&source, "import (")
	fmt.Fprintln(&source, "\t\"context\"")
	fmt.Fprintln(&source, "\t\"errors\"")
	fmt.Fprintln(&source, "\t\"fmt\"")
	fmt.Fprintln(&source, "\t\"os\"")
	fmt.Fprintln(&source, "\t\"os/signal\"")
	fmt.Fprintln(&source, "\t\"syscall\"")
	fmt.Fprintln(&source, "\t\"time\"")
	fmt.Fprintln(&source)
	fmt.Fprintf(&source, "\tapplicationbootstrap %s\n", strconv.Quote(bootstrapPath))
	fmt.Fprintln(&source, "\tkernelintrinsic \"github.com/plystra/kernel/intrinsic\"")
	fmt.Fprintln(&source, ")")
	fmt.Fprintln(&source)
	fmt.Fprintf(&source, "const defaultShutdownTimeout = time.Duration(%d)\n", options.ShutdownTimeout)
	fmt.Fprintln(&source)
	fmt.Fprintln(&source, "var (")
	fmt.Fprintln(&source, "\t// ErrRun reports a safe generated-process lifecycle failure.")
	fmt.Fprintln(&source, "\tErrRun = errors.New(\"run generated application\")")
	fmt.Fprintln(&source, "\t// ErrArguments reports an unsupported generated-process argument.")
	fmt.Fprintln(&source, "\tErrArguments = errors.New(\"invalid generated application arguments\")")
	fmt.Fprintln(&source, "\t// ErrHealth reports a failed intrinsic lifecycle smoke check.")
	fmt.Fprintln(&source, "\tErrHealth = errors.New(\"intrinsic Kernel health check failed\")")
	fmt.Fprintln(&source, ")")
	fmt.Fprintln(&source)
	fmt.Fprintln(&source, "func main() {")
	fmt.Fprintln(&source, "\tctx, cancel := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)")
	fmt.Fprintln(&source, "\tdefer cancel()")
	fmt.Fprintln(&source, "\tif err := run(ctx, os.Args[1:], os.Environ()); err != nil {")
	fmt.Fprintln(&source, "\t\t_, _ = fmt.Fprintln(os.Stderr, err)")
	fmt.Fprintln(&source, "\t\tos.Exit(1)")
	fmt.Fprintln(&source, "\t}")
	fmt.Fprintln(&source, "}")
	fmt.Fprintln(&source)
	fmt.Fprintln(&source, "func run(ctx context.Context, arguments, environment []string) (result error) {")
	fmt.Fprintln(&source, "\tif ctx == nil {")
	fmt.Fprintln(&source, "\t\treturn fmt.Errorf(\"%w: context is required\", ErrRun)")
	fmt.Fprintln(&source, "\t}")
	fmt.Fprintln(&source, "\tsmoke, selectorArguments, err := processArguments(arguments)")
	fmt.Fprintln(&source, "\tif err != nil {")
	fmt.Fprintln(&source, "\t\treturn err")
	fmt.Fprintln(&source, "\t}")
	fmt.Fprintln(&source, "\tapplication, err := applicationbootstrap.New(ctx, applicationbootstrap.RuntimeOptions{")
	fmt.Fprintln(&source, "\t\tArguments:   selectorArguments,")
	fmt.Fprintln(&source, "\t\tEnvironment: environment,")
	fmt.Fprintln(&source, "\t})")
	fmt.Fprintln(&source, "\tif err != nil {")
	fmt.Fprintln(&source, "\t\treturn fmt.Errorf(\"%w: construct: %w\", ErrRun, err)")
	fmt.Fprintln(&source, "\t}")
	fmt.Fprintln(&source, "\tif err := application.Start(ctx); err != nil {")
	fmt.Fprintln(&source, "\t\treturn fmt.Errorf(\"%w: start: %w\", ErrRun, err)")
	fmt.Fprintln(&source, "\t}")
	fmt.Fprintln(&source, "\tdefer func() {")
	fmt.Fprintln(&source, "\t\tstopContext, cancel := context.WithTimeout(context.Background(), defaultShutdownTimeout)")
	fmt.Fprintln(&source, "\t\tdefer cancel()")
	fmt.Fprintln(&source, "\t\tif err := application.Stop(stopContext); err != nil {")
	fmt.Fprintln(&source, "\t\t\tstopError := fmt.Errorf(\"%w: stop: %w\", ErrRun, err)")
	fmt.Fprintln(&source, "\t\t\tif result == nil {")
	fmt.Fprintln(&source, "\t\t\t\tresult = stopError")
	fmt.Fprintln(&source, "\t\t\t} else {")
	fmt.Fprintln(&source, "\t\t\t\tresult = errors.Join(result, stopError)")
	fmt.Fprintln(&source, "\t\t\t}")
	fmt.Fprintln(&source, "\t\t}")
	fmt.Fprintln(&source, "\t}()")
	fmt.Fprintln(&source)
	fmt.Fprintln(&source, "\tif smoke {")
	fmt.Fprintln(&source, "\t\thealth, err := application.Invocations().IntrinsicHealth(ctx)")
	fmt.Fprintln(&source, "\t\tif err != nil {")
	source.WriteString("\t\t\treturn fmt.Errorf(\"%w: %w: invoke: %v\", ErrRun, ErrHealth, err)\n")
	fmt.Fprintln(&source, "\t\t}")
	fmt.Fprintln(&source, "\t\tif health.Status != kernelintrinsic.HealthStatusHealthy {")
	fmt.Fprintln(&source, "\t\t\treturn fmt.Errorf(\"%w: %w: unexpected status\", ErrRun, ErrHealth)")
	fmt.Fprintln(&source, "\t\t}")
	fmt.Fprintln(&source, "\t\treturn nil")
	fmt.Fprintln(&source, "\t}")
	fmt.Fprintln(&source)
	fmt.Fprintln(&source, "\t<-ctx.Done()")
	fmt.Fprintln(&source, "\treturn nil")
	fmt.Fprintln(&source, "}")
	fmt.Fprintln(&source)
	fmt.Fprintln(&source, "func processArguments(arguments []string) (bool, []string, error) {")
	fmt.Fprintln(&source, "\tsmoke := false")
	fmt.Fprintln(&source, "\tselectors := make([]string, 0, len(arguments))")
	fmt.Fprintln(&source, "\tfor _, argument := range arguments {")
	fmt.Fprintln(&source, "\t\tif argument != \"--smoke\" {")
	fmt.Fprintln(&source, "\t\t\tselectors = append(selectors, argument)")
	fmt.Fprintln(&source, "\t\t\tcontinue")
	fmt.Fprintln(&source, "\t\t}")
	fmt.Fprintln(&source, "\t\tif smoke {")
	fmt.Fprintln(&source, "\t\t\treturn false, nil, fmt.Errorf(\"%w: --smoke may be specified once\", ErrArguments)")
	fmt.Fprintln(&source, "\t\t}")
	fmt.Fprintln(&source, "\t\tsmoke = true")
	fmt.Fprintln(&source, "\t}")
	fmt.Fprintln(&source, "\treturn smoke, selectors, nil")
	fmt.Fprintln(&source, "}")

	formatted, err := format.Source([]byte(source.String()))
	if err != nil {
		return nil, fmt.Errorf("%w: format generated source: %v", ErrRender, err)
	}
	return append([]byte(nil), formatted...), nil
}
