// Package interfaceproxygen renders typed governed proxies for authored Interfaces.
package interfaceproxygen

import (
	"errors"
	"fmt"
	"go/ast"
	"go/format"
	"go/token"
	"path"
	"slices"
	"strconv"
	"strings"

	"github.com/plystra/cli/internal/interfaceid"
	"golang.org/x/mod/module"
)

const kernelInvocationPackage = "github.com/plystra/kernel/invocation"

var (
	// ErrRender reports invalid proxy input or generated Go source.
	ErrRender = errors.New("render Interface proxies")
	// ErrInvalidInput reports incomplete or unsafe canonical Interface identity.
	ErrInvalidInput = errors.New("invalid Interface proxy input")
	// ErrDuplicateInterface reports more than one proxy input for an exact Interface.
	ErrDuplicateInterface = errors.New("duplicate Interface proxy")
)

// Input is the complete authored contract shape needed by one typed proxy.
type Input struct {
	InterfaceID  interfaceid.Identifier
	PackagePath  string
	MethodName   string
	RequestName  string
	ResponseName string
}

// File is one immutable generated proxy source file.
type File struct {
	interfaceID interfaceid.Identifier
	path        string
	data        []byte
}

// InterfaceID returns the exact authored Interface represented by this proxy.
func (f File) InterfaceID() interfaceid.Identifier { return f.interfaceID }

// Path returns the Project-relative generated source path.
func (f File) Path() string { return f.path }

// Data returns defensive gofmt-formatted generated source.
func (f File) Data() []byte { return append([]byte(nil), f.data...) }

// Render validates, canonicalizes, and renders one package per Interface in
// exact Interface-ID order. Generated methods preserve the authored signature
// and delegate to Kernel's governed typed invocation handle.
func Render(inputs []Input) ([]File, error) {
	normalized := append([]Input(nil), inputs...)
	for index, input := range normalized {
		if err := validateInput(input); err != nil {
			return nil, fmt.Errorf("%w: input %d: %w", ErrRender, index, err)
		}
	}
	sortInputs(normalized)
	for index := 1; index < len(normalized); index++ {
		if normalized[index-1].InterfaceID == normalized[index].InterfaceID {
			return nil, fmt.Errorf("%w: %w: %s", ErrRender, ErrDuplicateInterface, normalized[index].InterfaceID)
		}
	}
	files := make([]File, len(normalized))
	for index, input := range normalized {
		data, err := render(input)
		if err != nil {
			return nil, fmt.Errorf("%w: Interface %s: %v", ErrRender, input.InterfaceID, err)
		}
		files[index] = File{
			interfaceID: input.InterfaceID,
			path:        outputPath(input.InterfaceID),
			data:        data,
		}
	}
	return files, nil
}

func validateInput(input Input) error {
	if input.InterfaceID.String() == "" {
		return fmt.Errorf("%w: Interface ID is required", ErrInvalidInput)
	}
	if module.CheckImportPath(input.PackagePath) != nil || input.PackagePath == kernelInvocationPackage {
		return fmt.Errorf("%w: Interface package %q is invalid", ErrInvalidInput, input.PackagePath)
	}
	for _, candidate := range []struct {
		name  string
		value string
	}{
		{name: "method", value: input.MethodName},
		{name: "request", value: input.RequestName},
		{name: "response", value: input.ResponseName},
	} {
		name, value := candidate.name, candidate.value
		if !token.IsIdentifier(value) || !ast.IsExported(value) {
			return fmt.Errorf("%w: %s name %q must be an exported Go identifier", ErrInvalidInput, name, value)
		}
	}
	return nil
}

func sortInputs(inputs []Input) {
	slices.SortFunc(inputs, func(left, right Input) int {
		return strings.Compare(left.InterfaceID.String(), right.InterfaceID.String())
	})
}

func outputPath(identifier interfaceid.Identifier) string {
	segments := strings.Split(identifier.Name(), ".")
	segments = append([]string{"generated", "go", "proxies"}, segments...)
	segments = append(segments, "v"+strconv.FormatUint(identifier.Major(), 10), "proxy_gen.go")
	return path.Join(segments...)
}

func render(input Input) ([]byte, error) {
	var source strings.Builder
	fmt.Fprintln(&source, "// Code generated by Plystra CLI. DO NOT EDIT.")
	fmt.Fprintln(&source)
	fmt.Fprintln(&source, "package proxy")
	fmt.Fprintln(&source)
	fmt.Fprintln(&source, "import (")
	fmt.Fprintln(&source, "\t\"context\"")
	fmt.Fprintln(&source)
	fmt.Fprintf(&source, "\tcontract %s\n", strconv.Quote(input.PackagePath))
	fmt.Fprintf(&source, "\tkernelinvocation %s\n", strconv.Quote(kernelInvocationPackage))
	fmt.Fprintln(&source, ")")
	fmt.Fprintln(&source)
	fmt.Fprintf(&source, "// InterfaceID is the exact authored Interface served by this proxy.\nconst InterfaceID = %s\n", strconv.Quote(input.InterfaceID.String()))
	fmt.Fprintln(&source)
	fmt.Fprintln(&source, "// Proxy preserves the authored Interface while routing calls through Kernel governance.")
	fmt.Fprintln(&source, "type Proxy struct {")
	fmt.Fprintf(&source, "\thandle kernelinvocation.Handle[contract.%s, contract.%s]\n", input.RequestName, input.ResponseName)
	fmt.Fprintln(&source, "}")
	fmt.Fprintln(&source)
	fmt.Fprintln(&source, "var _ contract.Interface = Proxy{}")
	fmt.Fprintln(&source)
	fmt.Fprintln(&source, "// New binds one already-resolved governed handle to the authored Interface.")
	fmt.Fprintf(&source, "func New(handle kernelinvocation.Handle[contract.%s, contract.%s]) Proxy {\n", input.RequestName, input.ResponseName)
	fmt.Fprintln(&source, "\treturn Proxy{handle: handle}")
	fmt.Fprintln(&source, "}")
	fmt.Fprintln(&source)
	fmt.Fprintf(&source, "// %s invokes %s through the frozen Kernel binding.\n", input.MethodName, input.InterfaceID)
	fmt.Fprintf(&source, "func (proxy Proxy) %s(ctx context.Context, request contract.%s) (contract.%s, error) {\n", input.MethodName, input.RequestName, input.ResponseName)
	fmt.Fprintln(&source, "\treturn proxy.handle.Invoke(ctx, request)")
	fmt.Fprintln(&source, "}")

	formatted, err := format.Source([]byte(source.String()))
	if err != nil {
		return nil, fmt.Errorf("format generated source: %w", err)
	}
	return formatted, nil
}
