package assemblygen

import (
	"crypto/sha256"
	"encoding/json"
	"errors"
	"fmt"
	"go/format"
	"path"
	"sort"
	"strconv"
	"strings"
	"time"

	"github.com/plystra/cli/internal/capabilityid"
	"github.com/plystra/cli/internal/capabilitymeta"
	"github.com/plystra/cli/internal/goname"
	kernelcatalog "github.com/plystra/kernel/capability/catalog"
	kernelintrinsic "github.com/plystra/kernel/intrinsic"
	kernelinvocation "github.com/plystra/kernel/invocation"
	"golang.org/x/mod/module"
)

// InvocationsPath is the application-relative canonical runtime source path.
const InvocationsPath = "generated/go/assembly/invocations_gen.go"

var (
	// ErrRenderInvocations reports invalid resolved runtime input or a generated
	// canonical invocation source formatting failure.
	ErrRenderInvocations = errors.New("render canonical invocation assembly")
	// ErrInvalidInvocation reports incomplete or contradictory selected
	// Capability runtime input.
	ErrInvalidInvocation = errors.New("invalid canonical invocation input")
	// ErrDuplicateInvocation reports repeated Capability IDs or generated
	// accessor names.
	ErrDuplicateInvocation = errors.New("duplicate canonical invocation input")
	// ErrInvocationDependency reports an absent, repeated, self-referential, or
	// cyclic generated application invocation dependency.
	ErrInvocationDependency = errors.New("invalid canonical invocation dependency")
)

// InvocationInput binds one exact required canonical contract to either its
// selected ordinary provider or the Kernel intrinsic implementation, plus its
// ordered generated application dependencies. ContractJSON is the complete
// normalized contract and contains no runtime values.
type InvocationInput struct {
	ContractJSON    []byte
	Intrinsic       bool
	ProviderID      string
	SelectionReason kernelinvocation.SelectionReason
	Dependencies    []string
}

// InvocationOptions contains the complete canonical runtime plan and selected
// Kernel module provenance.
// ApplicationBuildIdentity is deterministic non-secret build provenance, not
// a dependency lock or runtime application identity.
type InvocationOptions struct {
	ModulePath               string
	ApplicationBuildIdentity string
	KernelModuleVersion      string
	KernelBuildIdentity      string
	DefaultTimeout           time.Duration
	Providers                []ProviderInput
	Invocations              []InvocationInput
}

type runtimeContract struct {
	ID       string                  `json:"id"`
	Request  map[string]runtimeField `json:"request"`
	Response map[string]runtimeField `json:"response"`
	Errors   []string                `json:"errors"`
}

type runtimeField struct {
	Required bool              `json:"required,omitempty"`
	Enum     []json.RawMessage `json:"enum,omitempty"`
}

type indexedProvider struct {
	plannedProvider
	index int
}

type plannedInvocation struct {
	id              capabilityid.Identifier
	contract        runtimeContract
	digest          [sha256.Size]byte
	intrinsic       bool
	provider        indexedProvider
	selectionReason kernelinvocation.SelectionReason
	dependencies    []capabilityid.Identifier
	accessor        string
	index           int
}

// RenderInvocations emits one immutable canonical catalog, one shared Kernel
// dispatcher, typed ordinary-provider endpoint adapters, raw handles, and
// generated application invocation handles for every required Capability.
func RenderInvocations(options InvocationOptions) ([]byte, error) {
	invocations, order, err := planInvocations(options)
	if err != nil {
		return nil, fmt.Errorf("%w: %w", ErrRenderInvocations, err)
	}

	var source strings.Builder
	fmt.Fprintln(&source, "// Code generated by Plystra CLI. DO NOT EDIT.")
	fmt.Fprintln(&source)
	fmt.Fprintln(&source, "package assembly")
	fmt.Fprintln(&source)
	fmt.Fprintln(&source, "import (")
	ordinaryCount := ordinaryInvocationCount(invocations)
	intrinsicCount := len(kernelcatalog.Definitions())
	if ordinaryCount != 0 {
		fmt.Fprintln(&source, "\t\"context\"")
	}
	fmt.Fprintln(&source, "\t\"errors\"")
	fmt.Fprintln(&source, "\t\"fmt\"")
	fmt.Fprintln(&source, "\t\"log/slog\"")
	fmt.Fprintln(&source, "\t\"time\"")
	fmt.Fprintln(&source)
	for _, invocation := range invocations {
		fmt.Fprintf(&source, "\tapplicationinvocation%d %s\n", invocation.index, strconv.Quote(applicationInvocationPath(options.ModulePath, invocation.id)))
		if !invocation.intrinsic {
			fmt.Fprintf(&source, "\tcontract%d %s\n", invocation.index, strconv.Quote(applicationContractPath(options.ModulePath, invocation.id)))
		}
		if !invocation.intrinsic && invocation.provider.ModulePath != options.ModulePath {
			fmt.Fprintf(&source, "\tprovidercontract%d %s\n", invocation.index, strconv.Quote(applicationContractPath(invocation.provider.ModulePath, invocation.id)))
		}
	}
	for _, dependencyIndex := range dependencyImportIndexes(invocations) {
		dependency := invocations[dependencyIndex]
		fmt.Fprintf(&source, "\tapplicationclient%d %s\n", dependency.index, strconv.Quote(applicationClientPath(options.ModulePath, dependency.id)))
	}
	if ordinaryCount != 0 {
		fmt.Fprintln(&source, "\tkernelcapability \"github.com/plystra/kernel/capability\"")
	}
	fmt.Fprintln(&source, "\tkernelintrinsic \"github.com/plystra/kernel/intrinsic\"")
	fmt.Fprintln(&source, "\tkernelinvocation \"github.com/plystra/kernel/invocation\"")
	if ordinaryCount != 0 {
		fmt.Fprintln(&source, "\tkernelplugin \"github.com/plystra/kernel/plugin\"")
	}
	fmt.Fprintln(&source, ")")
	fmt.Fprintln(&source)
	fmt.Fprintf(&source, "const defaultInvocationTimeout = time.Duration(%d)\n", options.DefaultTimeout)
	fmt.Fprintln(&source)
	fmt.Fprintln(&source, "// ErrInvocationAssembly reports a safe canonical runtime construction failure.")
	fmt.Fprintln(&source, "var ErrInvocationAssembly = errors.New(\"assemble canonical invocation runtime\")")
	if len(invocations) != 0 {
		fmt.Fprintln(&source)
		fmt.Fprintln(&source, "var (")
		for _, invocation := range invocations {
			if invocation.intrinsic {
				fmt.Fprintf(&source, "\tplystraContract%d = %s\n", invocation.index, intrinsicContractExpression(invocation.id))
				continue
			}
			fmt.Fprintf(
				&source,
				"\tplystraContract%d = kernelcapability.MustParseContractWithSemanticErrors[contract%d.Request, contract%d.Response](contract%d.CapabilityID",
				invocation.index,
				invocation.index,
				invocation.index,
				invocation.index,
			)
			for _, code := range invocation.contract.Errors {
				fmt.Fprintf(&source, ", %s", strconv.Quote(code))
			}
			fmt.Fprintln(&source, ")")
		}
		fmt.Fprintln(&source, ")")
	}
	fmt.Fprintln(&source)
	fmt.Fprintln(&source, "// Invocations is one immutable application-owned canonical runtime.")
	fmt.Fprintln(&source, "// Provider values remain private and Alias IDs never enter its catalog.")
	fmt.Fprintln(&source, "type Invocations struct {")
	fmt.Fprintln(&source, "\tcatalog    kernelinvocation.Catalog")
	fmt.Fprintln(&source, "\tdispatcher *kernelinvocation.Dispatcher")
	for _, invocation := range invocations {
		fmt.Fprintf(&source, "\thandle%d applicationinvocation%d.Handle\n", invocation.index, invocation.index)
	}
	fmt.Fprintln(&source, "\tinitialized bool")
	fmt.Fprintln(&source, "}")
	fmt.Fprintln(&source)
	fmt.Fprintln(&source, "// Valid reports whether the complete canonical catalog was published and every typed handle was bound.")
	fmt.Fprintln(&source, "func (i Invocations) Valid() bool {")
	fmt.Fprintf(&source, "\tif !i.initialized || i.dispatcher == nil || !i.dispatcher.Published() || len(i.catalog.Bindings()) != %d {\n", intrinsicCount+ordinaryCount)
	fmt.Fprintln(&source, "\t\treturn false")
	fmt.Fprintln(&source, "\t}")
	if len(invocations) == 0 {
		fmt.Fprintln(&source, "\treturn true")
	} else {
		fmt.Fprint(&source, "\treturn ")
		for index, invocation := range invocations {
			if index != 0 {
				fmt.Fprint(&source, " && ")
			}
			fmt.Fprintf(&source, "applicationinvocation%d.Available(i.handle%d)", invocation.index, invocation.index)
		}
		fmt.Fprintln(&source)
	}
	fmt.Fprintln(&source, "}")
	fmt.Fprintln(&source)
	fmt.Fprintln(&source, "// Catalog returns the immutable canonical registry snapshot.")
	fmt.Fprintln(&source, "func (i Invocations) Catalog() kernelinvocation.Catalog {")
	fmt.Fprintln(&source, "\tif !i.Valid() {")
	fmt.Fprintln(&source, "\t\treturn kernelinvocation.Catalog{}")
	fmt.Fprintln(&source, "\t}")
	fmt.Fprintln(&source, "\treturn i.catalog")
	fmt.Fprintln(&source, "}")
	for _, invocation := range invocations {
		fmt.Fprintln(&source)
		fmt.Fprintf(&source, "// %s returns the bound application invocation path for %s.\n", invocation.accessor, invocation.id)
		fmt.Fprintf(&source, "func (i Invocations) %s() applicationinvocation%d.Handle {\n", invocation.accessor, invocation.index)
		fmt.Fprintln(&source, "\tif !i.Valid() {")
		fmt.Fprintf(&source, "\t\treturn applicationinvocation%d.Handle{}\n", invocation.index)
		fmt.Fprintln(&source, "\t}")
		fmt.Fprintf(&source, "\treturn i.handle%d\n", invocation.index)
		fmt.Fprintln(&source, "}")
	}
	fmt.Fprintln(&source)
	fmt.Fprintln(&source, "// String redacts runtime internals.")
	fmt.Fprintln(&source, "func (Invocations) String() string { return \"<generated-canonical-invocations>\" }")
	fmt.Fprintln(&source)
	fmt.Fprintln(&source, "// GoString prevents Go-syntax formatting from exposing runtime internals.")
	fmt.Fprintln(&source, "func (Invocations) GoString() string { return \"<generated-canonical-invocations>\" }")
	fmt.Fprintln(&source)
	fmt.Fprintln(&source, "// Format redacts runtime internals for every fmt verb.")
	fmt.Fprintln(&source, "func (Invocations) Format(state fmt.State, _ rune) {")
	fmt.Fprintln(&source, "\t_, _ = state.Write([]byte(\"<generated-canonical-invocations>\"))")
	fmt.Fprintln(&source, "}")
	fmt.Fprintln(&source)
	fmt.Fprintln(&source, "// LogValue redacts runtime internals for structured standard-library logging.")
	fmt.Fprintln(&source, "func (Invocations) LogValue() slog.Value {")
	fmt.Fprintln(&source, "\treturn slog.StringValue(\"<generated-canonical-invocations>\")")
	fmt.Fprintln(&source, "}")
	fmt.Fprintln(&source)
	fmt.Fprintln(&source, "// pendingInvocations owns typed application handles while the canonical")
	fmt.Fprintln(&source, "// dispatcher is deliberately unpublished during plugin construction.")
	fmt.Fprintln(&source, "type pendingInvocations struct {")
	fmt.Fprintln(&source, "\tdispatcher *kernelinvocation.Dispatcher")
	for _, invocation := range invocations {
		fmt.Fprintf(&source, "\thandle%d applicationinvocation%d.Handle\n", invocation.index, invocation.index)
	}
	fmt.Fprintln(&source, "\tinitialized bool")
	fmt.Fprintln(&source, "}")
	fmt.Fprintln(&source)
	fmt.Fprintln(&source, "func (p pendingInvocations) valid() bool {")
	fmt.Fprintln(&source, "\tif !p.initialized || p.dispatcher == nil || p.dispatcher.Published() {")
	fmt.Fprintln(&source, "\t\treturn false")
	fmt.Fprintln(&source, "\t}")
	if len(invocations) == 0 {
		fmt.Fprintln(&source, "\treturn true")
	} else {
		fmt.Fprint(&source, "\treturn ")
		for index, invocation := range invocations {
			if index != 0 {
				fmt.Fprint(&source, " && ")
			}
			fmt.Fprintf(&source, "p.handle%d.Available()", invocation.index)
		}
		fmt.Fprintln(&source)
	}
	fmt.Fprintln(&source, "}")
	for _, invocation := range invocations {
		fmt.Fprintln(&source)
		fmt.Fprintf(&source, "func (p pendingInvocations) dependency%s() applicationinvocation%d.Handle {\n", invocation.accessor, invocation.index)
		fmt.Fprintln(&source, "\tif !p.valid() {")
		fmt.Fprintf(&source, "\t\treturn applicationinvocation%d.Handle{}\n", invocation.index)
		fmt.Fprintln(&source, "\t}")
		fmt.Fprintf(&source, "\treturn p.handle%d\n", invocation.index)
		fmt.Fprintln(&source, "}")
	}
	fmt.Fprintln(&source)
	fmt.Fprintln(&source, "func newPendingInvocations() (pendingInvocations, error) {")
	fmt.Fprintln(&source, "\tif err := RequireKernelCompatibility(); err != nil {")
	fmt.Fprintln(&source, "\t\treturn pendingInvocations{}, fmt.Errorf(\"%w: Kernel compatibility: %w\", ErrInvocationAssembly, err)")
	fmt.Fprintln(&source, "\t}")
	fmt.Fprintln(&source, "\tdispatcher, err := kernelinvocation.NewDispatcher(kernelinvocation.DispatcherOptions{DefaultTimeout: defaultInvocationTimeout})")
	fmt.Fprintln(&source, "\tif err != nil {")
	fmt.Fprintln(&source, "\t\treturn pendingInvocations{}, fmt.Errorf(\"%w: canonical dispatcher: %w\", ErrInvocationAssembly, err)")
	fmt.Fprintln(&source, "\t}")
	for _, invocation := range invocations {
		fmt.Fprintf(&source, "\trawHandle%d, err := kernelinvocation.NewHandle(dispatcher, plystraContract%d, true)\n", invocation.index, invocation.index)
		fmt.Fprintln(&source, "\tif err != nil {")
		fmt.Fprintf(&source, "\t\treturn pendingInvocations{}, fmt.Errorf(\"%%w: canonical handle %s: %%w\", ErrInvocationAssembly, err)\n", invocation.id)
		fmt.Fprintln(&source, "\t}")
	}
	for _, invocationIndex := range order {
		invocation := invocations[invocationIndex]
		fmt.Fprintf(&source, "\thandle%d := applicationinvocation%d.New(rawHandle%d", invocation.index, invocation.index, invocation.index)
		for _, dependencyID := range invocation.dependencies {
			dependency := invocations[indexOfInvocation(invocations, dependencyID)]
			fmt.Fprintf(&source, ", applicationclient%d.New(handle%d)", dependency.index, dependency.index)
		}
		fmt.Fprintln(&source, ")")
	}
	fmt.Fprintln(&source, "\treturn pendingInvocations{")
	fmt.Fprintln(&source, "\t\tdispatcher:  dispatcher,")
	for _, invocation := range invocations {
		fmt.Fprintf(&source, "\t\thandle%d:     handle%d,\n", invocation.index, invocation.index)
	}
	fmt.Fprintln(&source, "\t\tinitialized: true,")
	fmt.Fprintln(&source, "\t}, nil")
	fmt.Fprintln(&source, "}")
	fmt.Fprintln(&source)
	fmt.Fprintln(&source, "// publishInvocations adapts selected providers and atomically publishes the")
	fmt.Fprintln(&source, "// complete immutable canonical catalog behind every prepared client.")
	fmt.Fprintln(&source, "func publishInvocations(pending pendingInvocations, providers Providers) (Invocations, error) {")
	fmt.Fprintln(&source, "\tif !pending.valid() {")
	fmt.Fprintln(&source, "\t\treturn Invocations{}, fmt.Errorf(\"%w: pending invocation clients are invalid\", ErrInvocationAssembly)")
	fmt.Fprintln(&source, "\t}")
	fmt.Fprintln(&source, "\tif !providers.Valid() {")
	fmt.Fprintln(&source, "\t\treturn Invocations{}, fmt.Errorf(\"%w: selected providers are invalid\", ErrInvocationAssembly)")
	fmt.Fprintln(&source, "\t}")
	fmt.Fprintln(&source, "\tbindings, err := kernelintrinsic.NewBindings(kernelintrinsic.BindingOptions{")
	fmt.Fprintf(&source, "\t\tModuleVersion: %s,\n", strconv.Quote(options.KernelModuleVersion))
	fmt.Fprintf(&source, "\t\tBuildIdentity: %s,\n", strconv.Quote(options.KernelBuildIdentity))
	fmt.Fprintln(&source, "\t})")
	fmt.Fprintln(&source, "\tif err != nil {")
	fmt.Fprintln(&source, "\t\treturn Invocations{}, fmt.Errorf(\"%w: intrinsic Kernel bindings: %w\", ErrInvocationAssembly, err)")
	fmt.Fprintln(&source, "\t}")
	fmt.Fprintf(&source, "\tif len(bindings) != %d {\n", intrinsicCount)
	source.WriteString("\t\treturn Invocations{}, fmt.Errorf(\"%w: intrinsic Kernel binding count %d is incompatible\", ErrInvocationAssembly, len(bindings))\n")
	fmt.Fprintln(&source, "\t}")
	for _, provider := range usedProviders(invocations) {
		fmt.Fprintf(
			&source,
			"\tproviderBuild%d, err := kernelinvocation.NewModuleBuild(%s, %s, %s)\n",
			provider.index,
			strconv.Quote(provider.ModulePath),
			strconv.Quote(provider.ModuleVersion),
			strconv.Quote(options.ApplicationBuildIdentity),
		)
		fmt.Fprintln(&source, "\tif err != nil {")
		fmt.Fprintf(&source, "\t\treturn Invocations{}, fmt.Errorf(\"%%w: plugin %%q build provenance: %%w\", ErrInvocationAssembly, %s, err)\n", strconv.Quote(provider.PluginID))
		fmt.Fprintln(&source, "\t}")
		fmt.Fprintf(&source, "\tproviderID%d, err := kernelplugin.ParseID(%s)\n", provider.index, strconv.Quote(provider.PluginID))
		fmt.Fprintln(&source, "\tif err != nil {")
		fmt.Fprintf(&source, "\t\treturn Invocations{}, fmt.Errorf(\"%%w: generated Plugin ID %%q: %%w\", ErrInvocationAssembly, %s, err)\n", strconv.Quote(provider.PluginID))
		fmt.Fprintln(&source, "\t}")
	}
	for _, invocation := range invocations {
		if invocation.intrinsic {
			continue
		}
		renderEndpointBinding(&source, options, invocation)
	}
	fmt.Fprintln(&source, "\tcatalog, err := kernelinvocation.NewCatalog(bindings)")
	fmt.Fprintln(&source, "\tif err != nil {")
	fmt.Fprintln(&source, "\t\treturn Invocations{}, fmt.Errorf(\"%w: canonical catalog: %w\", ErrInvocationAssembly, err)")
	fmt.Fprintln(&source, "\t}")
	fmt.Fprintln(&source, "\tif err := pending.dispatcher.Publish(catalog); err != nil {")
	fmt.Fprintln(&source, "\t\treturn Invocations{}, fmt.Errorf(\"%w: publish canonical catalog: %w\", ErrInvocationAssembly, err)")
	fmt.Fprintln(&source, "\t}")
	fmt.Fprintln(&source, "\treturn Invocations{")
	fmt.Fprintln(&source, "\t\tcatalog:     catalog,")
	fmt.Fprintln(&source, "\t\tdispatcher:  pending.dispatcher,")
	for _, invocation := range invocations {
		fmt.Fprintf(&source, "\t\thandle%d:     pending.handle%d,\n", invocation.index, invocation.index)
	}
	fmt.Fprintln(&source, "\t\tinitialized: true,")
	fmt.Fprintln(&source, "\t}, nil")
	fmt.Fprintln(&source, "}")
	for _, invocation := range invocations {
		if invocation.intrinsic || invocation.provider.ModulePath == options.ModulePath {
			continue
		}
		renderProviderConversion(&source, invocation, "Request", invocation.contract.Request, true)
		renderProviderConversion(&source, invocation, "Response", invocation.contract.Response, false)
	}

	formatted, err := format.Source([]byte(source.String()))
	if err != nil {
		return nil, fmt.Errorf("%w: format generated source: %v", ErrRenderInvocations, err)
	}
	return append([]byte(nil), formatted...), nil
}

func planInvocations(options InvocationOptions) ([]plannedInvocation, []int, error) {
	if err := module.CheckPath(options.ModulePath); err != nil {
		return nil, nil, fmt.Errorf("%w: application Go Module path %q: %v", ErrInvalidInvocation, options.ModulePath, err)
	}
	if options.DefaultTimeout <= 0 {
		return nil, nil, fmt.Errorf("%w: default invocation timeout must be positive", ErrInvalidInvocation)
	}
	if _, err := kernelinvocation.NewModuleBuild(kernelintrinsic.ModulePath, options.KernelModuleVersion, options.KernelBuildIdentity); err != nil {
		return nil, nil, fmt.Errorf("%w: intrinsic Kernel build provenance: %v", ErrInvalidInvocation, err)
	}
	providers, _, err := planProviders(options.Providers)
	if err != nil {
		return nil, nil, err
	}
	providerByID := make(map[string]indexedProvider, len(providers))
	for index, provider := range providers {
		providerByID[provider.PluginID] = indexedProvider{plannedProvider: provider, index: index}
	}

	invocations := make([]plannedInvocation, len(options.Invocations))
	for index, input := range options.Invocations {
		canonical, err := capabilitymeta.NormalizeSchema(input.ContractJSON)
		if err != nil {
			return nil, nil, fmt.Errorf("%w: invocation %d contract: %v", ErrInvalidInvocation, index, err)
		}
		var contract runtimeContract
		if err := json.Unmarshal(canonical, &contract); err != nil {
			return nil, nil, fmt.Errorf("%w: invocation %d contract: %v", ErrInvalidInvocation, index, err)
		}
		identifier, err := capabilityid.Parse(contract.ID)
		if err != nil {
			return nil, nil, fmt.Errorf("%w: invocation %d Capability ID: %v", ErrInvalidInvocation, index, err)
		}
		reservedIntrinsic := strings.HasPrefix(identifier.Name(), "kernel.")
		if input.Intrinsic != reservedIntrinsic {
			return nil, nil, fmt.Errorf("%w: Capability %s must be intrinsic exactly when it uses the reserved kernel.* namespace", ErrInvalidInvocation, identifier)
		}
		var provider indexedProvider
		if input.Intrinsic {
			if input.ProviderID != "" || input.SelectionReason != kernelinvocation.SelectionReasonIntrinsic {
				return nil, nil, fmt.Errorf("%w: intrinsic Capability %s cannot select an ordinary provider", ErrInvalidInvocation, identifier)
			}
			if err := validateIntrinsicContract(identifier, canonical); err != nil {
				return nil, nil, fmt.Errorf("%w: %v", ErrInvalidInvocation, err)
			}
		} else {
			var exists bool
			provider, exists = providerByID[input.ProviderID]
			if !exists {
				return nil, nil, fmt.Errorf("%w: Capability %s selects absent plugin %q", ErrInvalidInvocation, identifier, input.ProviderID)
			}
			if input.SelectionReason != kernelinvocation.SelectionReasonSoleProvider && input.SelectionReason != kernelinvocation.SelectionReasonExplicit {
				return nil, nil, fmt.Errorf("%w: Capability %s has invalid ordinary selection reason %q", ErrInvalidInvocation, identifier, input.SelectionReason)
			}
			if _, err := kernelinvocation.NewModuleBuild(provider.ModulePath, provider.ModuleVersion, options.ApplicationBuildIdentity); err != nil {
				return nil, nil, fmt.Errorf("%w: plugin %q build provenance: %v", ErrInvalidInvocation, provider.PluginID, err)
			}
		}
		if err := validateRuntimeFields(contract.Request, "request", identifier); err != nil {
			return nil, nil, err
		}
		if err := validateRuntimeFields(contract.Response, "response", identifier); err != nil {
			return nil, nil, err
		}
		dependencies := make([]capabilityid.Identifier, len(input.Dependencies))
		for dependencyIndex, value := range input.Dependencies {
			dependency, err := capabilityid.Parse(value)
			if err != nil {
				return nil, nil, fmt.Errorf("%w: Capability %s dependency %q: %v", ErrInvocationDependency, identifier, value, err)
			}
			dependencies[dependencyIndex] = dependency
		}
		invocations[index] = plannedInvocation{
			id:              identifier,
			contract:        contract,
			digest:          sha256.Sum256(canonical),
			intrinsic:       input.Intrinsic,
			provider:        provider,
			selectionReason: input.SelectionReason,
			dependencies:    dependencies,
			accessor:        invocationAccessor(identifier),
		}
	}
	sort.Slice(invocations, func(left, right int) bool { return invocations[left].id.String() < invocations[right].id.String() })
	byID := make(map[capabilityid.Identifier]int, len(invocations))
	accessors := make(map[string]capabilityid.Identifier, len(invocations))
	for index := range invocations {
		invocations[index].index = index
		if _, duplicate := byID[invocations[index].id]; duplicate {
			return nil, nil, fmt.Errorf("%w: Capability %s", ErrDuplicateInvocation, invocations[index].id)
		}
		byID[invocations[index].id] = index
		if previous, collision := accessors[invocations[index].accessor]; collision {
			return nil, nil, fmt.Errorf("%w: Capabilities %s and %s both generate accessor %s", ErrDuplicateInvocation, previous, invocations[index].id, invocations[index].accessor)
		}
		accessors[invocations[index].accessor] = invocations[index].id
	}
	for _, provider := range providers {
		for _, dependency := range provider.dependencies {
			if _, exists := byID[dependency.id]; !exists {
				return nil, nil, fmt.Errorf("%w: plugin %q dependency %s is not an assembled canonical invocation", ErrInvocationDependency, provider.PluginID, dependency.id)
			}
		}
	}
	for _, invocation := range invocations {
		seen := make(map[capabilityid.Identifier]struct{}, len(invocation.dependencies))
		for _, dependency := range invocation.dependencies {
			if dependency == invocation.id {
				return nil, nil, fmt.Errorf("%w: Capability %s depends on itself", ErrInvocationDependency, invocation.id)
			}
			if _, duplicate := seen[dependency]; duplicate {
				return nil, nil, fmt.Errorf("%w: Capability %s repeats dependency %s", ErrInvocationDependency, invocation.id, dependency)
			}
			seen[dependency] = struct{}{}
			if _, exists := byID[dependency]; !exists {
				return nil, nil, fmt.Errorf("%w: Capability %s dependency %s is not an assembled canonical invocation", ErrInvocationDependency, invocation.id, dependency)
			}
		}
	}
	order, err := invocationOrder(invocations, byID)
	if err != nil {
		return nil, nil, err
	}
	return invocations, order, nil
}

func validateRuntimeFields(fields map[string]runtimeField, section string, identifier capabilityid.Identifier) error {
	goNames := make(map[string]string, len(fields))
	for wireName := range fields {
		goName := goname.Field(wireName)
		if goName == "" {
			return fmt.Errorf("%w: Capability %s %s field %q has no generated Go name", ErrInvalidInvocation, identifier, section, wireName)
		}
		if previous, collision := goNames[goName]; collision {
			return fmt.Errorf("%w: Capability %s %s fields %q and %q both generate %s", ErrInvalidInvocation, identifier, section, previous, wireName, goName)
		}
		goNames[goName] = wireName
	}
	return nil
}

func invocationOrder(invocations []plannedInvocation, byID map[capabilityid.Identifier]int) ([]int, error) {
	const (
		unvisited uint8 = iota
		visiting
		visited
	)
	state := make([]uint8, len(invocations))
	stack := make([]int, 0, len(invocations))
	order := make([]int, 0, len(invocations))
	var visit func(int) error
	visit = func(index int) error {
		state[index] = visiting
		stack = append(stack, index)
		for _, dependency := range invocations[index].dependencies {
			dependencyIndex := byID[dependency]
			switch state[dependencyIndex] {
			case unvisited:
				if err := visit(dependencyIndex); err != nil {
					return err
				}
			case visiting:
				start := 0
				for stack[start] != dependencyIndex {
					start++
				}
				cycle := make([]string, 0, len(stack)-start+1)
				for _, cycleIndex := range stack[start:] {
					cycle = append(cycle, invocations[cycleIndex].id.String())
				}
				cycle = append(cycle, dependency.String())
				return fmt.Errorf("%w: %s", ErrInvocationDependency, strings.Join(cycle, " -> "))
			}
		}
		stack = stack[:len(stack)-1]
		state[index] = visited
		order = append(order, index)
		return nil
	}
	for index := range invocations {
		if state[index] == unvisited {
			if err := visit(index); err != nil {
				return nil, err
			}
		}
	}
	return order, nil
}

func renderEndpointBinding(source *strings.Builder, options InvocationOptions, invocation plannedInvocation) {
	fmt.Fprintf(source, "\tendpoint%d, err := kernelinvocation.NewEndpoint(plystraContract%d, func(ctx context.Context, request contract%d.Request) (contract%d.Response, error) {\n", invocation.index, invocation.index, invocation.index, invocation.index)
	if invocation.provider.ModulePath == options.ModulePath {
		fmt.Fprintf(source, "\t\treturn providers.plugin%d.%s(ctx, request)\n", invocation.provider.index, goname.Operation(invocation.id))
	} else {
		fmt.Fprintf(source, "\t\tresponse, providerError := providers.plugin%d.%s(ctx, plystraProviderRequest%d(request))\n", invocation.provider.index, goname.Operation(invocation.id), invocation.index)
		fmt.Fprintln(source, "\t\tif providerError != nil {")
		fmt.Fprintf(source, "\t\t\treturn contract%d.Response{}, providerError\n", invocation.index)
		fmt.Fprintln(source, "\t\t}")
		fmt.Fprintf(source, "\t\treturn plystraApplicationResponse%d(response), nil\n", invocation.index)
	}
	fmt.Fprintln(source, "\t})")
	fmt.Fprintln(source, "\tif err != nil {")
	fmt.Fprintf(source, "\t\treturn Invocations{}, fmt.Errorf(\"%%w: endpoint %s: %%w\", ErrInvocationAssembly, err)\n", invocation.id)
	fmt.Fprintln(source, "\t}")
	fmt.Fprintf(source, "\tbinding%d, err := kernelinvocation.NewBinding(kernelinvocation.BindingOptions{\n", invocation.index)
	fmt.Fprintln(source, "\t\tProviderKind:    kernelinvocation.ProviderKindPlugin,")
	fmt.Fprintf(source, "\t\tProviderID:      providerID%d,\n", invocation.provider.index)
	fmt.Fprintf(source, "\t\tProviderPackage: %s,\n", strconv.Quote(invocation.provider.ImportPath))
	fmt.Fprintf(source, "\t\tProviderBuild:   providerBuild%d,\n", invocation.provider.index)
	fmt.Fprintf(source, "\t\tSelectionReason: kernelinvocation.%s,\n", selectionReasonName(invocation.selectionReason))
	fmt.Fprintf(source, "\t\tSchemaDigest:    %s,\n", digestLiteral(invocation.digest))
	fmt.Fprintf(source, "\t}, endpoint%d)\n", invocation.index)
	fmt.Fprintln(source, "\tif err != nil {")
	fmt.Fprintf(source, "\t\treturn Invocations{}, fmt.Errorf(\"%%w: binding %s to plugin %%q: %%w\", ErrInvocationAssembly, %s, err)\n", invocation.id, strconv.Quote(invocation.provider.PluginID))
	fmt.Fprintln(source, "\t}")
	fmt.Fprintf(source, "\tbindings = append(bindings, binding%d)\n", invocation.index)
}

func renderProviderConversion(source *strings.Builder, invocation plannedInvocation, section string, fields map[string]runtimeField, request bool) {
	fmt.Fprintln(source)
	functionName := fmt.Sprintf("plystraProviderRequest%d", invocation.index)
	sourceAlias := fmt.Sprintf("contract%d", invocation.index)
	targetAlias := fmt.Sprintf("providercontract%d", invocation.index)
	if !request {
		functionName = fmt.Sprintf("plystraApplicationResponse%d", invocation.index)
		sourceAlias, targetAlias = targetAlias, sourceAlias
	}
	fmt.Fprintf(source, "func %s(value %s.%s) %s.%s {\n", functionName, sourceAlias, section, targetAlias, section)
	fmt.Fprintf(source, "\tvar result %s.%s\n", targetAlias, section)
	names := make([]string, 0, len(fields))
	for name := range fields {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		field := fields[name]
		goName := goname.Field(name)
		if len(field.Enum) == 0 {
			fmt.Fprintf(source, "\tresult.%s = value.%s\n", goName, goName)
			continue
		}
		targetType := targetAlias + "." + section + goName
		if field.Required {
			fmt.Fprintf(source, "\tresult.%s = %s(value.%s)\n", goName, targetType, goName)
			continue
		}
		fmt.Fprintf(source, "\tif value.%s != nil {\n", goName)
		fmt.Fprintf(source, "\t\tconverted := %s(*value.%s)\n", targetType, goName)
		fmt.Fprintf(source, "\t\tresult.%s = &converted\n", goName)
		fmt.Fprintln(source, "\t}")
	}
	fmt.Fprintln(source, "\treturn result")
	fmt.Fprintln(source, "}")
}

func dependencyImportIndexes(invocations []plannedInvocation) []int {
	set := make(map[int]struct{})
	for _, invocation := range invocations {
		for _, dependency := range invocation.dependencies {
			set[indexOfInvocation(invocations, dependency)] = struct{}{}
		}
	}
	indexes := make([]int, 0, len(set))
	for index := range set {
		indexes = append(indexes, index)
	}
	sort.Ints(indexes)
	return indexes
}

func usedProviders(invocations []plannedInvocation) []indexedProvider {
	values := make(map[int]indexedProvider)
	for _, invocation := range invocations {
		if invocation.intrinsic {
			continue
		}
		values[invocation.provider.index] = invocation.provider
	}
	indexes := make([]int, 0, len(values))
	for index := range values {
		indexes = append(indexes, index)
	}
	sort.Ints(indexes)
	result := make([]indexedProvider, len(indexes))
	for index, providerIndex := range indexes {
		result[index] = values[providerIndex]
	}
	return result
}

func ordinaryInvocationCount(invocations []plannedInvocation) int {
	count := 0
	for _, invocation := range invocations {
		if !invocation.intrinsic {
			count++
		}
	}
	return count
}

func validateIntrinsicContract(identifier capabilityid.Identifier, canonical []byte) error {
	if intrinsicContractExpression(identifier) == "" {
		return fmt.Errorf("intrinsic Capability %s has no supported typed Kernel contract", identifier)
	}
	digest := sha256.Sum256(canonical)
	for _, definition := range kernelcatalog.Definitions() {
		if definition.ID().String() != identifier.String() {
			continue
		}
		if definition.SchemaDigest() != digest {
			return fmt.Errorf("intrinsic Capability %s differs from the Kernel catalog", identifier)
		}
		return nil
	}
	return fmt.Errorf("intrinsic Capability %s is absent from the Kernel catalog", identifier)
}

func intrinsicContractExpression(identifier capabilityid.Identifier) string {
	switch identifier.String() {
	case "kernel.health/v1":
		return "kernelintrinsic.HealthContract()"
	case "kernel.info/v1":
		return "kernelintrinsic.InfoContract()"
	default:
		return ""
	}
}

func indexOfInvocation(invocations []plannedInvocation, identifier capabilityid.Identifier) int {
	index := sort.Search(len(invocations), func(index int) bool {
		return invocations[index].id.String() >= identifier.String()
	})
	if index >= len(invocations) || invocations[index].id != identifier {
		return -1
	}
	return index
}

func invocationAccessor(identifier capabilityid.Identifier) string {
	parts := strings.FieldsFunc(identifier.Name(), func(character rune) bool { return character == '.' || character == '-' })
	for index := range parts {
		parts[index] = goname.ExportedWord(parts[index])
	}
	return strings.Join(parts, "") + "V" + strconv.FormatUint(identifier.Major(), 10)
}

func applicationContractPath(modulePath string, identifier capabilityid.Identifier) string {
	return path.Join(modulePath, generatedCapabilityDirectory("contracts", identifier))
}

func applicationInvocationPath(modulePath string, identifier capabilityid.Identifier) string {
	return path.Join(modulePath, generatedCapabilityDirectory("invocation", identifier))
}

func applicationClientPath(modulePath string, identifier capabilityid.Identifier) string {
	return path.Join(modulePath, generatedCapabilityDirectory("clients", identifier))
}

func generatedCapabilityDirectory(category string, identifier capabilityid.Identifier) string {
	components := append([]string{"generated", "go", category}, strings.Split(identifier.Name(), ".")...)
	components = append(components, "v"+strconv.FormatUint(identifier.Major(), 10))
	return path.Join(components...)
}

func selectionReasonName(reason kernelinvocation.SelectionReason) string {
	switch reason {
	case kernelinvocation.SelectionReasonSoleProvider:
		return "SelectionReasonSoleProvider"
	case kernelinvocation.SelectionReasonExplicit:
		return "SelectionReasonExplicit"
	default:
		return ""
	}
}

func digestLiteral(digest [sha256.Size]byte) string {
	var result strings.Builder
	result.WriteString("[32]byte{")
	for index, value := range digest {
		if index != 0 {
			result.WriteString(", ")
		}
		fmt.Fprintf(&result, "0x%02x", value)
	}
	result.WriteByte('}')
	return result.String()
}
