package assemblygen

import (
	"encoding/json"
	"errors"
	"fmt"
	"go/format"
	"path"
	"sort"
	"strconv"
	"strings"

	"github.com/plystra/cli/internal/capabilityid"
	"github.com/plystra/cli/internal/capabilitymeta"
	"github.com/plystra/cli/internal/configurationgen"
	"github.com/plystra/cli/internal/goname"
	"github.com/plystra/cli/internal/pluginid"
	"golang.org/x/mod/module"
)

// ProvidersPath is the application-relative selected-provider source path.
const ProvidersPath = "generated/go/assembly/providers_gen.go"

var (
	// ErrRenderProviders reports invalid selected-plugin provenance or a
	// generated provider source formatting failure.
	ErrRenderProviders = errors.New("render selected plugin providers")
	// ErrInvalidProvider reports one selected plugin that cannot be imported
	// through the required direct-child Go Module layout.
	ErrInvalidProvider = errors.New("invalid selected plugin provider")
	// ErrDuplicateProvider reports repeated Plugin IDs, import paths, or
	// generated configuration symbols in one provider plan.
	ErrDuplicateProvider = errors.New("duplicate selected plugin provider")
)

// ProviderInput is the complete public build provenance needed to import and
// construct one selected plugin. It contains no runtime configuration values.
type ProviderInput struct {
	PluginID      string
	ModulePath    string
	ModuleVersion string
	ImportPath    string
	Dependencies  []DependencyInput
}

// DependencyInput is one exact canonical Capability client required by a
// selected plugin constructor. ContractJSON is the final resolved contract
// used to generate safe cross-module adapters.
type DependencyInput struct {
	Capability   string
	ContractJSON []byte
}

type plannedDependency struct {
	id                  capabilityid.Identifier
	contract            runtimeContract
	accessor            string
	dependenciesAlias   string
	clientAlias         string
	providerContract    string
	applicationContract string
	local               bool
}

type plannedProvider struct {
	ProviderInput
	configurationNames configurationgen.GoNames
	pluginAlias        string
	configurationAlias string
	dependencies       []plannedDependency
}

type importSpec struct {
	alias string
	path  string
}

// RenderProviders emits the immutable runtime construction boundary for every
// selected plugin. The generated source extracts private values only at
// startup, rejects stale configuration before invoking constructors, and
// never embeds application runtime values or Secret reference targets.
func RenderProviders(applicationModulePath string, inputs []ProviderInput) ([]byte, error) {
	if err := module.CheckPath(applicationModulePath); err != nil {
		return nil, fmt.Errorf("%w: %w: invalid application Go Module path %q: %v", ErrRenderProviders, ErrInvalidProvider, applicationModulePath, err)
	}
	providers, imports, err := planProviders(inputs)
	if err != nil {
		return nil, fmt.Errorf("%w: %w", ErrRenderProviders, err)
	}
	imports, err = planDependencyImports(applicationModulePath, providers, imports)
	if err != nil {
		return nil, fmt.Errorf("%w: %w", ErrRenderProviders, err)
	}

	var source strings.Builder
	fmt.Fprintln(&source, "// Code generated by Plystra CLI. DO NOT EDIT.")
	fmt.Fprintln(&source)
	fmt.Fprintln(&source, "package assembly")
	fmt.Fprintln(&source)
	fmt.Fprintln(&source, "import (")
	fmt.Fprintln(&source, "\t\"context\"")
	fmt.Fprintln(&source, "\t\"errors\"")
	fmt.Fprintln(&source, "\t\"fmt\"")
	fmt.Fprintln(&source, "\t\"log/slog\"")
	fmt.Fprintln(&source, "\t\"time\"")
	fmt.Fprintln(&source)
	fmt.Fprintln(&source, "\tkernelconfiguration \"github.com/plystra/kernel/configuration\"")
	fmt.Fprintln(&source, "\tkernellifecycle \"github.com/plystra/kernel/lifecycle\"")
	if len(providers) != 0 {
		fmt.Fprintln(&source, "\tkernelplugin \"github.com/plystra/kernel/plugin\"")
	}
	for _, imported := range imports {
		fmt.Fprintf(&source, "\t%s %s\n", imported.alias, strconv.Quote(imported.path))
	}
	fmt.Fprintln(&source, ")")
	fmt.Fprintln(&source)
	fmt.Fprintln(&source, "var (")
	fmt.Fprintln(&source, "\t// ErrProviderAssembly reports a safe selected-plugin startup failure.")
	fmt.Fprintln(&source, "\tErrProviderAssembly = errors.New(\"assemble selected plugin providers\")")
	fmt.Fprintln(&source, "\t// ErrUnselectedPluginConfiguration reports stale configuration outside the selected plugin set.")
	fmt.Fprintln(&source, "\tErrUnselectedPluginConfiguration = errors.New(\"configuration targets unselected plugin\")")
	fmt.Fprintln(&source, "\t// ErrPluginConstructor reports a selected constructor panic or nil result.")
	fmt.Fprintln(&source, "\tErrPluginConstructor = errors.New(\"plugin constructor failed\")")
	fmt.Fprintln(&source, "\t// ErrProviderLifecycle reports invalid generated lifecycle binding or manager options.")
	fmt.Fprintln(&source, "\tErrProviderLifecycle = errors.New(\"assemble selected provider lifecycle\")")
	fmt.Fprintln(&source, "\t// ErrRuntimeAssembly reports a failure before one complete generated runtime is published.")
	fmt.Fprintln(&source, "\tErrRuntimeAssembly = errors.New(\"assemble generated application runtime\")")
	fmt.Fprintln(&source, ")")
	fmt.Fprintln(&source)
	fmt.Fprintln(&source, "// Providers is the immutable set of selected in-process plugin providers.")
	fmt.Fprintln(&source, "// Its concrete values and configuration always remain redacted.")
	fmt.Fprintln(&source, "type Providers struct {")
	for index, provider := range providers {
		fmt.Fprintf(&source, "\tplugin%d *%s.Plugin\n", index, provider.pluginAlias)
	}
	fmt.Fprintln(&source, "\tinitialized bool")
	fmt.Fprintln(&source, "}")
	fmt.Fprintln(&source)
	fmt.Fprintln(&source, "// Valid reports whether all selected constructors completed successfully.")
	fmt.Fprintln(&source, "func (p Providers) Valid() bool {")
	fmt.Fprintln(&source, "\tif !p.initialized {")
	fmt.Fprintln(&source, "\t\treturn false")
	fmt.Fprintln(&source, "\t}")
	if len(providers) == 0 {
		fmt.Fprintln(&source, "\treturn true")
	} else {
		fmt.Fprint(&source, "\treturn ")
		for index := range providers {
			if index != 0 {
				fmt.Fprint(&source, " && ")
			}
			fmt.Fprintf(&source, "p.plugin%d != nil", index)
		}
		fmt.Fprintln(&source)
	}
	fmt.Fprintln(&source, "}")
	fmt.Fprintln(&source)
	fmt.Fprintln(&source, "// Len returns the selected provider count for a valid set.")
	fmt.Fprintln(&source, "func (p Providers) Len() int {")
	fmt.Fprintln(&source, "\tif !p.Valid() {")
	fmt.Fprintln(&source, "\t\treturn 0")
	fmt.Fprintln(&source, "\t}")
	fmt.Fprintf(&source, "\treturn %d\n", len(providers))
	fmt.Fprintln(&source, "}")
	fmt.Fprintln(&source)
	fmt.Fprintln(&source, "// String redacts every provider and its configuration.")
	fmt.Fprintln(&source, "func (Providers) String() string { return \"<redacted-plugin-providers>\" }")
	fmt.Fprintln(&source)
	fmt.Fprintln(&source, "// GoString prevents Go-syntax formatting from exposing provider state.")
	fmt.Fprintln(&source, "func (Providers) GoString() string { return \"<redacted-plugin-providers>\" }")
	fmt.Fprintln(&source)
	fmt.Fprintln(&source, "// Format redacts provider state for every fmt verb.")
	fmt.Fprintln(&source, "func (Providers) Format(state fmt.State, _ rune) {")
	fmt.Fprintln(&source, "\t_, _ = state.Write([]byte(\"<redacted-plugin-providers>\"))")
	fmt.Fprintln(&source, "}")
	fmt.Fprintln(&source)
	fmt.Fprintln(&source, "// LogValue redacts provider state for structured standard-library logging.")
	fmt.Fprintln(&source, "func (Providers) LogValue() slog.Value {")
	fmt.Fprintln(&source, "\treturn slog.StringValue(\"<redacted-plugin-providers>\")")
	fmt.Fprintln(&source, "}")
	fmt.Fprintln(&source)
	fmt.Fprintln(&source, "// MarshalJSON rejects accidental provider serialization.")
	fmt.Fprintln(&source, "func (Providers) MarshalJSON() ([]byte, error) {")
	fmt.Fprintln(&source, "\treturn nil, kernelconfiguration.ErrSecretExposure")
	fmt.Fprintln(&source, "}")
	fmt.Fprintln(&source)
	fmt.Fprintln(&source, "// MarshalText rejects accidental provider serialization.")
	fmt.Fprintln(&source, "func (Providers) MarshalText() ([]byte, error) {")
	fmt.Fprintln(&source, "\treturn nil, kernelconfiguration.ErrSecretExposure")
	fmt.Fprintln(&source, "}")
	fmt.Fprintln(&source)
	fmt.Fprintln(&source, "// MarshalYAML rejects accidental provider serialization.")
	fmt.Fprintln(&source, "func (Providers) MarshalYAML() (any, error) {")
	fmt.Fprintln(&source, "\treturn nil, kernelconfiguration.ErrSecretExposure")
	fmt.Fprintln(&source, "}")
	fmt.Fprintln(&source)
	fmt.Fprintln(&source, "// NewRuntime prepares typed application clients before constructors, decodes")
	fmt.Fprintln(&source, "// exactly one private configuration object per selected Plugin ID, constructs")
	fmt.Fprintln(&source, "// every provider, and only then publishes the complete canonical runtime.")
	fmt.Fprintln(&source, "func NewRuntime(ctx context.Context, resolver *kernelconfiguration.Resolver, document []byte) (Providers, Invocations, error) {")
	fmt.Fprintln(&source, "\tpending, err := newPendingInvocations()")
	fmt.Fprintln(&source, "\tif err != nil {")
	fmt.Fprintln(&source, "\t\treturn Providers{}, Invocations{}, fmt.Errorf(\"%w: prepare invocation clients: %w\", ErrRuntimeAssembly, err)")
	fmt.Fprintln(&source, "\t}")
	fmt.Fprintln(&source, "\tproviders, err := newProviders(ctx, resolver, document, pending)")
	fmt.Fprintln(&source, "\tif err != nil {")
	fmt.Fprintln(&source, "\t\treturn Providers{}, Invocations{}, fmt.Errorf(\"%w: %w\", ErrRuntimeAssembly, err)")
	fmt.Fprintln(&source, "\t}")
	fmt.Fprintln(&source, "\tinvocations, err := publishInvocations(pending, providers)")
	fmt.Fprintln(&source, "\tif err != nil {")
	fmt.Fprintln(&source, "\t\treturn Providers{}, Invocations{}, fmt.Errorf(\"%w: %w\", ErrRuntimeAssembly, err)")
	fmt.Fprintln(&source, "\t}")
	fmt.Fprintln(&source, "\treturn providers, invocations, nil")
	fmt.Fprintln(&source, "}")
	fmt.Fprintln(&source)
	fmt.Fprintln(&source, "// newProviders validates the generated Kernel boundary, decodes exactly one")
	fmt.Fprintln(&source, "// private configuration object per selected Plugin ID, and invokes each")
	fmt.Fprintln(&source, "// selected plugin constructor exactly once.")
	fmt.Fprintln(&source, "func newProviders(ctx context.Context, resolver *kernelconfiguration.Resolver, document []byte, pending pendingInvocations) (Providers, error) {")
	fmt.Fprintln(&source, "\tif err := RequireKernelCompatibility(); err != nil {")
	fmt.Fprintln(&source, "\t\treturn Providers{}, fmt.Errorf(\"%w: Kernel compatibility: %w\", ErrProviderAssembly, err)")
	fmt.Fprintln(&source, "\t}")
	fmt.Fprintln(&source, "\tif !pending.valid() {")
	fmt.Fprintln(&source, "\t\treturn Providers{}, fmt.Errorf(\"%w: pending invocation clients are invalid\", ErrProviderAssembly)")
	fmt.Fprintln(&source, "\t}")
	fmt.Fprintln(&source, "\tconfigurations, err := kernelconfiguration.ExtractObjectMap(document, \"config\")")
	fmt.Fprintln(&source, "\tif err != nil {")
	fmt.Fprintln(&source, "\t\treturn Providers{}, fmt.Errorf(\"%w: extract runtime configuration: %w\", ErrProviderAssembly, err)")
	fmt.Fprintln(&source, "\t}")
	fmt.Fprintln(&source, "\tfor _, pluginID := range configurations.Names() {")
	if len(providers) == 0 {
		source.WriteString("\t\treturn Providers{}, fmt.Errorf(\"%w: %w %q\", ErrProviderAssembly, ErrUnselectedPluginConfiguration, pluginID)\n")
	} else {
		fmt.Fprintln(&source, "\t\tswitch pluginID {")
		fmt.Fprint(&source, "\t\tcase ")
		for index, provider := range providers {
			if index != 0 {
				fmt.Fprint(&source, ", ")
			}
			fmt.Fprint(&source, strconv.Quote(provider.PluginID))
		}
		fmt.Fprintln(&source, ":")
		fmt.Fprintln(&source, "\t\tdefault:")
		source.WriteString("\t\t\treturn Providers{}, fmt.Errorf(\"%w: %w %q\", ErrProviderAssembly, ErrUnselectedPluginConfiguration, pluginID)\n")
		fmt.Fprintln(&source, "\t\t}")
	}
	fmt.Fprintln(&source, "\t}")
	for index, provider := range providers {
		fmt.Fprintf(&source, "\tpluginConfigurationData%d, exists := configurations.YAML(%s)\n", index, strconv.Quote(provider.PluginID))
		fmt.Fprintln(&source, "\tif !exists {")
		fmt.Fprintf(&source, "\t\tpluginConfigurationData%d = []byte(\"{}\\n\")\n", index)
		fmt.Fprintln(&source, "\t}")
		fmt.Fprintf(&source, "\tpluginConfiguration%d, err := %s.%s(ctx, resolver, pluginConfigurationData%d)\n", index, provider.configurationAlias, provider.configurationNames.DecodeName(), index)
		fmt.Fprintf(&source, "\tclear(pluginConfigurationData%d)\n", index)
		fmt.Fprintln(&source, "\tif err != nil {")
		fmt.Fprintf(&source, "\t\treturn Providers{}, fmt.Errorf(\"%%w: decode plugin %%q configuration: %%w\", ErrProviderAssembly, %s, err)\n", strconv.Quote(provider.PluginID))
		fmt.Fprintln(&source, "\t}")
	}
	for index := range providers {
		fmt.Fprintf(&source, "\tplugin%d, err := constructPlugin%d(pluginConfiguration%d, pending)\n", index, index, index)
		fmt.Fprintln(&source, "\tif err != nil {")
		fmt.Fprintln(&source, "\t\treturn Providers{}, fmt.Errorf(\"%w: %w\", ErrProviderAssembly, err)")
		fmt.Fprintln(&source, "\t}")
	}
	fmt.Fprintln(&source, "\treturn Providers{")
	for index := range providers {
		fmt.Fprintf(&source, "\t\tplugin%d: plugin%d,\n", index, index)
	}
	fmt.Fprintln(&source, "\t\tinitialized: true,")
	fmt.Fprintln(&source, "\t}, nil")
	fmt.Fprintln(&source, "}")
	fmt.Fprintln(&source)
	fmt.Fprintln(&source, "// NewProviderLifecycle binds optional lifecycle providers in deterministic")
	fmt.Fprintln(&source, "// selected Plugin ID order. The Kernel starts this order and stops it in reverse.")
	fmt.Fprintln(&source, "func NewProviderLifecycle(providers Providers, rollbackTimeout time.Duration) (*kernellifecycle.Manager, error) {")
	fmt.Fprintln(&source, "\tif !providers.Valid() {")
	fmt.Fprintln(&source, "\t\treturn nil, fmt.Errorf(\"%w: providers are invalid\", ErrProviderLifecycle)")
	fmt.Fprintln(&source, "\t}")
	fmt.Fprintf(&source, "\tbindings := make([]kernellifecycle.Binding, 0, %d)\n", len(providers))
	for index, provider := range providers {
		fmt.Fprintf(&source, "\tif lifecycleProvider, ok := any(providers.plugin%d).(kernellifecycle.Provider); ok {\n", index)
		fmt.Fprintf(&source, "\t\tpluginID, err := kernelplugin.ParseID(%s)\n", strconv.Quote(provider.PluginID))
		fmt.Fprintln(&source, "\t\tif err != nil {")
		fmt.Fprintf(&source, "\t\t\treturn nil, fmt.Errorf(\"%%w: generated Plugin ID %%q: %%w\", ErrProviderLifecycle, %s, err)\n", strconv.Quote(provider.PluginID))
		fmt.Fprintln(&source, "\t\t}")
		fmt.Fprintln(&source, "\t\tbinding, err := kernellifecycle.NewBinding(pluginID, lifecycleProvider)")
		fmt.Fprintln(&source, "\t\tif err != nil {")
		fmt.Fprintf(&source, "\t\t\treturn nil, fmt.Errorf(\"%%w: plugin %%q: %%w\", ErrProviderLifecycle, %s, err)\n", strconv.Quote(provider.PluginID))
		fmt.Fprintln(&source, "\t\t}")
		fmt.Fprintln(&source, "\t\tbindings = append(bindings, binding)")
		fmt.Fprintln(&source, "\t}")
	}
	fmt.Fprintln(&source, "\tmanager, err := kernellifecycle.NewManager(kernellifecycle.ManagerOptions{RollbackTimeout: rollbackTimeout}, bindings)")
	fmt.Fprintln(&source, "\tif err != nil {")
	fmt.Fprintln(&source, "\t\treturn nil, fmt.Errorf(\"%w: %w\", ErrProviderLifecycle, err)")
	fmt.Fprintln(&source, "\t}")
	fmt.Fprintln(&source, "\treturn manager, nil")
	fmt.Fprintln(&source, "}")

	for index, provider := range providers {
		fmt.Fprintln(&source)
		fmt.Fprintf(&source, "func constructPlugin%d(configuration %s.%s, pending pendingInvocations) (plugin *%s.Plugin, err error) {\n", index, provider.configurationAlias, provider.configurationNames.TypeName(), provider.pluginAlias)
		fmt.Fprintln(&source, "\tdefer func() {")
		fmt.Fprintln(&source, "\t\tif recover() != nil {")
		fmt.Fprintln(&source, "\t\t\tplugin = nil")
		fmt.Fprintf(&source, "\t\t\terr = fmt.Errorf(\"%%w: plugin %%q panicked\", ErrPluginConstructor, %s)\n", strconv.Quote(provider.PluginID))
		fmt.Fprintln(&source, "\t\t}")
		fmt.Fprintln(&source, "\t}()")
		if len(provider.dependencies) == 0 {
			fmt.Fprintf(&source, "\tplugin = %s.New(configuration)\n", provider.pluginAlias)
		} else {
			fmt.Fprintf(&source, "\tdependencies, dependencyError := %s.New(\n", provider.dependencies[0].dependenciesAlias)
			for depIndex, dependency := range provider.dependencies {
				renderDependencyClient(&source, index, depIndex, dependency)
			}
			fmt.Fprintln(&source, "\t)")
			fmt.Fprintln(&source, "\tif dependencyError != nil {")
			fmt.Fprintf(&source, "\t\treturn nil, fmt.Errorf(\"%%w: plugin %%q dependencies\", ErrPluginConstructor, %s)\n", strconv.Quote(provider.PluginID))
			fmt.Fprintln(&source, "\t}")
			fmt.Fprintf(&source, "\tplugin = %s.New(configuration, dependencies)\n", provider.pluginAlias)
		}
		fmt.Fprintln(&source, "\tif plugin == nil {")
		fmt.Fprintf(&source, "\t\treturn nil, fmt.Errorf(\"%%w: plugin %%q returned nil\", ErrPluginConstructor, %s)\n", strconv.Quote(provider.PluginID))
		fmt.Fprintln(&source, "\t}")
		fmt.Fprintln(&source, "\treturn plugin, nil")
		fmt.Fprintln(&source, "}")
	}
	for providerIndex, provider := range providers {
		for dependencyIndex, dependency := range provider.dependencies {
			if dependency.local {
				continue
			}
			renderDependencyAdapter(&source, providerIndex, dependencyIndex, dependency)
		}
	}

	formatted, err := format.Source([]byte(source.String()))
	if err != nil {
		return nil, fmt.Errorf("%w: format generated source: %v", ErrRenderProviders, err)
	}
	return append([]byte(nil), formatted...), nil
}

func planProviderDependencies(pluginID string, inputs []DependencyInput) ([]plannedDependency, error) {
	dependencies := make([]plannedDependency, len(inputs))
	seen := make(map[capabilityid.Identifier]struct{}, len(inputs))
	accessors := make(map[string]capabilityid.Identifier, len(inputs))
	for index, input := range inputs {
		canonical, err := capabilitymeta.NormalizeSchema(input.ContractJSON)
		if err != nil {
			return nil, fmt.Errorf("%w: plugin %q dependency %q contract: %v", ErrInvalidProvider, pluginID, input.Capability, err)
		}
		var contract runtimeContract
		if err := json.Unmarshal(canonical, &contract); err != nil {
			return nil, fmt.Errorf("%w: plugin %q dependency %q contract: %v", ErrInvalidProvider, pluginID, input.Capability, err)
		}
		identifier, err := capabilityid.Parse(contract.ID)
		if err != nil {
			return nil, fmt.Errorf("%w: plugin %q dependency %q contract identity: %v", ErrInvalidProvider, pluginID, input.Capability, err)
		}
		if input.Capability != identifier.String() {
			return nil, fmt.Errorf("%w: plugin %q dependency %q carries contract %s", ErrInvalidProvider, pluginID, input.Capability, identifier)
		}
		if _, duplicate := seen[identifier]; duplicate {
			return nil, fmt.Errorf("%w: plugin %q duplicates dependency %s", ErrDuplicateProvider, pluginID, identifier)
		}
		seen[identifier] = struct{}{}
		if err := validateRuntimeFields(contract.Request, "request", identifier); err != nil {
			return nil, fmt.Errorf("%w: plugin %q dependency: %v", ErrInvalidProvider, pluginID, err)
		}
		if err := validateRuntimeFields(contract.Response, "response", identifier); err != nil {
			return nil, fmt.Errorf("%w: plugin %q dependency: %v", ErrInvalidProvider, pluginID, err)
		}
		accessor := invocationAccessor(identifier)
		if previous, collision := accessors[accessor]; collision {
			return nil, fmt.Errorf("%w: plugin %q dependencies %s and %s both generate accessor %s", ErrDuplicateProvider, pluginID, previous, identifier, accessor)
		}
		accessors[accessor] = identifier
		dependencies[index] = plannedDependency{id: identifier, contract: contract, accessor: accessor}
	}
	sort.Slice(dependencies, func(left, right int) bool {
		return dependencies[left].id.String() < dependencies[right].id.String()
	})
	return dependencies, nil
}

func planDependencyImports(applicationModulePath string, providers []plannedProvider, imports []importSpec) ([]importSpec, error) {
	byPath := make(map[string]string, len(imports))
	usedAliases := make(map[string]string, len(imports))
	for _, imported := range imports {
		byPath[imported.path] = imported.alias
		usedAliases[imported.alias] = imported.path
	}
	add := func(importPath, preferredAlias string) (string, error) {
		if err := module.CheckImportPath(importPath); err != nil {
			return "", fmt.Errorf("%w: generated dependency import path %q: %v", ErrInvalidProvider, importPath, err)
		}
		if alias, exists := byPath[importPath]; exists {
			return alias, nil
		}
		alias := preferredAlias
		for suffix := 1; ; suffix++ {
			if previous, collision := usedAliases[alias]; !collision {
				break
			} else if previous == importPath {
				return alias, nil
			}
			alias = preferredAlias + strconv.Itoa(suffix)
		}
		byPath[importPath] = alias
		usedAliases[alias] = importPath
		imports = append(imports, importSpec{alias: alias, path: importPath})
		return alias, nil
	}

	for providerIndex := range providers {
		provider := &providers[providerIndex]
		if len(provider.dependencies) == 0 {
			continue
		}
		pluginName := path.Base(provider.ImportPath)
		dependenciesAlias, err := add(path.Join(provider.ModulePath, "generated/go/dependencies", pluginName), fmt.Sprintf("dependencies%d", providerIndex))
		if err != nil {
			return nil, err
		}
		for dependencyIndex := range provider.dependencies {
			dependency := &provider.dependencies[dependencyIndex]
			dependency.dependenciesAlias = dependenciesAlias
			dependency.local = provider.ModulePath == applicationModulePath
			dependency.clientAlias, err = add(applicationClientPath(provider.ModulePath, dependency.id), fmt.Sprintf("providerclient%d_%d", providerIndex, dependencyIndex))
			if err != nil {
				return nil, err
			}
			if dependency.local {
				continue
			}
			dependency.providerContract, err = add(applicationContractPath(provider.ModulePath, dependency.id), fmt.Sprintf("providerdependencycontract%d_%d", providerIndex, dependencyIndex))
			if err != nil {
				return nil, err
			}
			dependency.applicationContract, err = add(applicationContractPath(applicationModulePath, dependency.id), fmt.Sprintf("applicationdependencycontract%d_%d", providerIndex, dependencyIndex))
			if err != nil {
				return nil, err
			}
		}
	}
	sort.Slice(imports, func(left, right int) bool { return imports[left].path < imports[right].path })
	return imports, nil
}

func renderDependencyClient(source *strings.Builder, providerIndex, dependencyIndex int, dependency plannedDependency) {
	if dependency.local {
		fmt.Fprintf(source, "\t\t%s.New(pending.dependency%s()),\n", dependency.clientAlias, dependency.accessor)
		return
	}
	fmt.Fprintf(source, "\t\t%s.New(provider%dDependency%d{\n", dependency.clientAlias, providerIndex, dependencyIndex)
	fmt.Fprintf(source, "\t\t\tavailable: pending.dependency%s().Available,\n", dependency.accessor)
	fmt.Fprintf(source, "\t\t\tinvoke:    pending.dependency%s().Invoke,\n", dependency.accessor)
	fmt.Fprintln(source, "\t\t}),")
}

func renderDependencyAdapter(source *strings.Builder, providerIndex, dependencyIndex int, dependency plannedDependency) {
	typeName := fmt.Sprintf("provider%dDependency%d", providerIndex, dependencyIndex)
	fmt.Fprintln(source)
	fmt.Fprintf(source, "type %s struct {\n", typeName)
	fmt.Fprintln(source, "\tavailable func() bool")
	fmt.Fprintf(source, "\tinvoke func(context.Context, %s.Request) (%s.Response, error)\n", dependency.applicationContract, dependency.applicationContract)
	fmt.Fprintln(source, "}")
	fmt.Fprintln(source)
	fmt.Fprintf(source, "func (d %s) Available() bool {\n", typeName)
	fmt.Fprintln(source, "\treturn d.available != nil && d.invoke != nil && d.available()")
	fmt.Fprintln(source, "}")
	fmt.Fprintln(source)
	fmt.Fprintf(source, "func (d %s) Invoke(ctx context.Context, request %s.Request) (%s.Response, error) {\n", typeName, dependency.providerContract, dependency.providerContract)
	fmt.Fprintln(source, "\tif !d.Available() {")
	fmt.Fprintf(source, "\t\treturn %s.Response{}, ErrPluginConstructor\n", dependency.providerContract)
	fmt.Fprintln(source, "\t}")
	fmt.Fprintf(source, "\tresponse, err := d.invoke(ctx, provider%dDependency%dApplicationRequest(request))\n", providerIndex, dependencyIndex)
	fmt.Fprintln(source, "\tif err != nil {")
	fmt.Fprintf(source, "\t\treturn %s.Response{}, err\n", dependency.providerContract)
	fmt.Fprintln(source, "\t}")
	fmt.Fprintf(source, "\treturn provider%dDependency%dProviderResponse(response), nil\n", providerIndex, dependencyIndex)
	fmt.Fprintln(source, "}")
	renderDependencyConversion(source, fmt.Sprintf("provider%dDependency%dApplicationRequest", providerIndex, dependencyIndex), dependency.providerContract, dependency.applicationContract, "Request", dependency.contract.Request)
	renderDependencyConversion(source, fmt.Sprintf("provider%dDependency%dProviderResponse", providerIndex, dependencyIndex), dependency.applicationContract, dependency.providerContract, "Response", dependency.contract.Response)
}

func renderDependencyConversion(source *strings.Builder, functionName, sourceAlias, targetAlias, section string, fields map[string]runtimeField) {
	fmt.Fprintln(source)
	fmt.Fprintf(source, "func %s(value %s.%s) %s.%s {\n", functionName, sourceAlias, section, targetAlias, section)
	fmt.Fprintf(source, "\tvar result %s.%s\n", targetAlias, section)
	names := make([]string, 0, len(fields))
	for name := range fields {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		field := fields[name]
		goName := goname.Field(name)
		if len(field.Enum) == 0 {
			fmt.Fprintf(source, "\tresult.%s = value.%s\n", goName, goName)
			continue
		}
		targetType := targetAlias + "." + section + goName
		if field.Required {
			fmt.Fprintf(source, "\tresult.%s = %s(value.%s)\n", goName, targetType, goName)
			continue
		}
		fmt.Fprintf(source, "\tif value.%s != nil {\n", goName)
		fmt.Fprintf(source, "\t\tconverted := %s(*value.%s)\n", targetType, goName)
		fmt.Fprintf(source, "\t\tresult.%s = &converted\n", goName)
		fmt.Fprintln(source, "\t}")
	}
	fmt.Fprintln(source, "\treturn result")
	fmt.Fprintln(source, "}")
}

func planProviders(inputs []ProviderInput) ([]plannedProvider, []importSpec, error) {
	providers := make([]plannedProvider, len(inputs))
	for index, input := range inputs {
		if err := pluginid.Validate(input.PluginID); err != nil {
			return nil, nil, fmt.Errorf("%w: Plugin ID %q: %v", ErrInvalidProvider, input.PluginID, err)
		}
		if err := module.CheckPath(input.ModulePath); err != nil {
			return nil, nil, fmt.Errorf("%w: plugin %q has invalid Go Module path %q: %v", ErrInvalidProvider, input.PluginID, input.ModulePath, err)
		}
		if input.ModuleVersion != "" {
			if err := module.Check(input.ModulePath, input.ModuleVersion); err != nil {
				return nil, nil, fmt.Errorf("%w: plugin %q has invalid Go Module version %q: %v", ErrInvalidProvider, input.PluginID, input.ModuleVersion, err)
			}
		}
		if err := module.CheckImportPath(input.ImportPath); err != nil {
			return nil, nil, fmt.Errorf("%w: plugin %q has invalid import path %q: %v", ErrInvalidProvider, input.PluginID, input.ImportPath, err)
		}
		pluginName, found := strings.CutPrefix(input.ImportPath, input.ModulePath+"/")
		if !found || pluginName == "" || strings.Contains(pluginName, "/") {
			return nil, nil, fmt.Errorf("%w: plugin %q import path %q is not a direct child of module %q", ErrInvalidProvider, input.PluginID, input.ImportPath, input.ModulePath)
		}
		names, err := configurationgen.DeriveGoNames(pluginName)
		if err != nil {
			return nil, nil, fmt.Errorf("%w: plugin %q import path %q: %v", ErrInvalidProvider, input.PluginID, input.ImportPath, err)
		}
		dependencies, err := planProviderDependencies(input.PluginID, input.Dependencies)
		if err != nil {
			return nil, nil, err
		}
		input.Dependencies = append([]DependencyInput(nil), input.Dependencies...)
		providers[index] = plannedProvider{ProviderInput: input, configurationNames: names, dependencies: dependencies}
	}
	sort.Slice(providers, func(left, right int) bool {
		if providers[left].PluginID != providers[right].PluginID {
			return providers[left].PluginID < providers[right].PluginID
		}
		if providers[left].ModulePath != providers[right].ModulePath {
			return providers[left].ModulePath < providers[right].ModulePath
		}
		if providers[left].ModuleVersion != providers[right].ModuleVersion {
			return providers[left].ModuleVersion < providers[right].ModuleVersion
		}
		return providers[left].ImportPath < providers[right].ImportPath
	})

	pluginIDs := make(map[string]string, len(providers))
	importPaths := make(map[string]string, len(providers))
	configurationSymbols := make(map[string]string, len(providers))
	modulePaths := make(map[string]struct{}, len(providers))
	for _, provider := range providers {
		if previous, duplicate := pluginIDs[provider.PluginID]; duplicate {
			return nil, nil, fmt.Errorf("%w: Plugin ID %q is declared by %s and %s", ErrDuplicateProvider, provider.PluginID, previous, provider.ImportPath)
		}
		pluginIDs[provider.PluginID] = provider.ImportPath
		if previous, duplicate := importPaths[provider.ImportPath]; duplicate {
			return nil, nil, fmt.Errorf("%w: import path %q belongs to plugins %q and %q", ErrDuplicateProvider, provider.ImportPath, previous, provider.PluginID)
		}
		importPaths[provider.ImportPath] = provider.PluginID
		key := provider.ModulePath + "\x00" + provider.configurationNames.DecodeName()
		if previous, collision := configurationSymbols[key]; collision {
			return nil, nil, fmt.Errorf("%w: plugins %q and %q in module %q both use decoder %s", ErrDuplicateProvider, previous, provider.PluginID, provider.ModulePath, provider.configurationNames.DecodeName())
		}
		configurationSymbols[key] = provider.PluginID
		modulePaths[provider.ModulePath] = struct{}{}
	}

	modules := make([]string, 0, len(modulePaths))
	for modulePath := range modulePaths {
		modules = append(modules, modulePath)
	}
	sort.Strings(modules)
	for _, modulePath := range modules {
		configurationPath := path.Join(modulePath, "generated/go/configuration")
		if configurationPath == "github.com/plystra/kernel/configuration" {
			return nil, nil, fmt.Errorf("%w: generated configuration import path %q conflicts with the Kernel", ErrDuplicateProvider, configurationPath)
		}
		if pluginID, collision := importPaths[configurationPath]; collision {
			return nil, nil, fmt.Errorf("%w: generated configuration import path %q conflicts with plugin %q", ErrDuplicateProvider, configurationPath, pluginID)
		}
	}
	configurationAliases := make(map[string]string, len(modules))
	imports := make([]importSpec, 0, len(modules)+len(providers))
	for index, modulePath := range modules {
		alias := fmt.Sprintf("configuration%d", index)
		configurationAliases[modulePath] = alias
		imports = append(imports, importSpec{alias: alias, path: path.Join(modulePath, "generated/go/configuration")})
	}
	for index := range providers {
		if providers[index].ImportPath == "github.com/plystra/kernel/configuration" {
			return nil, nil, fmt.Errorf("%w: plugin %q import path conflicts with the Kernel configuration package", ErrDuplicateProvider, providers[index].PluginID)
		}
		providers[index].pluginAlias = fmt.Sprintf("provider%d", index)
		providers[index].configurationAlias = configurationAliases[providers[index].ModulePath]
		imports = append(imports, importSpec{alias: providers[index].pluginAlias, path: providers[index].ImportPath})
	}
	sort.Slice(imports, func(left, right int) bool { return imports[left].path < imports[right].path })
	return providers, imports, nil
}
