// Code generated by Plystra CLI. DO NOT EDIT.

import { resolveUnaryMethod } from "../../../descriptors.js";
import { createRuntime, type ClientOptions, type Runtime } from "../../../runtime.js";
import {
  bindOperationMethod as bindCanonicalOperationMethod,
  type Operation,
} from "../../../operations/email/send/v1.js";
export type { ErrorCode, Operation, Request, Response } from "../../../operations/email/send/v1.js";

export const capabilityID = "mail.deliver/v1";
export const targetCapabilityID = "email.send/v1";
export const contractDigest = "sha256:d1bb3e79da4ce8fc729c4a21d4ebabd3818436c1aac31d407d68ae96b8319e26";
const method = resolveUnaryMethod(
  "plystra.generated.mail.deliver.v1.MailDeliverV1Service",
  "Invoke",
  "plystra.generated.email.send.v1.EmailSendV1Request",
  "plystra.generated.email.send.v1.EmailSendV1Response",
);

/** @internal */
export function bindOperation(runtime: Runtime): Operation {
  return bindCanonicalOperationMethod(runtime, method, capabilityID);
}

/** @deprecated Use email.send/v1 instead. */
export function createOperation(options: ClientOptions): Operation {
  return bindOperation(createRuntime(options));
}
