// Code generated by Plystra CLI. DO NOT EDIT.

import { createRuntime, type ClientOptions, type Runtime } from "../../../runtime.js";
import {
  bindOperationRoute as bindCanonicalOperationRoute,
  type Operation,
} from "../../../operations/email/send/v1.js";
export type { ErrorCode, Operation, Request, Response } from "../../../operations/email/send/v1.js";

export const capabilityID = "mail.deliver/v1";
export const targetCapabilityID = "email.send/v1";
export const contractDigest = "sha256:836377411dbd56a4b2e7441377ce8e3f093d1e8758677ae44b8062bb69c6a8a5";
const routePath = "api/v1/capabilities/mail.deliver/v1/invoke";

/** @deprecated Use email.send/v1 instead. */
export function bindOperation(runtime: Runtime): Operation {
  return bindCanonicalOperationRoute(runtime, routePath);
}

/** @deprecated Use email.send/v1 instead. */
export function createOperation(options: ClientOptions): Operation {
  return bindOperation(createRuntime(options));
}
