// Code generated by Plystra CLI. DO NOT EDIT.

import { resolveUnaryMethod } from "../../../descriptors.js";
import { createRuntime, type ClientOptions, type Runtime } from "../../../runtime.js";
import {
  bindOperationMethod as bindCanonicalOperationMethod,
  type Operation,
} from "../../../operations/email/send/v1.js";
export type { ErrorCode, Operation, Request, Response } from "../../../operations/email/send/v1.js";

export const capabilityID = "mail.deliver/v1";
export const targetCapabilityID = "email.send/v1";
export const contractDigest = "sha256:836377411dbd56a4b2e7441377ce8e3f093d1e8758677ae44b8062bb69c6a8a5";
const method = resolveUnaryMethod(
  "plystra.generated.mail.deliver.v1.MailDeliverV1Service",
  "Invoke",
  "plystra.generated.email.send.v1.EmailSendV1Request",
  "plystra.generated.email.send.v1.EmailSendV1Response",
);

/** @deprecated Use email.send/v1 instead. */
export function bindOperation(runtime: Runtime): Operation {
  return bindCanonicalOperationMethod(runtime, method);
}

/** @deprecated Use email.send/v1 instead. */
export function createOperation(options: ClientOptions): Operation {
  return bindOperation(createRuntime(options));
}
