// Code generated by Plystra CLI. DO NOT EDIT.

import { createRuntime, type ClientOptions } from "./runtime.js";
import {
  bindOperation as bindAccountProfileGetV2,
  createOperation as createAccountProfileGetV2,
  type Operation as AccountProfileGetV2Operation,
} from "./operations/account/profile/get/v2.js";
import {
  bindOperation as bindAlphaBetaV1CheckV1,
  createOperation as createAlphaBetaV1CheckV1,
  type Operation as AlphaBetaV1CheckV1Operation,
} from "./operations/alpha/beta/v1/check/v1.js";
import {
  bindOperation as bindAlphaBetaV1,
  createOperation as createAlphaBetaV1,
  type Operation as AlphaBetaV1Operation,
} from "./operations/alpha/beta/v1.js";
import {
  bindOperation as bindCompatSendV1,
  createOperation as createCompatSendV1Operation,
  type Operation as CompatSendV1Operation,
} from "./operations/compat/send/v1.js";
import {
  bindOperation as bindEmailSendV1,
  createOperation as createEmailSendV1,
  type Operation as EmailSendV1Operation,
} from "./operations/email/send/v1.js";
import {
  bindOperation as bindFooBarSendV1_666f6f2d6261722e73656e642f7631,
  createOperation as createFooBarSendV1_666f6f2d6261722e73656e642f7631,
  type Operation as FooBarSendV1_666f6f2d6261722e73656e642f7631Operation,
} from "./operations/foo-bar/send/v1.js";
import {
  bindOperation as bindFooBarSendV1_666f6f2e6261722d73656e642f7631,
  createOperation as createFooBarSendV1_666f6f2e6261722d73656e642f7631,
  type Operation as FooBarSendV1_666f6f2e6261722d73656e642f7631Operation,
} from "./operations/foo/bar-send/v1.js";
import {
  bindOperation as bindMailDeliverV1,
  createOperation as createMailDeliverV1Operation,
  type Operation as MailDeliverV1Operation,
} from "./operations/mail/deliver/v1.js";
export type {
  RecordsEchoV1Detail,
  RecordsEchoV1Envelope,
  RecordsEchoV1Request,
  RecordsEchoV1Response,
} from "./interfaces/records/echo/v1.js";

export { PlystraError } from "./runtime.js";
export type { ClientOptions, JSONValue, KernelErrorClass, PlystraErrorDetail, RequestOptions } from "./runtime.js";
export { createAccountProfileGetV2 };
export type {
  ErrorCode as AccountProfileGetV2ErrorCode,
  Request as AccountProfileGetV2Request,
  Response as AccountProfileGetV2Response,
} from "./operations/account/profile/get/v2.js";
export { createAlphaBetaV1CheckV1 };
export type {
  ErrorCode as AlphaBetaV1CheckV1ErrorCode,
  Request as AlphaBetaV1CheckV1Request,
  Response as AlphaBetaV1CheckV1Response,
} from "./operations/alpha/beta/v1/check/v1.js";
export { createAlphaBetaV1 };
export type {
  ErrorCode as AlphaBetaV1ErrorCode,
  Request as AlphaBetaV1Request,
  Response as AlphaBetaV1Response,
} from "./operations/alpha/beta/v1.js";
export const createCompatSendV1 = createCompatSendV1Operation;
export type {
  ErrorCode as CompatSendV1ErrorCode,
  Request as CompatSendV1Request,
  Response as CompatSendV1Response,
} from "./operations/compat/send/v1.js";
export { createEmailSendV1 };
export type {
  ErrorCode as EmailSendV1ErrorCode,
  Request as EmailSendV1Request,
  Response as EmailSendV1Response,
} from "./operations/email/send/v1.js";
export { createFooBarSendV1_666f6f2d6261722e73656e642f7631 };
export type {
  ErrorCode as FooBarSendV1_666f6f2d6261722e73656e642f7631ErrorCode,
  Request as FooBarSendV1_666f6f2d6261722e73656e642f7631Request,
  Response as FooBarSendV1_666f6f2d6261722e73656e642f7631Response,
} from "./operations/foo-bar/send/v1.js";
export { createFooBarSendV1_666f6f2e6261722d73656e642f7631 };
export type {
  ErrorCode as FooBarSendV1_666f6f2e6261722d73656e642f7631ErrorCode,
  Request as FooBarSendV1_666f6f2e6261722d73656e642f7631Request,
  Response as FooBarSendV1_666f6f2e6261722d73656e642f7631Response,
} from "./operations/foo/bar-send/v1.js";
/** @deprecated Use email.send/v1 instead. */
export const createMailDeliverV1 = createMailDeliverV1Operation;
export type {
  ErrorCode as MailDeliverV1ErrorCode,
  Request as MailDeliverV1Request,
  Response as MailDeliverV1Response,
} from "./operations/mail/deliver/v1.js";

export type PlystraClient = {
  readonly "account": {
    readonly "profile": {
      readonly "get": {
        readonly "v2": AccountProfileGetV2Operation;
      };
    };
  };
  readonly "alpha": {
    readonly "beta": {
      readonly "v1": AlphaBetaV1Operation & {
        readonly "check": {
          readonly "v1": AlphaBetaV1CheckV1Operation;
        };
      };
    };
  };
  readonly "compat": {
    readonly "send": {
      readonly "v1": CompatSendV1Operation;
    };
  };
  readonly "email": {
    readonly "send": {
      readonly "v1": EmailSendV1Operation;
    };
  };
  readonly "foo": {
    readonly "bar-send": {
      readonly "v1": FooBarSendV1_666f6f2e6261722d73656e642f7631Operation;
    };
  };
  readonly "foo-bar": {
    readonly "send": {
      readonly "v1": FooBarSendV1_666f6f2d6261722e73656e642f7631Operation;
    };
  };
  readonly "mail": {
    readonly "deliver": {
      /** @deprecated Use email.send/v1 instead. */
      readonly "v1": MailDeliverV1Operation;
    };
  };
};

export function createPlystraClient(options: ClientOptions): PlystraClient {
  const runtime = createRuntime(options);
  return Object.freeze({
    "account": Object.freeze({
      "profile": Object.freeze({
        "get": Object.freeze({
          "v2": bindAccountProfileGetV2(runtime),
        }),
      }),
    }),
    "alpha": Object.freeze({
      "beta": Object.freeze({
        "v1": Object.freeze(Object.assign(bindAlphaBetaV1(runtime), {
          "check": Object.freeze({
            "v1": bindAlphaBetaV1CheckV1(runtime),
          }),
        })),
      }),
    }),
    "compat": Object.freeze({
      "send": Object.freeze({
        "v1": bindCompatSendV1(runtime),
      }),
    }),
    "email": Object.freeze({
      "send": Object.freeze({
        "v1": bindEmailSendV1(runtime),
      }),
    }),
    "foo": Object.freeze({
      "bar-send": Object.freeze({
        "v1": bindFooBarSendV1_666f6f2e6261722d73656e642f7631(runtime),
      }),
    }),
    "foo-bar": Object.freeze({
      "send": Object.freeze({
        "v1": bindFooBarSendV1_666f6f2d6261722e73656e642f7631(runtime),
      }),
    }),
    "mail": Object.freeze({
      "deliver": Object.freeze({
        "v1": bindMailDeliverV1(runtime),
      }),
    }),
  });
}
