// Code generated by Plystra CLI. DO NOT EDIT.

const maximumPayloadBytes = 1_048_576;
const maximumCredentialBytes = 65_536;
const maximumJSONDepth = 64;
const serverErrorCodes = new Set([
  "capability_error",
  "cancelled",
  "conflict",
  "denied",
  "internal",
  "invalid_argument",
  "invalid_request",
  "method_not_allowed",
  "not_found",
  "payload_too_large",
  "result_unknown",
  "timeout",
  "unauthenticated",
  "unavailable",
  "unsupported_media_type",
  "version_incompatible",
]);

export type Awaitable<T> = T | PromiseLike<T>;
export type JSONPrimitive = string | number | boolean | null;
export type JSONValue =
  | JSONPrimitive
  | { readonly [key: string]: JSONValue }
  | readonly JSONValue[];

export interface ClientOptions {
  readonly baseUrl: string | URL;
  readonly getAccessToken?: () => Awaitable<string | null | undefined>;
  readonly fetch?: typeof globalThis.fetch;
}

export interface RequestOptions {
  readonly signal?: AbortSignal;
}

export class PlystraError extends Error {
  readonly status: number;
  readonly code: string;
  readonly detailCode: string | undefined;

  constructor(status: number, code: string, detailCode?: string) {
    super(code);
    this.name = "PlystraError";
    this.status = status;
    this.code = code;
    this.detailCode = detailCode;
  }
}

export interface Runtime {
  readonly baseUrl: URL;
  readonly fetch: typeof globalThis.fetch;
  readonly getAccessToken:
    | (() => Awaitable<string | null | undefined>)
    | undefined;
}

export function createRuntime(options: ClientOptions): Runtime {
  if (options === null || typeof options !== "object") {
    throw new TypeError("Plystra client options must be an object");
  }
  const baseUrl = normalizeBaseUrl(options.baseUrl);
  const fetcher = options.fetch ?? globalThis.fetch;
  if (typeof fetcher !== "function") {
    throw new TypeError("Plystra client requires a Fetch-compatible function");
  }
  if (
    options.getAccessToken !== undefined &&
    typeof options.getAccessToken !== "function"
  ) {
    throw new TypeError("getAccessToken must be a function");
  }
  return Object.freeze({
    baseUrl,
    fetch: (input: RequestInfo | URL, init?: RequestInit) =>
      fetcher(input, init),
    getAccessToken: options.getAccessToken,
  });
}

export async function invoke(
  runtime: Runtime,
  routePath: string,
  request: unknown,
  options: RequestOptions,
): Promise<unknown> {
  if (signalAborted(options.signal)) {
    throw new PlystraError(0, "cancelled");
  }
  let body: string;
  try {
    const encoded = JSON.stringify(request);
    if (encoded === undefined) {
      throw new TypeError("request is not JSON-encodable");
    }
    body = encoded;
  } catch {
    throw new TypeError("request is not JSON-encodable");
  }
  if (new TextEncoder().encode(body).byteLength > maximumPayloadBytes) {
    throw new RangeError("request exceeds the 1 MiB transport limit");
  }

  const headers = new Headers({
    Accept: "application/json",
    "Content-Type": "application/json",
  });
  if (runtime.getAccessToken !== undefined) {
    let token: string | null | undefined;
    try {
      token = await runtime.getAccessToken();
    } catch {
      throw new PlystraError(0, "credential_error");
    }
    if (token !== null && token !== undefined && token !== "") {
      if (
        typeof token !== "string" ||
        token.trim() !== token ||
        /[\u0000-\u001f\u007f]/.test(token) ||
        new TextEncoder().encode(token).byteLength > maximumCredentialBytes
      ) {
        throw new TypeError("getAccessToken returned an invalid credential");
      }
      headers.set("Authorization", "Bearer " + token);
    }
  }

  const init: RequestInit = {
    method: "POST",
    headers,
    body,
    cache: "no-store",
    credentials: "same-origin",
    redirect: "error",
  };
  if (options.signal !== undefined) {
    init.signal = options.signal;
  }

  let response: Response;
  try {
    response = await runtime.fetch(new URL(routePath, runtime.baseUrl), init);
  } catch {
    if (signalAborted(options.signal)) {
      throw new PlystraError(0, "cancelled");
    }
    throw new PlystraError(0, "network_error");
  }
  let payload: unknown;
  let status: number;
  let succeeded: boolean;
  try {
    status = response.status;
    succeeded = response.ok;
    if (!Number.isInteger(status) || status < 100 || status > 599) {
      throw new PlystraError(0, "invalid_response");
    }
    payload = await responseJSON(response, options.signal);
  } catch (error) {
    if (error instanceof PlystraError) {
      throw error;
    }
    if (signalAborted(options.signal)) {
      throw new PlystraError(0, "cancelled");
    }
    throw new PlystraError(0, "invalid_response");
  }
  if (succeeded) {
    if (!isPlainObject(payload)) {
      throw new PlystraError(status, "invalid_response");
    }
    return payload;
  }
  if (!isPlainObject(payload) || !isPlainObject(payload["error"])) {
    throw new PlystraError(status, "invalid_response");
  }
  const error = payload["error"];
  const code = error["code"];
  const detailCode = error["detail_code"];
  if (
    typeof code !== "string" ||
    !serverErrorCodes.has(code) ||
    (detailCode !== undefined &&
      (typeof detailCode !== "string" || !validDetailCode(detailCode)))
  ) {
    throw new PlystraError(status, "invalid_response");
  }
  throw new PlystraError(status, code, detailCode);
}

export function hasOwn(
  value: Readonly<Record<string, unknown>>,
  key: string,
): boolean {
  return Object.prototype.hasOwnProperty.call(value, key);
}

export function isPlainObject(
  value: unknown,
): value is Readonly<Record<string, unknown>> {
  if (value === null || typeof value !== "object" || Array.isArray(value)) {
    return false;
  }
  try {
    const prototype = Object.getPrototypeOf(value);
    return prototype === Object.prototype || prototype === null;
  } catch {
    return false;
  }
}

export function isJSONValue(value: unknown): value is JSONValue {
  return isJSONValueAtDepth(value, 0, new Set<object>());
}

function normalizeBaseUrl(input: string | URL): URL {
  let result: URL;
  try {
    result = new URL(typeof input === "string" ? input : input.href);
  } catch {
    throw new TypeError("baseUrl must be an absolute HTTP or HTTPS URL");
  }
  if (
    (result.protocol !== "http:" && result.protocol !== "https:") ||
    result.username !== "" ||
    result.password !== "" ||
    result.search !== "" ||
    result.hash !== ""
  ) {
    throw new TypeError(
      "baseUrl must be an absolute HTTP or HTTPS URL without credentials, query, or fragment",
    );
  }
  if (!result.pathname.endsWith("/")) {
    result.pathname += "/";
  }
  return result;
}

async function responseJSON(
  response: Response,
  signal: AbortSignal | undefined,
): Promise<unknown> {
  if (!jsonContentType(response.headers.get("Content-Type"))) {
    throw new PlystraError(response.status, "invalid_response");
  }
  const contentLength = response.headers.get("Content-Length");
  if (contentLength !== null) {
    if (!/^(0|[1-9][0-9]*)$/.test(contentLength)) {
      throw new PlystraError(response.status, "invalid_response");
    }
    const length = Number(contentLength);
    if (!Number.isSafeInteger(length) || length > maximumPayloadBytes) {
      throw new PlystraError(response.status, "invalid_response");
    }
  }
  let text: string;
  try {
    text = await response.text();
  } catch {
    if (signalAborted(signal)) {
      throw new PlystraError(0, "cancelled");
    }
    throw new PlystraError(0, "network_error");
  }
  if (new TextEncoder().encode(text).byteLength > maximumPayloadBytes) {
    throw new PlystraError(response.status, "invalid_response");
  }
  try {
    return JSON.parse(text) as unknown;
  } catch {
    throw new PlystraError(response.status, "invalid_response");
  }
}

function jsonContentType(value: string | null): boolean {
  if (value === null) {
    return false;
  }
  return value.split(";", 1)[0]?.trim().toLowerCase() === "application/json";
}

function signalAborted(signal: AbortSignal | undefined): boolean {
  return signal?.aborted === true;
}

function validDetailCode(value: string): boolean {
  return (
    value !== "" &&
    new TextEncoder().encode(value).byteLength <= 128 &&
    value.split(".").every((segment) =>
      /^[a-z][a-z0-9]*(?:_[a-z0-9]+)*$/.test(segment),
    )
  );
}

function isJSONValueAtDepth(
  value: unknown,
  depth: number,
  ancestors: Set<object>,
): value is JSONValue {
  switch (typeof value) {
    case "string":
    case "boolean":
      return true;
    case "number":
      return (
        Number.isFinite(value) &&
        (!Number.isInteger(value) || Number.isSafeInteger(value))
      );
    case "object":
      if (value === null) {
        return true;
      }
      break;
    default:
      return false;
  }
  if (depth >= maximumJSONDepth || ancestors.has(value)) {
    return false;
  }
  ancestors.add(value);
  try {
    if (Array.isArray(value)) {
      return value.every((item) =>
        isJSONValueAtDepth(item, depth + 1, ancestors),
      );
    }
    if (!isPlainObject(value)) {
      return false;
    }
    return Object.values(value).every((item) =>
      isJSONValueAtDepth(item, depth + 1, ancestors),
    );
  } catch {
    return false;
  } finally {
    ancestors.delete(value);
  }
}
