// Code generated by Plystra CLI. DO NOT EDIT.

import {
  fromJson,
  toBinary,
  toJson,
  type DescMessage,
  type DescMethodUnary,
  type JsonValue as ProtobufJSONValue,
  type MessageShape,
} from "@bufbuild/protobuf";
import { Code, ConnectError, type Transport } from "@connectrpc/connect";
import { createConnectTransport } from "@connectrpc/connect-web";

const maximumPayloadBytes = 1_048_576;
const maximumCredentialBytes = 65_536;
const maximumJSONDepth = 64;

export type Awaitable<T> = T | PromiseLike<T>;
export type JSONPrimitive = string | number | boolean | null;
export type JSONValue =
  | JSONPrimitive
  | { readonly [key: string]: JSONValue }
  | readonly JSONValue[];

export interface ClientOptions {
  readonly baseUrl: string | URL;
  /** Returns the raw access token; Plystra adds the Bearer authorization scheme. */
  readonly getAccessToken?: () => Awaitable<string | null | undefined>;
  readonly fetch?: typeof globalThis.fetch;
}

export interface RequestOptions {
  readonly signal?: AbortSignal;
}

export class PlystraError extends Error {
  readonly status: number;
  readonly code: string;
  readonly detailCode: string | undefined;

  constructor(status: number, code: string, detailCode?: string) {
    super(code);
    this.name = "PlystraError";
    this.status = status;
    this.code = code;
    this.detailCode = detailCode;
  }
}

export type FieldKind =
  | "string"
  | "integer"
  | "number"
  | "boolean"
  | "object"
  | "array";

export interface EnumCodec {
  readonly canonical: string | number | boolean;
  readonly protobufName: string;
}

export interface FieldCodec {
  readonly canonicalName: string;
  readonly protobufJSONName: string;
  readonly kind: FieldKind;
  readonly items?: Exclude<FieldKind, "array">;
  readonly required: boolean;
  readonly enum?: readonly EnumCodec[];
}

export interface MessageCodec {
  readonly fields: readonly FieldCodec[];
}

export interface Runtime {
  readonly transport: Transport;
  readonly getAccessToken:
    | (() => Awaitable<string | null | undefined>)
    | undefined;
}

export function createRuntime(options: ClientOptions): Runtime {
  if (options === null || typeof options !== "object") {
    throw new TypeError("Plystra client options must be an object");
  }
  const baseUrl = normalizeBaseUrl(options.baseUrl);
  const fetcher = options.fetch ?? globalThis.fetch;
  if (typeof fetcher !== "function") {
    throw new TypeError("Plystra client requires a Fetch-compatible function");
  }
  if (
    options.getAccessToken !== undefined &&
    typeof options.getAccessToken !== "function"
  ) {
    throw new TypeError("getAccessToken must be a function");
  }
  const transportFetch: typeof globalThis.fetch = (input, init) =>
    fetcher(input, {
      ...init,
      cache: "no-store",
      credentials: "same-origin",
      redirect: "error",
    });
  return Object.freeze({
    transport: createConnectTransport({
      baseUrl: connectBaseUrl(baseUrl),
      useBinaryFormat: true,
      fetch: transportFetch,
    }),
    getAccessToken: options.getAccessToken,
  });
}

export async function invoke(
  runtime: Runtime,
  method: DescMethodUnary,
  requestCodec: MessageCodec,
  responseCodec: MessageCodec,
  request: unknown,
  options: RequestOptions,
): Promise<unknown> {
  if (signalAborted(options.signal)) {
    throw new PlystraError(0, "cancelled");
  }

  let requestMessage: MessageShape<typeof method.input>;
  try {
    requestMessage = encodeMessage(method.input, requestCodec, request);
    if (toBinary(method.input, requestMessage).byteLength > maximumPayloadBytes) {
      throw new RangeError("request exceeds the 1 MiB transport limit");
    }
  } catch (error) {
    if (error instanceof RangeError) {
      throw error;
    }
    throw new TypeError("request cannot be encoded for the generated Connect contract");
  }

  const headers = new Headers();
  if (runtime.getAccessToken !== undefined) {
    let token: string | null | undefined;
    try {
      token = await runtime.getAccessToken();
    } catch {
      throw new PlystraError(0, "credential_error");
    }
    if (token !== null && token !== undefined && token !== "") {
      if (
        typeof token !== "string" ||
        token.trim() !== token ||
        /[\u0000-\u001f\u007f]/.test(token) ||
        new TextEncoder().encode(token).byteLength > maximumCredentialBytes
      ) {
        throw new TypeError("getAccessToken returned an invalid credential");
      }
      if (/^Bearer(?: |$)/i.test(token)) {
        throw new TypeError(
          "getAccessToken must return the raw token without the Bearer scheme",
        );
      }
      headers.set("Authorization", "Bearer " + token);
    }
  }

  let responseMessage: MessageShape<typeof method.output>;
  try {
    const response = await runtime.transport.unary(
      method,
      options.signal,
      undefined,
      headers,
      requestMessage,
    );
    responseMessage = response.message;
  } catch (error) {
    if (signalAborted(options.signal)) {
      throw new PlystraError(0, "cancelled");
    }
    throw normalizeTransportError(error);
  }

  try {
    return decodeMessage(method.output, responseCodec, responseMessage);
  } catch {
    throw new PlystraError(200, "invalid_response");
  }
}

export function hasOwn(
  value: Readonly<Record<string, unknown>>,
  key: string,
): boolean {
  return Object.prototype.hasOwnProperty.call(value, key);
}

export function isPlainObject(
  value: unknown,
): value is Readonly<Record<string, unknown>> {
  if (value === null || typeof value !== "object" || Array.isArray(value)) {
    return false;
  }
  try {
    const prototype = Object.getPrototypeOf(value);
    return prototype === Object.prototype || prototype === null;
  } catch {
    return false;
  }
}

export function isJSONValue(value: unknown): value is JSONValue {
  return isJSONValueAtDepth(value, 0, new Set<object>());
}

function encodeMessage<Desc extends DescMessage>(
  descriptor: Desc,
  codec: MessageCodec,
  value: unknown,
): MessageShape<Desc> {
  if (!isPlainObject(value)) {
    throw new TypeError("request must be an object");
  }
  const json: { [key: string]: ProtobufJSONValue } = {};
  for (const field of codec.fields) {
    if (!hasOwn(value, field.canonicalName)) {
      if (field.required) {
        throw new TypeError("required request field is absent");
      }
      continue;
    }
    json[field.protobufJSONName] = encodeField(field, value[field.canonicalName]);
  }
  return fromJson(descriptor, json, {
    ignoreUnknownFields: false,
    recursionLimit: maximumJSONDepth,
  });
}

function encodeField(field: FieldCodec, value: unknown): ProtobufJSONValue {
  if (field.enum !== undefined) {
    const member = field.enum.find((candidate) =>
      Object.is(candidate.canonical, value),
    );
    if (member === undefined) {
      throw new TypeError("request enum is invalid");
    }
    return member.protobufName;
  }
  switch (field.kind) {
    case "string":
      if (typeof value !== "string") throw new TypeError("request string is invalid");
      return value;
    case "integer":
      if (typeof value !== "number" || !Number.isSafeInteger(value)) {
        throw new TypeError("request integer is invalid");
      }
      return String(value);
    case "number":
      if (typeof value !== "number" || !Number.isFinite(value)) {
        throw new TypeError("request number is invalid");
      }
      return value;
    case "boolean":
      if (typeof value !== "boolean") throw new TypeError("request boolean is invalid");
      return value;
    case "object":
      if (!isPlainObject(value) || !isJSONValue(value)) {
        throw new TypeError("request object is invalid");
      }
      return cloneJSONValue(value);
    case "array":
      if (!Array.isArray(value) || field.items === undefined) {
        throw new TypeError("request array is invalid");
      }
      const itemKind = field.items;
      return {
        values: value.map((item) => encodeArrayItem(itemKind, item)),
      };
  }
}

function encodeArrayItem(
  kind: Exclude<FieldKind, "array">,
  value: unknown,
): ProtobufJSONValue {
  switch (kind) {
    case "string":
      if (typeof value !== "string") throw new TypeError("request array item is invalid");
      return value;
    case "integer":
      if (typeof value !== "number" || !Number.isSafeInteger(value)) {
        throw new TypeError("request array item is invalid");
      }
      return String(value);
    case "number":
      if (typeof value !== "number" || !Number.isFinite(value)) {
        throw new TypeError("request array item is invalid");
      }
      return value;
    case "boolean":
      if (typeof value !== "boolean") throw new TypeError("request array item is invalid");
      return value;
    case "object":
      if (!isPlainObject(value) || !isJSONValue(value)) {
        throw new TypeError("request array item is invalid");
      }
      return cloneJSONValue(value);
  }
}

function decodeMessage<Desc extends DescMessage>(
  descriptor: Desc,
  codec: MessageCodec,
  message: MessageShape<Desc>,
): unknown {
  const json = toJson(descriptor, message, {
    alwaysEmitImplicit: true,
    enumAsInteger: false,
    useProtoFieldName: false,
  });
  if (!isPlainObject(json)) {
    throw new TypeError("response is not an object");
  }
  const known = new Set(codec.fields.map((field) => field.protobufJSONName));
  if (!Object.keys(json).every((key) => known.has(key))) {
    throw new TypeError("response contains an unknown field");
  }
  const result: Record<string, unknown> = {};
  for (const field of codec.fields) {
    if (!hasOwn(json, field.protobufJSONName)) {
      if (field.required) {
        throw new TypeError("required response field is absent");
      }
      continue;
    }
    result[field.canonicalName] = decodeField(
      field,
      json[field.protobufJSONName],
    );
  }
  return result;
}

function decodeField(field: FieldCodec, value: unknown): unknown {
  if (field.enum !== undefined) {
    if (typeof value !== "string") {
      throw new TypeError("response enum is invalid");
    }
    const member = field.enum.find(
      (candidate) => candidate.protobufName === value,
    );
    if (member === undefined) {
      throw new TypeError("response enum is unknown");
    }
    return member.canonical;
  }
  switch (field.kind) {
    case "string":
      if (typeof value !== "string") throw new TypeError("response string is invalid");
      return value;
    case "integer":
      return decodeInteger(value);
    case "number":
      if (typeof value !== "number" || !Number.isFinite(value)) {
        throw new TypeError("response number is invalid");
      }
      return value;
    case "boolean":
      if (typeof value !== "boolean") throw new TypeError("response boolean is invalid");
      return value;
    case "object":
      if (!isPlainObject(value) || !isJSONValue(value)) {
        throw new TypeError("response object is invalid");
      }
      return cloneJSONValue(value);
    case "array": {
      if (!isPlainObject(value) || field.items === undefined) {
        throw new TypeError("response array wrapper is invalid");
      }
      const itemKind = field.items;
      const values = value["values"];
      if (
        Object.keys(value).some((key) => key !== "values") ||
        !Array.isArray(values)
      ) {
        throw new TypeError("response array wrapper is invalid");
      }
      return values.map((item) => decodeArrayItem(itemKind, item));
    }
  }
}

function decodeArrayItem(
  kind: Exclude<FieldKind, "array">,
  value: unknown,
): unknown {
  switch (kind) {
    case "string":
      if (typeof value !== "string") throw new TypeError("response array item is invalid");
      return value;
    case "integer":
      return decodeInteger(value);
    case "number":
      if (typeof value !== "number" || !Number.isFinite(value)) {
        throw new TypeError("response array item is invalid");
      }
      return value;
    case "boolean":
      if (typeof value !== "boolean") throw new TypeError("response array item is invalid");
      return value;
    case "object":
      if (!isPlainObject(value) || !isJSONValue(value)) {
        throw new TypeError("response array item is invalid");
      }
      return cloneJSONValue(value);
  }
}

function decodeInteger(value: unknown): number {
  let decoded: number;
  if (typeof value === "string" && /^-?(?:0|[1-9][0-9]*)$/.test(value)) {
    decoded = Number(value);
  } else if (typeof value === "number") {
    decoded = value;
  } else {
    throw new TypeError("response integer is invalid");
  }
  if (!Number.isSafeInteger(decoded)) {
    throw new TypeError("response integer is outside the safe range");
  }
  return decoded;
}

function normalizeBaseUrl(input: string | URL): URL {
  let result: URL;
  try {
    result = new URL(typeof input === "string" ? input : input.href);
  } catch {
    throw new TypeError("baseUrl must be an absolute HTTP or HTTPS URL");
  }
  if (
    (result.protocol !== "http:" && result.protocol !== "https:") ||
    result.username !== "" ||
    result.password !== "" ||
    result.search !== "" ||
    result.hash !== ""
  ) {
    throw new TypeError(
      "baseUrl must be an absolute HTTP or HTTPS URL without credentials, query, or fragment",
    );
  }
  if (!result.pathname.endsWith("/")) {
    result.pathname += "/";
  }
  return result;
}

function connectBaseUrl(value: URL): string {
  return value.href.endsWith("/") ? value.href.slice(0, -1) : value.href;
}

function normalizeTransportError(error: unknown): PlystraError {
  if (!(error instanceof ConnectError)) {
    return new PlystraError(0, "network_error");
  }
  switch (error.code) {
    case Code.Canceled:
      return new PlystraError(0, "cancelled");
    case Code.Unknown:
      return new PlystraError(0, "network_error");
    case Code.InvalidArgument:
    case Code.OutOfRange:
      return new PlystraError(400, "invalid_argument");
    case Code.DeadlineExceeded:
      return new PlystraError(504, "timeout");
    case Code.NotFound:
      return new PlystraError(404, "not_found");
    case Code.AlreadyExists:
    case Code.Aborted:
      return new PlystraError(409, "conflict");
    case Code.PermissionDenied:
      return new PlystraError(403, "denied");
    case Code.ResourceExhausted:
      return new PlystraError(429, "unavailable");
    case Code.FailedPrecondition:
      return new PlystraError(422, "capability_error");
    case Code.Unimplemented:
      return new PlystraError(501, "version_incompatible");
    case Code.Internal:
    case Code.DataLoss:
      return new PlystraError(500, "internal");
    case Code.Unavailable:
      return new PlystraError(503, "unavailable");
    case Code.Unauthenticated:
      return new PlystraError(401, "unauthenticated");
  }
}

function signalAborted(signal: AbortSignal | undefined): boolean {
  return signal?.aborted === true;
}

function cloneJSONValue(value: JSONValue): ProtobufJSONValue {
  if (
    value === null ||
    typeof value === "string" ||
    typeof value === "number" ||
    typeof value === "boolean"
  ) {
    return value;
  }
  if (Array.isArray(value)) {
    return value.map((item) => cloneJSONValue(item));
  }
  const result: { [key: string]: ProtobufJSONValue } = {};
  for (const [key, item] of Object.entries(value)) {
    result[key] = cloneJSONValue(item);
  }
  return result;
}

function isJSONValueAtDepth(
  value: unknown,
  depth: number,
  ancestors: Set<object>,
): value is JSONValue {
  switch (typeof value) {
    case "string":
    case "boolean":
      return true;
    case "number":
      return (
        Number.isFinite(value) &&
        (!Number.isInteger(value) || Number.isSafeInteger(value))
      );
    case "object":
      if (value === null) {
        return true;
      }
      break;
    default:
      return false;
  }
  if (depth >= maximumJSONDepth || ancestors.has(value)) {
    return false;
  }
  ancestors.add(value);
  try {
    if (Array.isArray(value)) {
      return value.every((item) =>
        isJSONValueAtDepth(item, depth + 1, ancestors),
      );
    }
    if (!isPlainObject(value)) {
      return false;
    }
    return Object.values(value).every((item) =>
      isJSONValueAtDepth(item, depth + 1, ancestors),
    );
  } catch {
    return false;
  } finally {
    ancestors.delete(value);
  }
}
