package protobufdescriptor_test

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"slices"
	"strings"
	"testing"

	generation "github.com/plystra/cli/generation/v1"
	"github.com/plystra/cli/internal/capabilitymeta"
	"github.com/plystra/cli/internal/protobufdescriptor"
	"github.com/plystra/cli/internal/protobufmodel"
	"github.com/plystra/cli/internal/protobufwiremap"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protodesc"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/types/descriptorpb"
)

const descriptorContract = `id: customer.profile.get/v1
request:
  active: {type: boolean}
  metadata: {type: object}
  profile_id: {type: string, required: true}
  revision: {type: integer}
  score: {type: number}
  status: {type: string, enum: [active, suspended]}
  tags: {type: array, items: string}
response:
  found: {type: boolean, required: true}
  profile: {type: object}
errors: [profile_missing]
`

func TestBuildRendersDeterministicSchemasAndSelfContainedDescriptors(t *testing.T) {
	t.Parallel()

	target := descriptorTarget(t, descriptorContract)
	alias := descriptorAlias(t, "account.profile/v1", target)
	model := descriptorModel(t, []descriptorTargetView{target}, []descriptorAliasView{alias})
	wireMap := descriptorWireMap(t, model, nil, false, "")

	evidence, err := protobufdescriptor.Build(model, wireMap)
	if err != nil || !evidence.Valid() || evidence.DescriptorCount() != 2 {
		t.Fatalf("Build = %#v, %v", evidence, err)
	}
	files := evidence.Files()
	paths := descriptorPaths(files)
	wantPaths := []string{
		"generated/proto/descriptor-set.pb",
		"generated/proto/plystra/generated/account/profile/v1/capability.proto",
		"generated/proto/plystra/generated/customer/profile/get/v1/capability.proto",
	}
	if !slices.Equal(paths, wantPaths) {
		t.Fatalf("paths = %v, want %v", paths, wantPaths)
	}
	if evidence.Digest() != descriptorDigest(files[0].Data()) {
		t.Fatalf("Digest = %q, want %q", evidence.Digest(), descriptorDigest(files[0].Data()))
	}
	descriptorSet := evidence.DescriptorSet()
	if !bytes.Equal(descriptorSet, files[0].Data()) {
		t.Fatal("DescriptorSet does not return the generated binary descriptor evidence")
	}
	descriptorSet[0] ^= 0xff
	if bytes.Equal(descriptorSet, evidence.DescriptorSet()) {
		t.Fatal("DescriptorSet exposed mutable descriptor storage")
	}

	set := decodeDescriptorSet(t, files[0].Data())
	if len(set.File) != 3 {
		t.Fatalf("descriptor file count = %d, want canonical, Alias, and Struct dependency", len(set.File))
	}
	if _, err := protodesc.NewFiles(set); err != nil {
		t.Fatalf("protodesc.NewFiles: %v", err)
	}
	canonical := descriptorFile(t, set, "plystra/generated/customer/profile/get/v1/capability.proto")
	request := descriptorMessage(t, canonical, "CustomerProfileGetV1Request")
	if got := request.Fields().ByName("active"); got == nil || got.Kind() != protoreflect.BoolKind || !got.HasPresence() {
		t.Fatalf("active descriptor = %#v", got)
	}
	if got := request.Fields().ByName("revision"); got == nil || got.Kind() != protoreflect.Sint64Kind || !got.HasPresence() {
		t.Fatalf("revision descriptor = %#v", got)
	}
	if got := request.Fields().ByName("score"); got == nil || got.Kind() != protoreflect.DoubleKind || !got.HasPresence() {
		t.Fatalf("score descriptor = %#v", got)
	}
	if got := request.Fields().ByName("metadata"); got == nil || got.Message() == nil || got.Message().FullName() != "google.protobuf.Struct" {
		t.Fatalf("metadata descriptor = %#v", got)
	}
	if got := request.Fields().ByName("tags"); got == nil || got.Message() == nil || got.Message().Fields().ByName("values") == nil || !got.Message().Fields().ByName("values").IsList() {
		t.Fatalf("tags descriptor = %#v", got)
	}
	status := request.Fields().ByName("status")
	if status == nil || status.Enum() == nil || status.Enum().Values().Len() != 3 || status.Enum().Values().Get(0).Number() != 0 || status.Enum().Values().Get(0).Name() != "CUSTOMERPROFILEGETV1REQUESTSTATUSENUM_UNSPECIFIED" {
		t.Fatalf("status descriptor = %#v", status)
	}
	service := canonical.Services().ByName("CustomerProfileGetV1Service")
	if service == nil || service.Methods().Len() != 1 || service.Methods().Get(0).Input().FullName() != request.FullName() {
		t.Fatalf("canonical service = %#v", service)
	}
	aliasFile := descriptorFile(t, set, "plystra/generated/account/profile/v1/capability.proto")
	aliasService := aliasFile.Services().ByName("AccountProfileV1Service")
	if aliasService == nil || aliasService.Methods().Get(0).Input().FullName() != request.FullName() || aliasService.Methods().Get(0).Output().FullName() != "plystra.generated.customer.profile.get.v1.CustomerProfileGetV1Response" {
		t.Fatalf("Alias service = %#v", aliasService)
	}

	canonicalSource := string(files[2].Data())
	for _, required := range []string{
		"// Code generated by Plystra CLI. DO NOT EDIT.",
		"// Descriptor schema: " + protobufdescriptor.ProjectionSchema,
		`import "google/protobuf/struct.proto";`,
		"enum CustomerProfileGetV1RequestStatusEnum {",
		"optional string profile_id = 3 [json_name = \"profileId\"];",
		"message CustomerProfileGetV1RequestTagsList {",
		"repeated string values = 1 [json_name = \"values\"];",
		"rpc Invoke(.plystra.generated.customer.profile.get.v1.CustomerProfileGetV1Request) returns (.plystra.generated.customer.profile.get.v1.CustomerProfileGetV1Response);",
	} {
		if !strings.Contains(canonicalSource, required) {
			t.Fatalf("canonical source omits %q:\n%s", required, canonicalSource)
		}
	}
	for _, forbidden := range []string{"provider", "plugin", "module_path", "secret"} {
		if strings.Contains(strings.ToLower(canonicalSource), forbidden) || bytes.Contains(bytes.ToLower(files[0].Data()), []byte(forbidden)) {
			t.Fatalf("descriptor evidence contains forbidden %q", forbidden)
		}
	}

	repeated, err := protobufdescriptor.Build(model, wireMap)
	if err != nil || repeated.Digest() != evidence.Digest() || !descriptorFilesEqual(repeated.Files(), files) {
		t.Fatalf("repeated Build drifted: %#v, %v", repeated, err)
	}
	files[0] = protobufdescriptor.File{}
	mutated := evidence.Files()
	data := mutated[0].Data()
	if len(data) != 0 {
		data[0] ^= 0xff
	}
	if evidence.Files()[0].Path() != protobufdescriptor.DescriptorSetPath || evidence.Digest() != descriptorDigest(evidence.Files()[0].Data()) {
		t.Fatal("Evidence exposed mutable file storage")
	}
}

func TestBuildPreservesFieldAndEnumReservationsInDescriptorEvidence(t *testing.T) {
	t.Parallel()

	initialTarget := descriptorTarget(t, `id: records.read/v1
request:
  legacy_id: {type: string}
  status: {type: string, enum: [active, retired]}
response: {}
`)
	initialModel := descriptorModel(t, []descriptorTargetView{initialTarget}, nil)
	initialMap := descriptorWireMap(t, initialModel, nil, false, "")
	updatedTarget := descriptorTarget(t, `id: records.read/v1
request:
  status: {type: string, enum: [active]}
response: {}
`)
	updatedModel := descriptorModel(t, []descriptorTargetView{updatedTarget}, nil)
	updatedMap := descriptorWireMap(t, updatedModel, initialMap.CanonicalJSON(), true, initialMap.Digest())

	evidence, err := protobufdescriptor.Build(updatedModel, updatedMap)
	if err != nil {
		t.Fatalf("Build: %v", err)
	}
	files := evidence.Files()
	set := decodeDescriptorSet(t, files[0].Data())
	file := descriptorFile(t, set, "plystra/generated/records/read/v1/capability.proto")
	request := descriptorMessage(t, file, "RecordsReadV1Request")
	if request.ReservedNames().Len() != 1 || request.ReservedNames().Get(0) != "legacy_id" || request.ReservedRanges().Len() != 1 {
		t.Fatalf("message reservations = names %v ranges %v", request.ReservedNames(), request.ReservedRanges())
	}
	status := request.Fields().ByName("status").Enum()
	reservedEnumName := updatedMap.ActiveCapabilities()[0].Request().Enums()[0].ReservedNames()[0]
	if status.ReservedNames().Len() != 1 || status.ReservedNames().Get(0) != protoreflect.Name(reservedEnumName) || status.ReservedRanges().Len() != 1 {
		t.Fatalf("enum reservations = names %v ranges %v", status.ReservedNames(), status.ReservedRanges())
	}
	source := string(files[1].Data())
	for _, required := range []string{`reserved "` + reservedEnumName + `";`, `reserved "legacy_id";`} {
		if !strings.Contains(source, required) {
			t.Fatalf("source omits %q:\n%s", required, source)
		}
	}
}

func TestBuildEmitsOneDeterministicEmptyDescriptorSetWithoutConnectSurface(t *testing.T) {
	t.Parallel()

	model, err := protobufmodel.Build(false, []protobufmodel.CanonicalTargetView{nil}, []protobufmodel.AliasView{nil})
	if err != nil {
		t.Fatalf("protobufmodel.Build: %v", err)
	}
	wireMap := descriptorWireMap(t, model, nil, false, "")
	evidence, err := protobufdescriptor.Build(model, wireMap)
	if err != nil || !evidence.Valid() || evidence.DescriptorCount() != 0 {
		t.Fatalf("Build = %#v, %v", evidence, err)
	}
	files := evidence.Files()
	if len(files) != 1 || files[0].Path() != protobufdescriptor.DescriptorSetPath || len(files[0].Data()) != 0 {
		t.Fatalf("empty files = %#v", files)
	}
	if set := decodeDescriptorSet(t, files[0].Data()); len(set.File) != 0 {
		t.Fatalf("empty descriptor set = %#v", set)
	}
}

func TestBuildIsInputOrderIndependentAcrossCapabilitiesAndAliases(t *testing.T) {
	t.Parallel()

	profile := descriptorTarget(t, descriptorContract)
	order := descriptorTarget(t, `id: order.submit/v1
request:
  order_id: {type: string, required: true}
response:
  accepted: {type: boolean, required: true}
`)
	profileAlias := descriptorAlias(t, "account.profile/v1", profile)
	orderAlias := descriptorAlias(t, "checkout.submit/v1", order)
	firstModel := descriptorModel(t, []descriptorTargetView{profile, order}, []descriptorAliasView{profileAlias, orderAlias})
	secondModel := descriptorModel(t, []descriptorTargetView{order, profile}, []descriptorAliasView{orderAlias, profileAlias})
	firstMap := descriptorWireMap(t, firstModel, nil, false, "")
	secondMap := descriptorWireMap(t, secondModel, nil, false, "")

	first, err := protobufdescriptor.Build(firstModel, firstMap)
	if err != nil {
		t.Fatalf("Build(first): %v", err)
	}
	second, err := protobufdescriptor.Build(secondModel, secondMap)
	if err != nil {
		t.Fatalf("Build(second): %v", err)
	}
	if first.Digest() != second.Digest() || !descriptorFilesEqual(first.Files(), second.Files()) {
		t.Fatalf("input order changed descriptor evidence:\nfirst:  %v %s\nsecond: %v %s", descriptorPaths(first.Files()), first.Digest(), descriptorPaths(second.Files()), second.Digest())
	}
}

func TestBuildRejectsProjectionAndWireMapDisagreement(t *testing.T) {
	t.Parallel()

	first := descriptorModel(t, []descriptorTargetView{descriptorTarget(t, "id: records.read/v1\n")}, nil)
	second := descriptorModel(t, []descriptorTargetView{descriptorTarget(t, "id: records.write/v1\n")}, nil)
	wireMap := descriptorWireMap(t, first, nil, false, "")
	evidence, err := protobufdescriptor.Build(second, wireMap)
	if !errors.Is(err, protobufdescriptor.ErrBuild) || !errors.Is(err, protobufdescriptor.ErrProjection) || evidence.Valid() || !strings.Contains(err.Error(), "does not match") {
		t.Fatalf("Build = %#v, %v", evidence, err)
	}
}

type descriptorTargetView struct {
	id       generation.CapabilityID
	contract []byte
	digest   string
	sources  []string
	exposure generation.Exposure
}

func (v descriptorTargetView) ID() generation.CapabilityID   { return v.id }
func (v descriptorTargetView) ContractJSON() []byte          { return append([]byte(nil), v.contract...) }
func (v descriptorTargetView) ContractDigest() string        { return v.digest }
func (v descriptorTargetView) Sources() []string             { return append([]string(nil), v.sources...) }
func (v descriptorTargetView) Exposure() generation.Exposure { return v.exposure }

type descriptorAliasView struct {
	id       generation.CapabilityID
	target   generation.CapabilityID
	digest   string
	exposure generation.Exposure
}

func (v descriptorAliasView) ID() generation.CapabilityID     { return v.id }
func (v descriptorAliasView) Target() generation.CapabilityID { return v.target }
func (v descriptorAliasView) TargetContractDigest() string    { return v.digest }
func (v descriptorAliasView) Exposure() generation.Exposure   { return v.exposure }
func (descriptorAliasView) Deprecated() string                { return "" }

func descriptorTarget(t testing.TB, source string) descriptorTargetView {
	t.Helper()
	canonical, err := capabilitymeta.NormalizeSchema([]byte(source))
	if err != nil {
		t.Fatalf("NormalizeSchema: %v", err)
	}
	var identity struct {
		ID string `json:"id"`
	}
	if err := json.Unmarshal(canonical, &identity); err != nil {
		t.Fatalf("decode identity: %v", err)
	}
	id, err := generation.ParseCapabilityID(identity.ID)
	if err != nil {
		t.Fatalf("ParseCapabilityID: %v", err)
	}
	return descriptorTargetView{
		id:       id,
		contract: canonical,
		digest:   descriptorDigest(canonical),
		sources:  []string{"example.com/contracts@v1/" + id.String() + "/capability.yaml"},
		exposure: generation.Exposure{Go: true, HTTP: true, JavaScript: true},
	}
}

func descriptorAlias(t testing.TB, id string, target descriptorTargetView) descriptorAliasView {
	t.Helper()
	parsed, err := generation.ParseCapabilityID(id)
	if err != nil {
		t.Fatalf("ParseCapabilityID(Alias): %v", err)
	}
	return descriptorAliasView{id: parsed, target: target.id, digest: target.digest, exposure: generation.Exposure{HTTP: true, JavaScript: true}}
}

func descriptorModel(t testing.TB, targets []descriptorTargetView, aliases []descriptorAliasView) protobufmodel.Model {
	t.Helper()
	targetViews := make([]protobufmodel.CanonicalTargetView, len(targets))
	for index := range targets {
		targetViews[index] = targets[index]
	}
	aliasViews := make([]protobufmodel.AliasView, len(aliases))
	for index := range aliases {
		aliasViews[index] = aliases[index]
	}
	model, err := protobufmodel.Build(true, targetViews, aliasViews)
	if err != nil {
		t.Fatalf("protobufmodel.Build: %v", err)
	}
	return model
}

func descriptorWireMap(t testing.TB, model protobufmodel.Model, previous []byte, previousExists bool, previousDigest string) protobufwiremap.Map {
	t.Helper()
	wireMap, err := protobufwiremap.Build(model, previous, previousExists, previousDigest)
	if err != nil {
		t.Fatalf("protobufwiremap.Build: %v", err)
	}
	return wireMap
}

func descriptorPaths(files []protobufdescriptor.File) []string {
	result := make([]string, len(files))
	for index, file := range files {
		result[index] = file.Path()
	}
	return result
}

func descriptorFilesEqual(left, right []protobufdescriptor.File) bool {
	if len(left) != len(right) {
		return false
	}
	for index := range left {
		if left[index].Path() != right[index].Path() || !bytes.Equal(left[index].Data(), right[index].Data()) {
			return false
		}
	}
	return true
}

func decodeDescriptorSet(t testing.TB, data []byte) *descriptorpb.FileDescriptorSet {
	t.Helper()
	set := &descriptorpb.FileDescriptorSet{}
	if err := proto.Unmarshal(data, set); err != nil {
		t.Fatalf("proto.Unmarshal descriptor set: %v", err)
	}
	return set
}

func descriptorFile(t testing.TB, set *descriptorpb.FileDescriptorSet, name string) protoreflect.FileDescriptor {
	t.Helper()
	files, err := protodesc.NewFiles(set)
	if err != nil {
		t.Fatalf("protodesc.NewFiles: %v", err)
	}
	file, err := files.FindFileByPath(name)
	if err != nil {
		t.Fatalf("FindFileByPath(%s): %v", name, err)
	}
	return file
}

func descriptorMessage(t testing.TB, file protoreflect.FileDescriptor, name protoreflect.Name) protoreflect.MessageDescriptor {
	t.Helper()
	message := file.Messages().ByName(name)
	if message == nil {
		t.Fatalf("message %s is absent from %s", name, file.Path())
	}
	return message
}

func descriptorDigest(data []byte) string {
	sum := sha256.Sum256(data)
	return "sha256:" + hex.EncodeToString(sum[:])
}
