package connectgen

import (
	"encoding/json"
	"fmt"
	"go/format"
	"path"
	"sort"
	"strconv"
	"strings"
	"unicode/utf8"

	"github.com/plystra/cli/internal/applicationmeta"
	"github.com/plystra/cli/internal/capabilityid"
	"github.com/plystra/cli/internal/goname"
	"github.com/plystra/cli/internal/protobufdescriptor"
	"github.com/plystra/cli/internal/protobufmodel"
	"github.com/plystra/cli/internal/protobufwiremap"
	"github.com/plystra/cli/internal/sdkmodel"
	"google.golang.org/protobuf/reflect/protoreflect"
)

func renderCanonical(
	modulePath string,
	operation protobufmodel.Operation,
	aliases []protobufmodel.Alias,
	wire protobufwiremap.CapabilityProjection,
	method protoreflect.MethodDescriptor,
	errorDetail protoreflect.MessageDescriptor,
	useHTTPPath bool,
	cors *applicationmeta.HTTPCORS,
) (File, error) {
	identity := operation.Identity()
	if method == nil || methodName(method) == "" || methodName(method) != identity.Package()+"."+identity.Service()+"."+identity.Method() {
		return File{}, fmt.Errorf("%w: canonical method descriptor is inconsistent", ErrDescriptor)
	}
	if wire.ID() != operation.ID().String() || wire.ContractDigest() != operation.ContractDigest() {
		return File{}, fmt.Errorf("%w: canonical wire projection is inconsistent", ErrProjection)
	}
	if errorDetail == nil || string(errorDetail.FullName()) != protobufdescriptor.ErrorDetailFullName {
		return File{}, fmt.Errorf("%w: safe error detail descriptor is inconsistent", ErrDescriptor)
	}
	requestedCapabilityIDs := []string{operation.ID().String()}
	for _, alias := range aliases {
		if alias.Target() != operation.ID() || alias.TargetContractDigest() != operation.ContractDigest() {
			return File{}, fmt.Errorf("%w: Alias %s is not an exact target of %s", ErrProjection, alias.ID(), operation.ID())
		}
		requestedCapabilityIDs = append(requestedCapabilityIDs, alias.ID().String())
	}
	sort.Strings(requestedCapabilityIDs)
	for index := 1; index < len(requestedCapabilityIDs); index++ {
		if requestedCapabilityIDs[index-1] == requestedCapabilityIDs[index] {
			return File{}, fmt.Errorf("%w: requested Capability ID %s is duplicated", ErrProjection, requestedCapabilityIDs[index])
		}
	}
	request, err := prepareFields("Request", operation.Request(), wire.Request())
	if err != nil {
		return File{}, err
	}
	response, err := prepareFields("Response", operation.Response(), wire.Response())
	if err != nil {
		return File{}, err
	}
	directory, err := generatedDirectory(operation.ID())
	if err != nil {
		return File{}, err
	}
	parsedID, err := capabilityid.Parse(operation.ID().String())
	if err != nil {
		return File{}, fmt.Errorf("%w: Capability %s has no generated Go package", ErrProjection, operation.ID())
	}
	packageName := goname.Package(parsedID)
	contractImport := path.Join(modulePath, generatedCapabilityDirectory("contracts", parsedID))
	invocationImport := path.Join(modulePath, generatedCapabilityDirectory("invocation", parsedID))

	var source strings.Builder
	fmt.Fprintln(&source, "// Code generated by Plystra CLI. DO NOT EDIT.")
	fmt.Fprintln(&source)
	fmt.Fprintf(&source, "package %s\n\n", packageName)
	fmt.Fprintln(&source, "import (")
	fmt.Fprintln(&source, "\t\"context\"")
	fmt.Fprintln(&source, "\t\"errors\"")
	fmt.Fprintln(&source, "\t\"mime\"")
	if cors != nil {
		fmt.Fprintln(&source, "\t\"net\"")
	}
	fmt.Fprintln(&source, "\t\"net/http\"")
	if cors != nil {
		fmt.Fprintln(&source, "\t\"net/url\"")
		fmt.Fprintln(&source, "\t\"strconv\"")
	}
	if useHTTPPath || cors != nil {
		fmt.Fprintln(&source, "\t\"strings\"")
	}
	fmt.Fprintln(&source)
	fmt.Fprintln(&source, "\t\"connectrpc.com/connect\"")
	fmt.Fprintf(&source, "\tcontract %s\n", strconv.Quote(contractImport))
	fmt.Fprintf(&source, "\tapplicationinvocation %s\n", strconv.Quote(invocationImport))
	fmt.Fprintf(&source, "\tconnectschema %s\n", strconv.Quote(runtimeSchemaImport(modulePath)))
	fmt.Fprintln(&source, "\t\"google.golang.org/protobuf/reflect/protoreflect\"")
	fmt.Fprintln(&source, "\t\"google.golang.org/protobuf/types/dynamicpb\"")
	fmt.Fprintln(&source, ")")
	fmt.Fprintln(&source)
	fmt.Fprintf(&source, "const CapabilityID = %s\n", strconv.Quote(operation.ID().String()))
	fmt.Fprintf(&source, "const Procedure = %s\n", strconv.Quote(identity.Procedure()))
	fmt.Fprintf(&source, "const plystraErrorDetailType = %s\n", strconv.Quote(protobufdescriptor.ErrorDetailFullName))
	if useHTTPPath {
		fmt.Fprintln(&source, "const MaximumAdapterCredentialBytes = 64 << 10")
	}
	fmt.Fprintln(&source)
	fmt.Fprintln(&source, "var (")
	fmt.Fprintln(&source, "\tErrInvalidHandler = errors.New(\"invalid generated Connect capability handler\")")
	fmt.Fprintln(&source, "\tplystraErrCapability = errors.New(\"capability error\")")
	fmt.Fprintln(&source, "\tplystraErrInvalidRequest = errors.New(\"invalid request\")")
	fmt.Fprintln(&source, "\tplystraErrInvalidResponse = errors.New(\"invalid response\")")
	fmt.Fprintln(&source, "\tplystraErrInternal = errors.New(\"internal\")")
	fmt.Fprintln(&source, ")")
	fmt.Fprintln(&source)
	fmt.Fprintln(&source, "// RootContext establishes the trusted Kernel root for one external Connect request. The generated handler preserves explicit caller cancellation and the earlier caller or trusted-root deadline even when the returned context is detached.")
	fmt.Fprintln(&source, "type RootContext func(context.Context, http.Header) (context.Context, error)")
	fmt.Fprintln(&source)
	fmt.Fprintln(&source, "// Handler binds one exact Connect procedure to the canonical generated application invocation.")
	fmt.Fprintln(&source, "type Handler struct {")
	fmt.Fprintln(&source, "\troot RootContext")
	fmt.Fprintln(&source, "\ttarget applicationinvocation.Handle")
	fmt.Fprintln(&source, "\tmethod protoreflect.MethodDescriptor")
	fmt.Fprintln(&source, "\terrorDetail protoreflect.MessageDescriptor")
	fmt.Fprintln(&source, "\ttransport http.Handler")
	fmt.Fprintln(&source, "}")
	fmt.Fprintln(&source)
	fmt.Fprintln(&source, "// New binds the exact procedure to one generated canonical invocation handle.")
	fmt.Fprintln(&source, "func New(root RootContext, target applicationinvocation.Handle) (Handler, error) {")
	fmt.Fprintln(&source, "\tif root == nil || !applicationinvocation.Available(target) {")
	fmt.Fprintln(&source, "\t\treturn Handler{}, ErrInvalidHandler")
	fmt.Fprintln(&source, "\t}")
	fmt.Fprintf(&source, "\tmethod, err := connectschema.Method(%s)\n", strconv.Quote(methodName(method)))
	fmt.Fprintln(&source, "\tif err != nil {")
	fmt.Fprintln(&source, "\t\treturn Handler{}, ErrInvalidHandler")
	fmt.Fprintln(&source, "\t}")
	fmt.Fprintln(&source, "\terrorDetail, err := connectschema.Message(plystraErrorDetailType)")
	fmt.Fprintln(&source, "\tif err != nil || !plystraValidErrorDetailDescriptor(errorDetail) {")
	fmt.Fprintln(&source, "\t\treturn Handler{}, ErrInvalidHandler")
	fmt.Fprintln(&source, "\t}")
	fmt.Fprintln(&source, "\thandler := Handler{root: root, target: target, method: method, errorDetail: errorDetail}")
	fmt.Fprintln(&source, "\thandler.transport = connect.NewUnaryHandler(")
	fmt.Fprintln(&source, "\t\tProcedure,")
	fmt.Fprintln(&source, "\t\tfunc(ctx context.Context, request *connect.Request[dynamicpb.Message]) (*connect.Response[dynamicpb.Message], error) {")
	fmt.Fprintln(&source, "\t\t\treturn handler.Invoke(ctx, request)")
	fmt.Fprintln(&source, "\t\t},")
	fmt.Fprintln(&source, "\t\tconnect.WithSchema(method),")
	fmt.Fprintln(&source, "\t\tconnect.WithRequestInitializer(connectschema.InitializeDynamicMessage),")
	fmt.Fprintln(&source, "\t\tconnect.WithCodec(connectschema.BinaryCodec{}),")
	fmt.Fprintln(&source, "\t\tconnect.WithCodec(connectschema.JSONCodec{}),")
	fmt.Fprintln(&source, "\t\tconnect.WithReadMaxBytes(connectschema.MaximumRequestBytes),")
	fmt.Fprintln(&source, "\t\tconnect.WithSendMaxBytes(connectschema.MaximumResponseBytes),")
	fmt.Fprintln(&source, "\t\tconnect.WithRequireConnectProtocolHeader(),")
	fmt.Fprintln(&source, "\t)")
	fmt.Fprintln(&source, "\treturn handler, nil")
	fmt.Fprintln(&source, "}")
	fmt.Fprintln(&source)
	fmt.Fprintln(&source, "// Available reports whether the descriptor, root, invocation, and transport are bound.")
	fmt.Fprintln(&source, "func Available(handler Handler) bool {")
	fmt.Fprintln(&source, "\treturn handler.root != nil && applicationinvocation.Available(handler.target) && handler.method != nil && plystraValidErrorDetailDescriptor(handler.errorDetail) && handler.transport != nil")
	fmt.Fprintln(&source, "}")
	fmt.Fprintln(&source)
	fmt.Fprintln(&source, "// ServeHTTP serves only this procedure through the generated Connect runtime.")
	fmt.Fprintln(&source, "func (h Handler) ServeHTTP(writer http.ResponseWriter, request *http.Request) {")
	fmt.Fprintln(&source, "\tif !Available(h) {")
	fmt.Fprintln(&source, "\t\thttp.Error(writer, plystraErrInternal.Error(), http.StatusInternalServerError)")
	fmt.Fprintln(&source, "\t\treturn")
	fmt.Fprintln(&source, "\t}")
	fmt.Fprintln(&source, "\tplystraServeConnectOnly(writer, request, h.transport)")
	fmt.Fprintln(&source, "}")
	fmt.Fprintln(&source)
	renderConnectProtocolBoundary(&source, cors)
	fmt.Fprintln(&source)
	fmt.Fprintf(&source, "// Invoke converts %s messages and enters canonical Capability %s.\n", identity.PublicID(), operation.ID())
	fmt.Fprintln(&source, "func (h Handler) Invoke(ctx context.Context, request *connect.Request[dynamicpb.Message]) (result *connect.Response[dynamicpb.Message], resultErr error) {")
	fmt.Fprintln(&source, "\treturn h.InvokeRequested(ctx, CapabilityID, request)")
	fmt.Fprintln(&source, "}")
	fmt.Fprintln(&source)
	fmt.Fprintln(&source, "// InvokeRequested preserves one generated canonical or Alias request identity while entering the canonical target.")
	fmt.Fprintln(&source, "func (h Handler) InvokeRequested(ctx context.Context, requestedCapabilityID string, request *connect.Request[dynamicpb.Message]) (result *connect.Response[dynamicpb.Message], resultErr error) {")
	fmt.Fprintln(&source, "\tsafeRequestedCapabilityID := CapabilityID")
	fmt.Fprintln(&source, "\tif plystraRequestedCapabilityID(requestedCapabilityID) {")
	fmt.Fprintln(&source, "\t\tsafeRequestedCapabilityID = requestedCapabilityID")
	fmt.Fprintln(&source, "\t}")
	fmt.Fprintln(&source, "\tdefer func() {")
	fmt.Fprintln(&source, "\t\tif recover() != nil {")
	fmt.Fprintln(&source, "\t\t\tresult = nil")
	fmt.Fprintln(&source, "\t\t\tresultErr = plystraKernelConnectError(h.errorDetail, safeRequestedCapabilityID, \"internal\", plystraErrInternal)")
	fmt.Fprintln(&source, "\t\t}")
	fmt.Fprintln(&source, "\t}()")
	fmt.Fprintln(&source, "\tif requestedCapabilityID != safeRequestedCapabilityID || ctx == nil || request == nil || request.Msg == nil || !Available(h) {")
	fmt.Fprintln(&source, "\t\treturn nil, plystraKernelConnectError(h.errorDetail, safeRequestedCapabilityID, \"internal\", plystraErrInternal)")
	fmt.Fprintln(&source, "\t}")
	fmt.Fprintln(&source, "\tinput, err := plystraDecodeRequest(request.Msg)")
	fmt.Fprintln(&source, "\tif err != nil {")
	fmt.Fprintln(&source, "\t\treturn nil, plystraKernelConnectError(h.errorDetail, safeRequestedCapabilityID, \"invalid_argument\", plystraErrInvalidRequest)")
	fmt.Fprintln(&source, "\t}")
	fmt.Fprintln(&source, "\tif err := applicationinvocation.ValidateRequest(input); err != nil {")
	fmt.Fprintln(&source, "\t\treturn nil, plystraInvocationConnectError(h.errorDetail, safeRequestedCapabilityID, applicationinvocation.SafeTransportError(err))")
	fmt.Fprintln(&source, "\t}")
	fmt.Fprintln(&source, "\troot, cleanupRoot, err := plystraCreateRoot(h.root, ctx, request.Header().Clone())")
	fmt.Fprintln(&source, "\tdefer cleanupRoot()")
	fmt.Fprintln(&source, "\tif err != nil || root == nil {")
	fmt.Fprintln(&source, "\t\treturn nil, plystraInvocationConnectError(h.errorDetail, safeRequestedCapabilityID, applicationinvocation.SafeTransportError(err))")
	fmt.Fprintln(&source, "\t}")
	if useHTTPPath {
		fmt.Fprintln(&source, "\tresponse, err := plystraInvoke(root, h.target, input, request.Header())")
	} else {
		fmt.Fprintln(&source, "\tresponse, err := plystraInvoke(root, h.target, input)")
	}
	fmt.Fprintln(&source, "\tif err != nil {")
	fmt.Fprintln(&source, "\t\treturn nil, plystraInvocationConnectError(h.errorDetail, safeRequestedCapabilityID, applicationinvocation.SafeTransportError(err))")
	fmt.Fprintln(&source, "\t}")
	fmt.Fprintln(&source, "\tmessage, err := plystraEncodeResponse(h.method, response)")
	fmt.Fprintln(&source, "\tif err != nil {")
	fmt.Fprintln(&source, "\t\treturn nil, plystraKernelConnectError(h.errorDetail, safeRequestedCapabilityID, \"internal\", plystraErrInvalidResponse)")
	fmt.Fprintln(&source, "\t}")
	fmt.Fprintln(&source, "\treturn connect.NewResponse(message), nil")
	fmt.Fprintln(&source, "}")
	fmt.Fprintln(&source)
	renderBoundaryHelpers(&source, useHTTPPath, requestedCapabilityIDs)
	renderDecodeRequest(&source, identity.RequestType(), request)
	renderEncodeResponse(&source, identity.ResponseType(), response)
	if hasOptionalField(request) {
		fmt.Fprintln(&source)
		fmt.Fprintln(&source, "func plystraPointer[Value any](value Value) *Value { return &value }")
	}

	formatted, err := format.Source([]byte(source.String()))
	if err != nil {
		return File{}, fmt.Errorf("format generated canonical handler: %w", err)
	}
	return File{
		path:        path.Join(directory, "handler_gen.go"),
		packageName: packageName,
		data:        append([]byte(nil), formatted...),
	}, nil
}

func renderAlias(
	modulePath string,
	alias protobufmodel.Alias,
	target protobufmodel.Operation,
	method protoreflect.MethodDescriptor,
	cors *applicationmeta.HTTPCORS,
) (File, error) {
	identity := alias.Identity()
	if method == nil || methodName(method) != identity.Package()+"."+identity.Service()+"."+identity.Method() {
		return File{}, fmt.Errorf("%w: Alias method descriptor is inconsistent", ErrDescriptor)
	}
	if alias.Target().String() != target.ID().String() || alias.TargetContractDigest() != target.ContractDigest() {
		return File{}, fmt.Errorf("%w: Alias canonical target is inconsistent", ErrProjection)
	}
	if len(alias.Deprecated()) > 1024 || !utf8.ValidString(alias.Deprecated()) || strings.ContainsRune(alias.Deprecated(), '\x00') {
		return File{}, fmt.Errorf("%w: Alias deprecation is invalid", ErrProjection)
	}
	directory, err := generatedDirectory(alias.ID())
	if err != nil {
		return File{}, err
	}
	parsedID, err := capabilityid.Parse(alias.ID().String())
	if err != nil {
		return File{}, fmt.Errorf("%w: Alias %s has no generated Go package", ErrProjection, alias.ID())
	}
	packageName := goname.Package(parsedID)
	canonicalID, err := capabilityid.Parse(target.ID().String())
	if err != nil {
		return File{}, fmt.Errorf("%w: canonical target %s has no generated Go package", ErrProjection, target.ID())
	}
	canonicalImport := path.Join(modulePath, generatedCapabilityDirectory("adapters/connect", canonicalID))

	var source strings.Builder
	fmt.Fprintln(&source, "// Code generated by Plystra CLI. DO NOT EDIT.")
	fmt.Fprintln(&source)
	fmt.Fprintf(&source, "package %s\n\n", packageName)
	fmt.Fprintln(&source, "import (")
	fmt.Fprintln(&source, "\t\"context\"")
	fmt.Fprintln(&source, "\t\"errors\"")
	fmt.Fprintln(&source, "\t\"mime\"")
	if cors != nil {
		fmt.Fprintln(&source, "\t\"net\"")
	}
	fmt.Fprintln(&source, "\t\"net/http\"")
	if cors != nil {
		fmt.Fprintln(&source, "\t\"net/url\"")
		fmt.Fprintln(&source, "\t\"strconv\"")
		fmt.Fprintln(&source, "\t\"strings\"")
	}
	fmt.Fprintln(&source)
	fmt.Fprintln(&source, "\t\"connectrpc.com/connect\"")
	fmt.Fprintf(&source, "\tcanonicaladapter %s\n", strconv.Quote(canonicalImport))
	fmt.Fprintf(&source, "\tconnectschema %s\n", strconv.Quote(runtimeSchemaImport(modulePath)))
	fmt.Fprintln(&source, "\t\"google.golang.org/protobuf/types/dynamicpb\"")
	fmt.Fprintln(&source, ")")
	fmt.Fprintln(&source)
	fmt.Fprintf(&source, "const CapabilityID = %s\n", strconv.Quote(alias.ID().String()))
	fmt.Fprintf(&source, "const Procedure = %s\n", strconv.Quote(identity.Procedure()))
	fmt.Fprintln(&source)
	fmt.Fprintln(&source, "var ErrInvalidHandler = errors.New(\"invalid generated Connect Alias handler\")")
	fmt.Fprintln(&source)
	fmt.Fprintf(&source, "// Handler serves application-local Alias %s through canonical target %s.\n", alias.ID(), target.ID())
	renderDeprecation(&source, alias.Deprecated())
	fmt.Fprintln(&source, "type Handler struct {")
	fmt.Fprintln(&source, "\ttarget canonicaladapter.Handler")
	fmt.Fprintln(&source, "\ttransport http.Handler")
	fmt.Fprintln(&source, "}")
	fmt.Fprintln(&source)
	fmt.Fprintf(&source, "// New binds Alias %s to the canonical generated handler for %s.\n", alias.ID(), target.ID())
	renderDeprecation(&source, alias.Deprecated())
	fmt.Fprintln(&source, "func New(target canonicaladapter.Handler) (Handler, error) {")
	fmt.Fprintln(&source, "\tif !canonicaladapter.Available(target) {")
	fmt.Fprintln(&source, "\t\treturn Handler{}, ErrInvalidHandler")
	fmt.Fprintln(&source, "\t}")
	fmt.Fprintf(&source, "\tmethod, err := connectschema.Method(%s)\n", strconv.Quote(methodName(method)))
	fmt.Fprintln(&source, "\tif err != nil {")
	fmt.Fprintln(&source, "\t\treturn Handler{}, ErrInvalidHandler")
	fmt.Fprintln(&source, "\t}")
	fmt.Fprintln(&source, "\thandler := Handler{target: target}")
	fmt.Fprintln(&source, "\thandler.transport = connect.NewUnaryHandler(")
	fmt.Fprintln(&source, "\t\tProcedure,")
	fmt.Fprintln(&source, "\t\tfunc(ctx context.Context, request *connect.Request[dynamicpb.Message]) (*connect.Response[dynamicpb.Message], error) {")
	fmt.Fprintln(&source, "\t\t\treturn target.InvokeRequested(ctx, CapabilityID, request)")
	fmt.Fprintln(&source, "\t\t},")
	fmt.Fprintln(&source, "\t\tconnect.WithSchema(method),")
	fmt.Fprintln(&source, "\t\tconnect.WithRequestInitializer(connectschema.InitializeDynamicMessage),")
	fmt.Fprintln(&source, "\t\tconnect.WithCodec(connectschema.BinaryCodec{}),")
	fmt.Fprintln(&source, "\t\tconnect.WithCodec(connectschema.JSONCodec{}),")
	fmt.Fprintln(&source, "\t\tconnect.WithReadMaxBytes(connectschema.MaximumRequestBytes),")
	fmt.Fprintln(&source, "\t\tconnect.WithSendMaxBytes(connectschema.MaximumResponseBytes),")
	fmt.Fprintln(&source, "\t\tconnect.WithRequireConnectProtocolHeader(),")
	fmt.Fprintln(&source, "\t)")
	fmt.Fprintln(&source, "\treturn handler, nil")
	fmt.Fprintln(&source, "}")
	fmt.Fprintln(&source)
	fmt.Fprintln(&source, "// Available reports whether the canonical target and Alias transport are bound.")
	fmt.Fprintln(&source, "func Available(handler Handler) bool {")
	fmt.Fprintln(&source, "\treturn canonicaladapter.Available(handler.target) && handler.transport != nil")
	fmt.Fprintln(&source, "}")
	fmt.Fprintln(&source)
	fmt.Fprintf(&source, "// ServeHTTP forwards Alias %s through canonical target %s.\n", alias.ID(), target.ID())
	fmt.Fprintln(&source, "func (h Handler) ServeHTTP(writer http.ResponseWriter, request *http.Request) {")
	fmt.Fprintln(&source, "\tif !Available(h) {")
	fmt.Fprintln(&source, "\t\thttp.Error(writer, \"internal\", http.StatusInternalServerError)")
	fmt.Fprintln(&source, "\t\treturn")
	fmt.Fprintln(&source, "\t}")
	fmt.Fprintln(&source, "\tplystraServeConnectOnly(writer, request, h.transport)")
	fmt.Fprintln(&source, "}")
	fmt.Fprintln(&source)
	renderConnectProtocolBoundary(&source, cors)

	formatted, err := format.Source([]byte(source.String()))
	if err != nil {
		return File{}, fmt.Errorf("format generated Alias handler: %w", err)
	}
	return File{path: path.Join(directory, "handler_gen.go"), packageName: packageName, data: append([]byte(nil), formatted...)}, nil
}

func renderConnectProtocolBoundary(source *strings.Builder, cors *applicationmeta.HTTPCORS) {
	fmt.Fprintln(source, "const plystraConnectAcceptPost = \"application/json, application/proto\"")
	if cors != nil {
		fmt.Fprintln(source, "const plystraCORSAllowHeaders = \"Authorization, Connect-Protocol-Version, Connect-Timeout-Ms, Content-Type\"")
		fmt.Fprintln(source, "const plystraCORSAllowMethods = \"POST\"")
		fmt.Fprintf(source, "const plystraCORSAllowCredentials = %t\n", cors.AllowCredentials)
		fmt.Fprintln(source, "const plystraCORSMaximumOriginBytes = 4096")
		fmt.Fprintln(source, "const plystraCORSMaximumRequestHeaderBytes = 4096")
		fmt.Fprintln(source, "const plystraCORSMaximumRequestHeaderValues = 4")
	}
	fmt.Fprintln(source)
	fmt.Fprintln(source, "func plystraServeConnectOnly(writer http.ResponseWriter, request *http.Request, transport http.Handler) {")
	fmt.Fprintln(source, "\tif request == nil || transport == nil {")
	fmt.Fprintln(source, "\t\thttp.Error(writer, \"internal\", http.StatusInternalServerError)")
	fmt.Fprintln(source, "\t\treturn")
	fmt.Fprintln(source, "\t}")
	if cors != nil {
		fmt.Fprintln(source, "\tif plystraServeCORS(writer, request) {")
		fmt.Fprintln(source, "\t\treturn")
		fmt.Fprintln(source, "\t}")
	}
	fmt.Fprintln(source, "\tif request.Method != http.MethodPost {")
	fmt.Fprintln(source, "\t\twriter.Header().Set(\"Allow\", http.MethodPost)")
	fmt.Fprintln(source, "\t\twriter.WriteHeader(http.StatusMethodNotAllowed)")
	fmt.Fprintln(source, "\t\treturn")
	fmt.Fprintln(source, "\t}")
	fmt.Fprintln(source, "\tif !plystraConnectContentType(request.Header.Get(\"Content-Type\")) {")
	fmt.Fprintln(source, "\t\twriter.Header().Set(\"Accept-Post\", plystraConnectAcceptPost)")
	fmt.Fprintln(source, "\t\twriter.WriteHeader(http.StatusUnsupportedMediaType)")
	fmt.Fprintln(source, "\t\treturn")
	fmt.Fprintln(source, "\t}")
	fmt.Fprintln(source, "\ttransport.ServeHTTP(writer, request)")
	fmt.Fprintln(source, "}")
	fmt.Fprintln(source)
	fmt.Fprintln(source, "func plystraConnectContentType(value string) bool {")
	fmt.Fprintln(source, "\tcontentType, parameters, err := mime.ParseMediaType(value)")
	fmt.Fprintln(source, "\tif err != nil || len(parameters) != 0 {")
	fmt.Fprintln(source, "\t\treturn false")
	fmt.Fprintln(source, "\t}")
	fmt.Fprintln(source, "\treturn contentType == \"application/json\" || contentType == \"application/proto\"")
	fmt.Fprintln(source, "}")
	if cors != nil {
		fmt.Fprintln(source)
		renderCORSBoundary(source, *cors)
	}
}

func renderCORSBoundary(source *strings.Builder, cors applicationmeta.HTTPCORS) {
	fmt.Fprintln(source, "func plystraServeCORS(writer http.ResponseWriter, request *http.Request) bool {")
	fmt.Fprintln(source, "\tplystraAddVary(writer.Header(), \"Origin\")")
	fmt.Fprintln(source, "\torigins := request.Header.Values(\"Origin\")")
	fmt.Fprintln(source, "\tif len(origins) == 0 {")
	fmt.Fprintln(source, "\t\treturn false")
	fmt.Fprintln(source, "\t}")
	fmt.Fprintln(source, "\tif len(origins) != 1 || !plystraValidCORSOrigin(origins[0]) {")
	fmt.Fprintln(source, "\t\twriter.WriteHeader(http.StatusForbidden)")
	fmt.Fprintln(source, "\t\treturn true")
	fmt.Fprintln(source, "\t}")
	fmt.Fprintln(source, "\tresponseOrigin, allowed := plystraAllowedCORSOrigin(origins[0])")
	fmt.Fprintln(source, "\tif !allowed {")
	fmt.Fprintln(source, "\t\twriter.WriteHeader(http.StatusForbidden)")
	fmt.Fprintln(source, "\t\treturn true")
	fmt.Fprintln(source, "\t}")
	fmt.Fprintln(source, "\tif request.Method != http.MethodOptions {")
	fmt.Fprintln(source, "\t\tplystraSetCORSResponse(writer.Header(), responseOrigin)")
	fmt.Fprintln(source, "\t\treturn false")
	fmt.Fprintln(source, "\t}")
	fmt.Fprintln(source, "\tplystraAddVary(writer.Header(), \"Access-Control-Request-Method\", \"Access-Control-Request-Headers\")")
	fmt.Fprintln(source, "\tmethods := request.Header.Values(\"Access-Control-Request-Method\")")
	fmt.Fprintln(source, "\tif len(methods) != 1 || methods[0] != http.MethodPost || !plystraAllowedCORSRequestHeaders(request.Header.Values(\"Access-Control-Request-Headers\")) {")
	fmt.Fprintln(source, "\t\twriter.WriteHeader(http.StatusForbidden)")
	fmt.Fprintln(source, "\t\treturn true")
	fmt.Fprintln(source, "\t}")
	fmt.Fprintln(source, "\tplystraSetCORSResponse(writer.Header(), responseOrigin)")
	fmt.Fprintln(source, "\twriter.Header().Set(\"Access-Control-Allow-Methods\", plystraCORSAllowMethods)")
	fmt.Fprintln(source, "\twriter.Header().Set(\"Access-Control-Allow-Headers\", plystraCORSAllowHeaders)")
	fmt.Fprintln(source, "\twriter.WriteHeader(http.StatusNoContent)")
	fmt.Fprintln(source, "\treturn true")
	fmt.Fprintln(source, "}")
	fmt.Fprintln(source)
	fmt.Fprintln(source, "func plystraAllowedCORSOrigin(origin string) (string, bool) {")
	if corsAllowsWildcard(cors) {
		fmt.Fprintln(source, "\treturn \"*\", true")
	} else {
		fmt.Fprintln(source, "\tswitch origin {")
		fmt.Fprint(source, "\tcase ")
		for index, origin := range cors.AllowedOrigins {
			if index != 0 {
				fmt.Fprint(source, ", ")
			}
			fmt.Fprint(source, strconv.Quote(origin))
		}
		fmt.Fprintln(source, ":")
		fmt.Fprintln(source, "\t\treturn origin, true")
		fmt.Fprintln(source, "\tdefault:")
		fmt.Fprintln(source, "\t\treturn \"\", false")
		fmt.Fprintln(source, "\t}")
	}
	fmt.Fprintln(source, "}")
	fmt.Fprintln(source)
	fmt.Fprintln(source, "func plystraValidCORSOrigin(origin string) bool {")
	fmt.Fprintln(source, "\tif origin == \"null\" {")
	fmt.Fprintln(source, "\t\treturn true")
	fmt.Fprintln(source, "\t}")
	fmt.Fprintln(source, "\tif origin == \"\" || len(origin) > plystraCORSMaximumOriginBytes || strings.TrimSpace(origin) != origin || strings.Contains(origin, \",\") {")
	fmt.Fprintln(source, "\t\treturn false")
	fmt.Fprintln(source, "\t}")
	fmt.Fprintln(source, "\tfor _, value := range []byte(origin) {")
	fmt.Fprintln(source, "\t\tif value < 0x20 || value == 0x7f {")
	fmt.Fprintln(source, "\t\t\treturn false")
	fmt.Fprintln(source, "\t\t}")
	fmt.Fprintln(source, "\t}")
	fmt.Fprintln(source, "\tparsed, err := url.Parse(origin)")
	fmt.Fprintln(source, "\tif err != nil || parsed.Opaque != \"\" || parsed.User != nil || parsed.Host == \"\" || parsed.Path != \"\" || parsed.RawPath != \"\" || parsed.RawQuery != \"\" || parsed.ForceQuery || parsed.Fragment != \"\" || parsed.RawFragment != \"\" {")
	fmt.Fprintln(source, "\t\treturn false")
	fmt.Fprintln(source, "\t}")
	fmt.Fprintln(source, "\tscheme := strings.ToLower(parsed.Scheme)")
	fmt.Fprintln(source, "\tif scheme != \"http\" && scheme != \"https\" {")
	fmt.Fprintln(source, "\t\treturn false")
	fmt.Fprintln(source, "\t}")
	fmt.Fprintln(source, "\thost := strings.ToLower(parsed.Hostname())")
	fmt.Fprintln(source, "\tif host == \"\" || strings.ContainsAny(host, \" /\\\\%\") {")
	fmt.Fprintln(source, "\t\treturn false")
	fmt.Fprintln(source, "\t}")
	fmt.Fprintln(source, "\tfor _, value := range []byte(host) {")
	fmt.Fprintln(source, "\t\tif value < 0x20 || value >= 0x7f {")
	fmt.Fprintln(source, "\t\t\treturn false")
	fmt.Fprintln(source, "\t\t}")
	fmt.Fprintln(source, "\t}")
	fmt.Fprintln(source, "\tif parsedIP := net.ParseIP(host); parsedIP != nil {")
	fmt.Fprintln(source, "\t\thost = parsedIP.String()")
	fmt.Fprintln(source, "\t}")
	fmt.Fprintln(source, "\tport := parsed.Port()")
	fmt.Fprintln(source, "\tif strings.HasSuffix(parsed.Host, \":\") {")
	fmt.Fprintln(source, "\t\treturn false")
	fmt.Fprintln(source, "\t}")
	fmt.Fprintln(source, "\tif port != \"\" {")
	fmt.Fprintln(source, "\t\tvalue, err := strconv.ParseUint(port, 10, 16)")
	fmt.Fprintln(source, "\t\tif err != nil || value == 0 {")
	fmt.Fprintln(source, "\t\t\treturn false")
	fmt.Fprintln(source, "\t\t}")
	fmt.Fprintln(source, "\t\tif (scheme == \"http\" && value == 80) || (scheme == \"https\" && value == 443) {")
	fmt.Fprintln(source, "\t\t\tport = \"\"")
	fmt.Fprintln(source, "\t\t}")
	fmt.Fprintln(source, "\t}")
	fmt.Fprintln(source, "\tif strings.Contains(host, \":\") {")
	fmt.Fprintln(source, "\t\thost = \"[\" + host + \"]\"")
	fmt.Fprintln(source, "\t}")
	fmt.Fprintln(source, "\tif port != \"\" {")
	fmt.Fprintln(source, "\t\thost = net.JoinHostPort(strings.Trim(host, \"[]\"), port)")
	fmt.Fprintln(source, "\t}")
	fmt.Fprintln(source, "\treturn origin == scheme+\"://\"+host")
	fmt.Fprintln(source, "}")
	fmt.Fprintln(source)
	fmt.Fprintln(source, "func plystraAllowedCORSRequestHeaders(values []string) bool {")
	fmt.Fprintln(source, "\tif len(values) > plystraCORSMaximumRequestHeaderValues {")
	fmt.Fprintln(source, "\t\treturn false")
	fmt.Fprintln(source, "\t}")
	fmt.Fprintln(source, "\ttotalBytes := 0")
	fmt.Fprintln(source, "\tseen := make(map[string]struct{}, len(values))")
	fmt.Fprintln(source, "\tfor _, value := range values {")
	fmt.Fprintln(source, "\t\ttotalBytes += len(value)")
	fmt.Fprintln(source, "\t\tif totalBytes > plystraCORSMaximumRequestHeaderBytes {")
	fmt.Fprintln(source, "\t\t\treturn false")
	fmt.Fprintln(source, "\t\t}")
	fmt.Fprintln(source, "\t\tfor _, field := range strings.Split(value, \",\") {")
	fmt.Fprintln(source, "\t\t\tnormalized := strings.ToLower(strings.TrimSpace(field))")
	fmt.Fprintln(source, "\t\t\tswitch normalized {")
	fmt.Fprintln(source, "\t\t\tcase \"authorization\", \"connect-protocol-version\", \"connect-timeout-ms\", \"content-type\":")
	fmt.Fprintln(source, "\t\t\tdefault:")
	fmt.Fprintln(source, "\t\t\t\treturn false")
	fmt.Fprintln(source, "\t\t\t}")
	fmt.Fprintln(source, "\t\t\tif _, duplicate := seen[normalized]; duplicate {")
	fmt.Fprintln(source, "\t\t\t\treturn false")
	fmt.Fprintln(source, "\t\t\t}")
	fmt.Fprintln(source, "\t\t\tseen[normalized] = struct{}{}")
	fmt.Fprintln(source, "\t\t}")
	fmt.Fprintln(source, "\t}")
	fmt.Fprintln(source, "\treturn true")
	fmt.Fprintln(source, "}")
	fmt.Fprintln(source)
	fmt.Fprintln(source, "func plystraSetCORSResponse(headers http.Header, origin string) {")
	fmt.Fprintln(source, "\theaders.Set(\"Access-Control-Allow-Origin\", origin)")
	fmt.Fprintln(source, "\tif plystraCORSAllowCredentials {")
	fmt.Fprintln(source, "\t\theaders.Set(\"Access-Control-Allow-Credentials\", \"true\")")
	fmt.Fprintln(source, "\t}")
	fmt.Fprintln(source, "}")
	fmt.Fprintln(source)
	fmt.Fprintln(source, "func plystraAddVary(headers http.Header, values ...string) {")
	fmt.Fprintln(source, "\tfor _, line := range headers.Values(\"Vary\") {")
	fmt.Fprintln(source, "\t\tfor _, field := range strings.Split(line, \",\") {")
	fmt.Fprintln(source, "\t\t\tif strings.TrimSpace(field) == \"*\" {")
	fmt.Fprintln(source, "\t\t\t\treturn")
	fmt.Fprintln(source, "\t\t\t}")
	fmt.Fprintln(source, "\t\t}")
	fmt.Fprintln(source, "\t}")
	fmt.Fprintln(source, "\tfor _, value := range values {")
	fmt.Fprintln(source, "\t\tpresent := false")
	fmt.Fprintln(source, "\t\tfor _, line := range headers.Values(\"Vary\") {")
	fmt.Fprintln(source, "\t\t\tfor _, field := range strings.Split(line, \",\") {")
	fmt.Fprintln(source, "\t\t\t\tif strings.EqualFold(strings.TrimSpace(field), value) {")
	fmt.Fprintln(source, "\t\t\t\t\tpresent = true")
	fmt.Fprintln(source, "\t\t\t\t\tbreak")
	fmt.Fprintln(source, "\t\t\t\t}")
	fmt.Fprintln(source, "\t\t\t}")
	fmt.Fprintln(source, "\t\t}")
	fmt.Fprintln(source, "\t\tif !present {")
	fmt.Fprintln(source, "\t\t\theaders.Add(\"Vary\", value)")
	fmt.Fprintln(source, "\t\t}")
	fmt.Fprintln(source, "\t}")
	fmt.Fprintln(source, "}")
}

func corsAllowsWildcard(cors applicationmeta.HTTPCORS) bool {
	for _, origin := range cors.AllowedOrigins {
		if origin == "*" {
			return true
		}
	}
	return false
}

func renderBoundaryHelpers(source *strings.Builder, useHTTPPath bool, requestedCapabilityIDs []string) {
	fmt.Fprintln(source, "func plystraRequestedCapabilityID(value string) bool {")
	fmt.Fprintln(source, "\tswitch value {")
	fmt.Fprint(source, "\tcase ")
	for index, capabilityID := range requestedCapabilityIDs {
		if index != 0 {
			fmt.Fprint(source, ", ")
		}
		fmt.Fprint(source, strconv.Quote(capabilityID))
	}
	fmt.Fprintln(source, ":")
	fmt.Fprintln(source, "\t\treturn true")
	fmt.Fprintln(source, "\tdefault:")
	fmt.Fprintln(source, "\t\treturn false")
	fmt.Fprintln(source, "\t}")
	fmt.Fprintln(source, "}")
	fmt.Fprintln(source)
	fmt.Fprintln(source, "func plystraValidErrorDetailDescriptor(descriptor protoreflect.MessageDescriptor) bool {")
	fmt.Fprintln(source, "\treturn descriptor != nil && descriptor.FullName() == plystraErrorDetailType && descriptor.Fields().Len() == 5 &&")
	fmt.Fprintln(source, "\t\tplystraValidErrorDetailField(descriptor, 1, \"requested_interface_id\") &&")
	fmt.Fprintln(source, "\t\tplystraValidErrorDetailField(descriptor, 2, \"canonical_interface_id\") &&")
	fmt.Fprintln(source, "\t\tplystraValidErrorDetailField(descriptor, 3, \"semantic_error_code\") &&")
	fmt.Fprintln(source, "\t\tplystraValidErrorDetailField(descriptor, 4, \"kernel_error_class\") &&")
	fmt.Fprintln(source, "\t\tplystraValidErrorDetailField(descriptor, 5, \"trace_id\")")
	fmt.Fprintln(source, "}")
	fmt.Fprintln(source)
	fmt.Fprintln(source, "func plystraValidErrorDetailField(descriptor protoreflect.MessageDescriptor, number protoreflect.FieldNumber, name protoreflect.Name) bool {")
	fmt.Fprintln(source, "\tfield := descriptor.Fields().ByNumber(number)")
	fmt.Fprintln(source, "\treturn field != nil && field.Name() == name && field.Kind() == protoreflect.StringKind && field.Cardinality() == protoreflect.Optional && !field.HasPresence()")
	fmt.Fprintln(source, "}")
	fmt.Fprintln(source)
	fmt.Fprintln(source, "func plystraInvocationConnectError(descriptor protoreflect.MessageDescriptor, requestedCapabilityID string, input applicationinvocation.TransportErrorInput) *connect.Error {")
	fmt.Fprintln(source, "\tif semanticErrorCode := input.SemanticErrorCode(); semanticErrorCode != \"\" {")
	fmt.Fprintln(source, "\t\treturn plystraConnectError(descriptor, requestedCapabilityID, connect.CodeFailedPrecondition, plystraErrCapability, semanticErrorCode, \"\")")
	fmt.Fprintln(source, "\t}")
	fmt.Fprintln(source, "\treturn plystraKernelConnectError(descriptor, requestedCapabilityID, input.KernelErrorClass(), plystraErrInternal)")
	fmt.Fprintln(source, "}")
	fmt.Fprintln(source)
	fmt.Fprintln(source, "func plystraKernelConnectError(descriptor protoreflect.MessageDescriptor, requestedCapabilityID, kernelErrorClass string, safe error) *connect.Error {")
	fmt.Fprintln(source, "\tcode := connect.CodeInternal")
	fmt.Fprintln(source, "\tswitch kernelErrorClass {")
	fmt.Fprintln(source, "\tcase \"invalid_argument\":")
	fmt.Fprintln(source, "\t\tcode = connect.CodeInvalidArgument")
	fmt.Fprintln(source, "\tcase \"not_found\":")
	fmt.Fprintln(source, "\t\tcode = connect.CodeNotFound")
	fmt.Fprintln(source, "\tcase \"conflict\":")
	fmt.Fprintln(source, "\t\tcode = connect.CodeAborted")
	fmt.Fprintln(source, "\tcase \"denied\":")
	fmt.Fprintln(source, "\t\tcode = connect.CodePermissionDenied")
	fmt.Fprintln(source, "\tcase \"unauthenticated\":")
	fmt.Fprintln(source, "\t\tcode = connect.CodeUnauthenticated")
	fmt.Fprintln(source, "\tcase \"unavailable\", \"result_unknown\":")
	fmt.Fprintln(source, "\t\tcode = connect.CodeUnavailable")
	fmt.Fprintln(source, "\tcase \"timeout\":")
	fmt.Fprintln(source, "\t\tcode = connect.CodeDeadlineExceeded")
	fmt.Fprintln(source, "\tcase \"cancelled\":")
	fmt.Fprintln(source, "\t\tcode = connect.CodeCanceled")
	fmt.Fprintln(source, "\tcase \"version_incompatible\":")
	fmt.Fprintln(source, "\t\tcode = connect.CodeUnimplemented")
	fmt.Fprintln(source, "\tcase \"internal\":")
	fmt.Fprintln(source, "\tdefault:")
	fmt.Fprintln(source, "\t\tkernelErrorClass = \"internal\"")
	fmt.Fprintln(source, "\t\tsafe = plystraErrInternal")
	fmt.Fprintln(source, "\t}")
	fmt.Fprintln(source, "\treturn plystraConnectError(descriptor, requestedCapabilityID, code, safe, \"\", kernelErrorClass)")
	fmt.Fprintln(source, "}")
	fmt.Fprintln(source)
	fmt.Fprintln(source, "func plystraConnectError(descriptor protoreflect.MessageDescriptor, requestedCapabilityID string, code connect.Code, safe error, semanticErrorCode, kernelErrorClass string) (result *connect.Error) {")
	fmt.Fprintln(source, "\tresult = connect.NewError(connect.CodeInternal, plystraErrInternal)")
	fmt.Fprintln(source, "\tdefer func() {")
	fmt.Fprintln(source, "\t\tif recover() != nil {")
	fmt.Fprintln(source, "\t\t\tresult = connect.NewError(connect.CodeInternal, plystraErrInternal)")
	fmt.Fprintln(source, "\t\t}")
	fmt.Fprintln(source, "\t}()")
	fmt.Fprintln(source, "\tif !plystraValidErrorDetailDescriptor(descriptor) || !plystraRequestedCapabilityID(requestedCapabilityID) || safe == nil || (semanticErrorCode == \"\") == (kernelErrorClass == \"\") {")
	fmt.Fprintln(source, "\t\treturn result")
	fmt.Fprintln(source, "\t}")
	fmt.Fprintln(source, "\tif semanticErrorCode != \"\" && code != connect.CodeFailedPrecondition {")
	fmt.Fprintln(source, "\t\treturn result")
	fmt.Fprintln(source, "\t}")
	fmt.Fprintln(source, "\tmessage := dynamicpb.NewMessage(descriptor)")
	fmt.Fprintln(source, "\tvalues := []string{requestedCapabilityID, CapabilityID, semanticErrorCode, kernelErrorClass, \"\"}")
	fmt.Fprintln(source, "\tfor index, value := range values {")
	fmt.Fprintln(source, "\t\tfield := descriptor.Fields().ByNumber(protoreflect.FieldNumber(index + 1))")
	fmt.Fprintln(source, "\t\tmessage.Set(field, protoreflect.ValueOfString(value))")
	fmt.Fprintln(source, "\t}")
	fmt.Fprintln(source, "\tif connectschema.ValidateResponseMessage(message.ProtoReflect()) != nil {")
	fmt.Fprintln(source, "\t\treturn result")
	fmt.Fprintln(source, "\t}")
	fmt.Fprintln(source, "\tdetail, err := connect.NewErrorDetail(message)")
	fmt.Fprintln(source, "\tif err != nil || detail == nil {")
	fmt.Fprintln(source, "\t\treturn result")
	fmt.Fprintln(source, "\t}")
	fmt.Fprintln(source, "\tresult = connect.NewError(code, safe)")
	fmt.Fprintln(source, "\tresult.AddDetail(detail)")
	fmt.Fprintln(source, "\treturn result")
	fmt.Fprintln(source, "}")
	fmt.Fprintln(source)
	fmt.Fprintln(source, "func plystraCreateRoot(root RootContext, parent context.Context, headers http.Header) (ctx context.Context, cleanup func(), err error) {")
	fmt.Fprintln(source, "\tcleanup = func() {}")
	fmt.Fprintln(source, "\tdefer func() {")
	fmt.Fprintln(source, "\t\tif recover() != nil {")
	fmt.Fprintln(source, "\t\t\tctx = nil")
	fmt.Fprintln(source, "\t\t\tcleanup = func() {}")
	fmt.Fprintln(source, "\t\t\terr = ErrInvalidHandler")
	fmt.Fprintln(source, "\t\t}")
	fmt.Fprintln(source, "\t}()")
	fmt.Fprintln(source, "\tctx, err = root(parent, headers)")
	fmt.Fprintln(source, "\tif err != nil || ctx == nil {")
	fmt.Fprintln(source, "\t\treturn ctx, cleanup, err")
	fmt.Fprintln(source, "\t}")
	fmt.Fprintln(source, "\tdeadline, hasDeadline := parent.Deadline()")
	fmt.Fprintln(source, "\tvar requestContext context.Context")
	fmt.Fprintln(source, "\tvar cancel context.CancelFunc")
	fmt.Fprintln(source, "\tif hasDeadline {")
	fmt.Fprintln(source, "\t\trequestContext, cancel = context.WithDeadline(ctx, deadline)")
	fmt.Fprintln(source, "\t} else {")
	fmt.Fprintln(source, "\t\trequestContext, cancel = context.WithCancel(ctx)")
	fmt.Fprintln(source, "\t}")
	fmt.Fprintln(source, "\tstopParent := context.AfterFunc(parent, func() { plystraCancelFromParent(parent, cancel) })")
	fmt.Fprintln(source, "\tplystraCancelFromParent(parent, cancel)")
	fmt.Fprintln(source, "\treturn requestContext, func() {")
	fmt.Fprintln(source, "\t\tstopParent()")
	fmt.Fprintln(source, "\t\tcancel()")
	fmt.Fprintln(source, "\t}, nil")
	fmt.Fprintln(source, "}")
	fmt.Fprintln(source)
	fmt.Fprintln(source, "func plystraCancelFromParent(parent context.Context, cancel context.CancelFunc) {")
	fmt.Fprintln(source, "\tdefer func() { _ = recover() }()")
	fmt.Fprintln(source, "\tif parent != nil && parent.Err() == context.Canceled {")
	fmt.Fprintln(source, "\t\tcancel()")
	fmt.Fprintln(source, "\t}")
	fmt.Fprintln(source, "}")
	fmt.Fprintln(source)
	if useHTTPPath {
		fmt.Fprintln(source, "func plystraInvoke(ctx context.Context, target applicationinvocation.Handle, request contract.Request, headers http.Header) (response contract.Response, err error) {")
	} else {
		fmt.Fprintln(source, "func plystraInvoke(ctx context.Context, target applicationinvocation.Handle, request contract.Request) (response contract.Response, err error) {")
	}
	fmt.Fprintln(source, "\tdefer func() {")
	fmt.Fprintln(source, "\t\tif recover() != nil {")
	fmt.Fprintln(source, "\t\t\tresponse = contract.Response{}")
	fmt.Fprintln(source, "\t\t\terr = ErrInvalidHandler")
	fmt.Fprintln(source, "\t\t}")
	fmt.Fprintln(source, "\t}()")
	if useHTTPPath {
		fmt.Fprintln(source, "\treturn target.InvokeHTTP(ctx, request, func(name string) (string, bool) {")
		fmt.Fprintln(source, "\t\treturn plystraAdapterCredential(headers, name)")
		fmt.Fprintln(source, "\t})")
	} else {
		fmt.Fprintln(source, "\treturn target.Invoke(ctx, request)")
	}
	fmt.Fprintln(source, "}")
	if useHTTPPath {
		fmt.Fprintln(source)
		fmt.Fprintln(source, "func plystraAdapterCredential(headers http.Header, name string) (string, bool) {")
		fmt.Fprintln(source, "\theader := http.CanonicalHeaderKey(strings.ReplaceAll(name, \"_\", \"-\"))")
		fmt.Fprintln(source, "\tvalues := headers.Values(header)")
		fmt.Fprintln(source, "\tif len(values) != 1 {")
		fmt.Fprintln(source, "\t\treturn \"\", false")
		fmt.Fprintln(source, "\t}")
		fmt.Fprintln(source, "\tvalue := strings.TrimSpace(values[0])")
		fmt.Fprintln(source, "\tif value == \"\" || len(value) > MaximumAdapterCredentialBytes {")
		fmt.Fprintln(source, "\t\treturn \"\", false")
		fmt.Fprintln(source, "\t}")
		fmt.Fprintln(source, "\tfor index := 0; index < len(value); index++ {")
		fmt.Fprintln(source, "\t\tif value[index] < ' ' || value[index] == 0x7f {")
		fmt.Fprintln(source, "\t\t\treturn \"\", false")
		fmt.Fprintln(source, "\t\t}")
		fmt.Fprintln(source, "\t}")
		fmt.Fprintln(source, "\treturn value, true")
		fmt.Fprintln(source, "}")
	}
}

func renderDecodeRequest(source *strings.Builder, messageName string, fields []preparedField) {
	fmt.Fprintln(source)
	fmt.Fprintln(source, "func plystraDecodeRequest(message *dynamicpb.Message) (contract.Request, error) {")
	fmt.Fprintln(source, "\tvar result contract.Request")
	fmt.Fprintf(source, "\tif message == nil || message.ProtoReflect().Descriptor().FullName() != %s || connectschema.ValidateMessage(message.ProtoReflect()) != nil {\n", strconv.Quote(messageName))
	fmt.Fprintln(source, "\t\treturn result, plystraErrInvalidRequest")
	fmt.Fprintln(source, "\t}")
	if len(fields) != 0 {
		fmt.Fprintln(source, "\treflected := message.ProtoReflect()")
	}
	for index, field := range fields {
		renderDecodeField(source, index, field)
	}
	fmt.Fprintln(source, "\treturn result, nil")
	fmt.Fprintln(source, "}")
}

func renderDecodeField(source *strings.Builder, index int, prepared preparedField) {
	fieldName := fmt.Sprintf("field%d", index)
	fmt.Fprintf(source, "\t%s, err := connectschema.Field(reflected, %d, %s)\n", fieldName, prepared.wire.Number(), strconv.Quote(prepared.wire.Name()))
	fmt.Fprintln(source, "\tif err != nil {")
	fmt.Fprintln(source, "\t\treturn result, plystraErrInvalidRequest")
	fmt.Fprintln(source, "\t}")
	if prepared.field.Required() {
		fmt.Fprintf(source, "\tif !reflected.Has(%s) {\n", fieldName)
		fmt.Fprintln(source, "\t\treturn result, plystraErrInvalidRequest")
		fmt.Fprintln(source, "\t}")
	} else {
		fmt.Fprintf(source, "\tif reflected.Has(%s) {\n", fieldName)
	}
	indent := "\t"
	if !prepared.field.Required() {
		indent = "\t\t"
	}
	valueExpression := fmt.Sprintf("reflected.Get(%s)", fieldName)
	variable := fmt.Sprintf("value%d", index)
	switch {
	case len(prepared.field.EnumJSON()) != 0:
		fmt.Fprintf(source, "%sswitch %s.Enum() {\n", indent, valueExpression)
		for _, member := range enumMembers(prepared) {
			fmt.Fprintf(source, "%scase %d:\n", indent, member.number)
			expression := "contract." + prepared.enumType + "(" + member.literal + ")"
			if prepared.field.Required() {
				fmt.Fprintf(source, "%s\tresult.%s = %s\n", indent, prepared.goName, expression)
			} else {
				fmt.Fprintf(source, "%s\t%s := %s\n", indent, variable, expression)
				fmt.Fprintf(source, "%s\tresult.%s = &%s\n", indent, prepared.goName, variable)
			}
		}
		fmt.Fprintf(source, "%sdefault:\n", indent)
		fmt.Fprintf(source, "%s\treturn result, plystraErrInvalidRequest\n", indent)
		fmt.Fprintf(source, "%s}\n", indent)
	case prepared.field.Kind() == sdkmodel.KindArray:
		renderDecodeArray(source, indent, index, prepared, valueExpression)
	case prepared.field.Kind() == sdkmodel.KindObject:
		fmt.Fprintf(source, "%s%s, err := connectschema.DecodeStruct(%s.Message())\n", indent, variable, valueExpression)
		fmt.Fprintf(source, "%sif err != nil {\n", indent)
		fmt.Fprintf(source, "%s\treturn result, plystraErrInvalidRequest\n", indent)
		fmt.Fprintf(source, "%s}\n", indent)
		if prepared.field.Required() {
			fmt.Fprintf(source, "%sresult.%s = %s\n", indent, prepared.goName, variable)
		} else {
			fmt.Fprintf(source, "%sresult.%s = &%s\n", indent, prepared.goName, variable)
		}
	default:
		expression := decodeScalarExpression(prepared.field.Kind(), valueExpression)
		if prepared.field.Required() {
			fmt.Fprintf(source, "%sresult.%s = %s\n", indent, prepared.goName, expression)
		} else {
			fmt.Fprintf(source, "%sresult.%s = plystraPointer(%s)\n", indent, prepared.goName, expression)
		}
	}
	if !prepared.field.Required() {
		fmt.Fprintln(source, "\t}")
	}
}

func renderDecodeArray(source *strings.Builder, indent string, index int, prepared preparedField, valueExpression string) {
	wrapper := fmt.Sprintf("wrapper%d", index)
	valuesField := fmt.Sprintf("valuesField%d", index)
	list := fmt.Sprintf("list%d", index)
	values := fmt.Sprintf("values%d", index)
	fmt.Fprintf(source, "%s%s := %s.Message()\n", indent, wrapper, valueExpression)
	fmt.Fprintf(source, "%s%s, err := connectschema.Field(%s, 1, \"values\")\n", indent, valuesField, wrapper)
	fmt.Fprintf(source, "%sif err != nil {\n", indent)
	fmt.Fprintf(source, "%s\treturn result, plystraErrInvalidRequest\n", indent)
	fmt.Fprintf(source, "%s}\n", indent)
	fmt.Fprintf(source, "%s%s := %s.Get(%s).List()\n", indent, list, wrapper, valuesField)
	fmt.Fprintf(source, "%s%s := make([]%s, %s.Len())\n", indent, values, goType(prepared.field.Items()), list)
	fmt.Fprintf(source, "%sfor item := 0; item < %s.Len(); item++ {\n", indent, list)
	if prepared.field.Items() == sdkmodel.KindObject {
		fmt.Fprintf(source, "%s\tdecoded, err := connectschema.DecodeStruct(%s.Get(item).Message())\n", indent, list)
		fmt.Fprintf(source, "%s\tif err != nil {\n", indent)
		fmt.Fprintf(source, "%s\t\treturn result, plystraErrInvalidRequest\n", indent)
		fmt.Fprintf(source, "%s\t}\n", indent)
		fmt.Fprintf(source, "%s\t%s[item] = decoded\n", indent, values)
	} else {
		fmt.Fprintf(source, "%s\t%s[item] = %s\n", indent, values, decodeScalarExpression(prepared.field.Items(), list+".Get(item)"))
	}
	fmt.Fprintf(source, "%s}\n", indent)
	if prepared.field.Required() {
		fmt.Fprintf(source, "%sresult.%s = %s\n", indent, prepared.goName, values)
	} else {
		fmt.Fprintf(source, "%sresult.%s = &%s\n", indent, prepared.goName, values)
	}
}

func renderEncodeResponse(source *strings.Builder, messageName string, fields []preparedField) {
	fmt.Fprintln(source)
	fmt.Fprintln(source, "func plystraEncodeResponse(method protoreflect.MethodDescriptor, response contract.Response) (*dynamicpb.Message, error) {")
	fmt.Fprintf(source, "\tif method == nil || method.Output() == nil || method.Output().FullName() != %s {\n", strconv.Quote(messageName))
	fmt.Fprintln(source, "\t\treturn nil, plystraErrInvalidResponse")
	fmt.Fprintln(source, "\t}")
	fmt.Fprintln(source, "\tbudget := connectschema.NewResponseEncodingBudget()")
	fmt.Fprintln(source, "\tif budget.ConsumeNodes(1) != nil {")
	fmt.Fprintln(source, "\t\treturn nil, plystraErrInvalidResponse")
	fmt.Fprintln(source, "\t}")
	for _, field := range fields {
		renderResponseBudgetField(source, field)
	}
	fmt.Fprintln(source, "\tmessage := dynamicpb.NewMessage(method.Output())")
	if len(fields) != 0 {
		fmt.Fprintln(source, "\treflected := message.ProtoReflect()")
	}
	for index, field := range fields {
		renderEncodeField(source, index, field)
	}
	fmt.Fprintln(source, "\tif connectschema.ValidateResponseMessage(message.ProtoReflect()) != nil {")
	fmt.Fprintln(source, "\t\treturn nil, plystraErrInvalidResponse")
	fmt.Fprintln(source, "\t}")
	fmt.Fprintln(source, "\treturn message, nil")
	fmt.Fprintln(source, "}")
}

func renderResponseBudgetField(source *strings.Builder, prepared preparedField) {
	value := "response." + prepared.goName
	indent := "\t"
	if !prepared.field.Required() {
		fmt.Fprintf(source, "\tif %s != nil {\n", value)
		value = "*" + value
		indent = "\t\t"
	}
	fmt.Fprintf(source, "%sif budget.ConsumeNodes(1) != nil {\n", indent)
	fmt.Fprintf(source, "%s\treturn nil, plystraErrInvalidResponse\n", indent)
	fmt.Fprintf(source, "%s}\n", indent)
	switch {
	case prepared.field.Kind() == sdkmodel.KindString && len(prepared.field.EnumJSON()) == 0:
		fmt.Fprintf(source, "%sif budget.ConsumeBytes(len(%s)) != nil {\n", indent, value)
		fmt.Fprintf(source, "%s\treturn nil, plystraErrInvalidResponse\n", indent)
		fmt.Fprintf(source, "%s}\n", indent)
	case prepared.field.Kind() == sdkmodel.KindObject:
		fmt.Fprintf(source, "%sif budget.ValidateObject(%s) != nil {\n", indent, value)
		fmt.Fprintf(source, "%s\treturn nil, plystraErrInvalidResponse\n", indent)
		fmt.Fprintf(source, "%s}\n", indent)
	case prepared.field.Kind() == sdkmodel.KindArray:
		fmt.Fprintf(source, "%sif budget.ConsumeNodes(len(%s)) != nil {\n", indent, value)
		fmt.Fprintf(source, "%s\treturn nil, plystraErrInvalidResponse\n", indent)
		fmt.Fprintf(source, "%s}\n", indent)
		if prepared.field.Items() == sdkmodel.KindString {
			fmt.Fprintf(source, "%sfor _, item := range %s {\n", indent, value)
			fmt.Fprintf(source, "%s\tif budget.ConsumeBytes(len(item)) != nil {\n", indent)
			fmt.Fprintf(source, "%s\t\treturn nil, plystraErrInvalidResponse\n", indent)
			fmt.Fprintf(source, "%s\t}\n", indent)
			fmt.Fprintf(source, "%s}\n", indent)
		}
		if prepared.field.Items() == sdkmodel.KindObject {
			fmt.Fprintf(source, "%sfor _, item := range %s {\n", indent, value)
			fmt.Fprintf(source, "%s\tif budget.ValidateObject(item) != nil {\n", indent)
			fmt.Fprintf(source, "%s\t\treturn nil, plystraErrInvalidResponse\n", indent)
			fmt.Fprintf(source, "%s\t}\n", indent)
			fmt.Fprintf(source, "%s}\n", indent)
		}
	}
	if !prepared.field.Required() {
		fmt.Fprintln(source, "\t}")
	}
}

func renderEncodeField(source *strings.Builder, index int, prepared preparedField) {
	fieldName := fmt.Sprintf("field%d", index)
	fmt.Fprintf(source, "\t%s, err := connectschema.Field(reflected, %d, %s)\n", fieldName, prepared.wire.Number(), strconv.Quote(prepared.wire.Name()))
	fmt.Fprintln(source, "\tif err != nil {")
	fmt.Fprintln(source, "\t\treturn nil, plystraErrInvalidResponse")
	fmt.Fprintln(source, "\t}")
	value := "response." + prepared.goName
	if !prepared.field.Required() {
		fmt.Fprintf(source, "\tif %s != nil {\n", value)
		value = "*" + value
	}
	indent := "\t"
	if !prepared.field.Required() {
		indent = "\t\t"
	}
	switch {
	case len(prepared.field.EnumJSON()) != 0:
		number := fmt.Sprintf("enum%d", index)
		fmt.Fprintf(source, "%svar %s protoreflect.EnumNumber\n", indent, number)
		fmt.Fprintf(source, "%sswitch %s {\n", indent, value)
		for _, member := range enumMembers(prepared) {
			fmt.Fprintf(source, "%scase contract.%s(%s):\n", indent, prepared.enumType, member.literal)
			fmt.Fprintf(source, "%s\t%s = %d\n", indent, number, member.number)
		}
		fmt.Fprintf(source, "%sdefault:\n", indent)
		fmt.Fprintf(source, "%s\treturn nil, plystraErrInvalidResponse\n", indent)
		fmt.Fprintf(source, "%s}\n", indent)
		fmt.Fprintf(source, "%sreflected.Set(%s, protoreflect.ValueOfEnum(%s))\n", indent, fieldName, number)
	case prepared.field.Kind() == sdkmodel.KindArray:
		renderEncodeArray(source, indent, index, prepared, fieldName, value)
	case prepared.field.Kind() == sdkmodel.KindObject:
		if prepared.field.Required() {
			fmt.Fprintf(source, "%sif %s == nil {\n", indent, value)
			fmt.Fprintf(source, "%s\treturn nil, plystraErrInvalidResponse\n", indent)
			fmt.Fprintf(source, "%s}\n", indent)
		}
		object := fmt.Sprintf("object%d", index)
		fmt.Fprintf(source, "%s%s, err := connectschema.EncodeStruct(%s.Message(), %s)\n", indent, object, fieldName, value)
		fmt.Fprintf(source, "%sif err != nil {\n", indent)
		fmt.Fprintf(source, "%s\treturn nil, plystraErrInvalidResponse\n", indent)
		fmt.Fprintf(source, "%s}\n", indent)
		fmt.Fprintf(source, "%sreflected.Set(%s, protoreflect.ValueOfMessage(%s))\n", indent, fieldName, object)
	default:
		fmt.Fprintf(source, "%sreflected.Set(%s, %s)\n", indent, fieldName, encodeScalarExpression(prepared.field.Kind(), value))
	}
	if !prepared.field.Required() {
		fmt.Fprintln(source, "\t}")
	}
}

func renderEncodeArray(source *strings.Builder, indent string, index int, prepared preparedField, fieldName, value string) {
	if prepared.field.Required() {
		fmt.Fprintf(source, "%sif %s == nil {\n", indent, value)
		fmt.Fprintf(source, "%s\treturn nil, plystraErrInvalidResponse\n", indent)
		fmt.Fprintf(source, "%s}\n", indent)
	}
	wrapper := fmt.Sprintf("wrapper%d", index)
	valuesField := fmt.Sprintf("valuesField%d", index)
	list := fmt.Sprintf("list%d", index)
	fmt.Fprintf(source, "%s%s := dynamicpb.NewMessage(%s.Message())\n", indent, wrapper, fieldName)
	fmt.Fprintf(source, "%s%s, err := connectschema.Field(%s.ProtoReflect(), 1, \"values\")\n", indent, valuesField, wrapper)
	fmt.Fprintf(source, "%sif err != nil {\n", indent)
	fmt.Fprintf(source, "%s\treturn nil, plystraErrInvalidResponse\n", indent)
	fmt.Fprintf(source, "%s}\n", indent)
	fmt.Fprintf(source, "%s%s := %s.Mutable(%s).List()\n", indent, list, wrapper, valuesField)
	fmt.Fprintf(source, "%sfor _, item := range %s {\n", indent, value)
	if prepared.field.Items() == sdkmodel.KindObject {
		fmt.Fprintf(source, "%s\tobject, err := connectschema.EncodeStruct(%s.Message(), item)\n", indent, valuesField)
		fmt.Fprintf(source, "%s\tif err != nil {\n", indent)
		fmt.Fprintf(source, "%s\t\treturn nil, plystraErrInvalidResponse\n", indent)
		fmt.Fprintf(source, "%s\t}\n", indent)
		fmt.Fprintf(source, "%s\t%s.Append(protoreflect.ValueOfMessage(object))\n", indent, list)
	} else {
		fmt.Fprintf(source, "%s\t%s.Append(%s)\n", indent, list, encodeScalarExpression(prepared.field.Items(), "item"))
	}
	fmt.Fprintf(source, "%s}\n", indent)
	fmt.Fprintf(source, "%sreflected.Set(%s, protoreflect.ValueOfMessage(%s.ProtoReflect()))\n", indent, fieldName, wrapper)
}

type enumMember struct {
	literal string
	number  int
}

func enumMembers(field preparedField) []enumMember {
	byCanonical := make(map[string]int, len(field.enum.Members()))
	for _, member := range field.enum.Members() {
		byCanonical[string(member.CanonicalJSON())] = member.Number()
	}
	values := field.field.EnumJSON()
	result := make([]enumMember, 0, len(values))
	for _, value := range values {
		number, exists := byCanonical[string(value)]
		if !exists || number <= 0 {
			continue
		}
		result = append(result, enumMember{literal: canonicalLiteral(field.field.Kind(), value), number: number})
	}
	return result
}

func canonicalLiteral(kind sdkmodel.Kind, raw json.RawMessage) string {
	if kind != sdkmodel.KindString {
		return string(raw)
	}
	var value string
	if err := json.Unmarshal(raw, &value); err != nil {
		return "\"\""
	}
	return strconv.Quote(value)
}

func decodeScalarExpression(kind sdkmodel.Kind, value string) string {
	switch kind {
	case sdkmodel.KindString:
		return value + ".String()"
	case sdkmodel.KindInteger:
		return value + ".Int()"
	case sdkmodel.KindNumber:
		return value + ".Float()"
	case sdkmodel.KindBoolean:
		return value + ".Bool()"
	default:
		return value
	}
}

func encodeScalarExpression(kind sdkmodel.Kind, value string) string {
	switch kind {
	case sdkmodel.KindString:
		return "protoreflect.ValueOfString(" + value + ")"
	case sdkmodel.KindInteger:
		return "protoreflect.ValueOfInt64(" + value + ")"
	case sdkmodel.KindNumber:
		return "protoreflect.ValueOfFloat64(" + value + ")"
	case sdkmodel.KindBoolean:
		return "protoreflect.ValueOfBool(" + value + ")"
	default:
		return value
	}
}

func goType(kind sdkmodel.Kind) string {
	switch kind {
	case sdkmodel.KindString:
		return "string"
	case sdkmodel.KindInteger:
		return "int64"
	case sdkmodel.KindNumber:
		return "float64"
	case sdkmodel.KindBoolean:
		return "bool"
	case sdkmodel.KindObject:
		return "map[string]any"
	default:
		return "any"
	}
}

func hasOptionalField(fields []preparedField) bool {
	for _, field := range fields {
		if !field.field.Required() && field.field.Kind() != sdkmodel.KindArray && field.field.Kind() != sdkmodel.KindObject && len(field.field.EnumJSON()) == 0 {
			return true
		}
	}
	return false
}

func generatedCapabilityDirectory(category string, capability capabilityid.Identifier) string {
	components := append([]string{"generated", "go"}, strings.Split(category, "/")...)
	components = append(components, strings.Split(capability.Name(), ".")...)
	components = append(components, "v"+strconv.FormatUint(capability.Major(), 10))
	return path.Join(components...)
}

func renderDeprecation(source *strings.Builder, value string) {
	if value == "" {
		return
	}
	cleaned := strings.NewReplacer("\r", " ", "\n", " ", "*/", "* /").Replace(value)
	cleaned = strings.Join(strings.Fields(cleaned), " ")
	fmt.Fprintf(source, "// Deprecated: %s\n", cleaned)
}
