// Code generated by Plystra CLI. DO NOT EDIT.

package emailsendv1

import (
	"context"
	"errors"
	"unicode/utf8"

	contract "example.com/acme/project/generated/go/contracts/email/send/v1"
	kernelinvocation "github.com/plystra/kernel/invocation"
)

// Handle is the opaque generated application path to one exact canonical Capability.
type Handle struct {
	target kernelinvocation.Handle[contract.Request, contract.Response]
}

// New binds the application path to its caller-scoped canonical Kernel handle.
func New(target kernelinvocation.Handle[contract.Request, contract.Response]) Handle {
	return Handle{target: target}
}

// Available reports whether assembly selected the canonical provider.
func Available(handle Handle) bool {
	return handle.Available()
}

// Available reports whether assembly selected the canonical provider.
func (h Handle) Available() bool {
	return h.target.Available()
}

// Invoke runs the application path for email.send/v1 and dispatches its canonical ID.
func (h Handle) Invoke(ctx context.Context, request contract.Request) (contract.Response, error) {
	if requestError := ValidateRequest(request); requestError != nil {
		return contract.Response{}, requestError
	}
	response, invocationError := h.target.Invoke(ctx, request)
	if invocationError != nil {
		return contract.Response{}, invocationError
	}
	if responseError := plystraValidateResponse(response); responseError != nil {
		return contract.Response{}, responseError
	}
	return response, nil
}

// ValidateRequest applies the canonical request constraints before trusted application work begins.
func ValidateRequest(request contract.Request) error {
	return plystraValidateRequest(request)
}

func plystraValidateRequest(request contract.Request) error {
	return nil
}

var plystraErrInvalidProviderResponse = errors.New("invalid canonical Provider response")

func plystraValidateResponse(response contract.Response) error {
	if !utf8.ValidString(response.MessageID) {
		return plystraErrInvalidProviderResponse
	}
	switch response.Status {
	case contract.ResponseStatus("queued"):
	case contract.ResponseStatus("sent"):
	default:
		return plystraErrInvalidProviderResponse
	}
	return nil
}

// TransportErrorInput is the immutable data-free failure projection consumed by generated external adapters.
type TransportErrorInput struct {
	semanticErrorCode string
	kernelErrorClass  kernelinvocation.ErrorCode
	kernelDetailCode  string
	completion        kernelinvocation.Completion
}

// Valid reports whether the projection contains exactly one closed semantic or Kernel failure classification.
func (i TransportErrorInput) Valid() bool {
	if !i.completion.Valid() {
		return false
	}
	if i.semanticErrorCode != "" {
		return i.kernelErrorClass == "" && i.kernelDetailCode == "" && plystraDeclaredSemanticError(i.semanticErrorCode)
	}
	if !i.kernelErrorClass.Valid() || !kernelinvocation.ValidDetailCode(i.kernelDetailCode) {
		return false
	}
	return i.kernelErrorClass != kernelinvocation.ErrorDenied || i.kernelDetailCode != ""
}

// SemanticErrorCode returns one declared canonical semantic code or an empty string.
func (i TransportErrorInput) SemanticErrorCode() string {
	if !i.Valid() {
		return ""
	}
	return i.semanticErrorCode
}

// KernelErrorClass returns one closed Kernel failure class or an empty string.
func (i TransportErrorInput) KernelErrorClass() string {
	if !i.Valid() {
		return ""
	}
	return i.kernelErrorClass.String()
}

// KernelDetailCode returns the optional bounded Kernel detail code or an empty string.
func (i TransportErrorInput) KernelDetailCode() string {
	if !i.Valid() {
		return ""
	}
	return i.kernelDetailCode
}

// Completion returns the result certainty independently of the primary error code.
func (i TransportErrorInput) Completion() kernelinvocation.Completion {
	if !i.Valid() {
		return kernelinvocation.CompletionResultUnknown
	}
	return i.completion
}

// SafeTransportError projects one canonical invocation failure without retaining its text, cause, payload, or Provider data.
func SafeTransportError(err error) (input TransportErrorInput) {
	input = plystraInternalTransportError()
	defer func() {
		if recover() != nil || !input.Valid() {
			input = plystraInternalTransportError()
		}
	}()
	if err == nil {
		return input
	}

	completion := kernelinvocation.CompletionOf(err)
	var semantic string
	var primary kernelinvocation.ErrorCode
	var detail string
	invalid, visited := false, 0
	addPrimary := func(code kernelinvocation.ErrorCode, value string) {
		if !code.Valid() || !kernelinvocation.ValidDetailCode(value) || (code == kernelinvocation.ErrorDenied && value == "") ||
			(primary != "" && (primary != code || detail != value)) {
			invalid = true
		}
		primary, detail = code, value
	}
	// Only ordinary unwrap edges are followed. Depth and node limits also stop cycles.
	var walk func(error, int) bool
	walk = func(node error, depth int) bool {
		if node == nil {
			return true
		}
		if depth > 64 || visited == 1024 {
			return false
		}
		visited++
		switch value := node.(type) {
		case *kernelinvocation.SemanticError:
			code := value.Code()
			if !plystraDeclaredSemanticError(code) || (semantic != "" && semantic != code) {
				invalid = true
			}
			semantic = code
		case *kernelinvocation.Error:
			addPrimary(value.Code(), value.DetailCode())
		default:
			switch node {
			case context.Canceled:
				addPrimary(kernelinvocation.ErrorCancelled, "")
			case context.DeadlineExceeded:
				addPrimary(kernelinvocation.ErrorTimeout, "")
			}
		}
		switch value := node.(type) {
		case interface{ Unwrap() error }:
			return walk(value.Unwrap(), depth+1)
		case interface{ Unwrap() []error }:
			children := value.Unwrap()
			if len(children) > 1024-visited {
				return false
			}
			for _, child := range children {
				if !walk(child, depth+1) {
					return false
				}
			}
		}
		return true
	}
	if !walk(err, 0) {
		return input
	}
	if invalid || (semantic != "" && primary != "") {
		input.completion = completion
		return input
	}
	if semantic != "" {
		return TransportErrorInput{semanticErrorCode: semantic, completion: completion}
	}
	if primary != "" {
		return TransportErrorInput{kernelErrorClass: primary, kernelDetailCode: detail, completion: completion}
	}
	input.completion = completion
	return input
}

func plystraDeclaredSemanticError(code string) bool {
	switch code {
	case "authentication_failed", "invalid_recipient", "temporarily_unavailable":
		return true
	default:
		return false
	}
}

func plystraInternalTransportError() TransportErrorInput {
	return TransportErrorInput{kernelErrorClass: kernelinvocation.ErrorInternal, completion: kernelinvocation.CompletionResultUnknown}
}
