// Code generated by Plystra CLI. DO NOT EDIT.

package emailsendv1

import (
	"context"

	contract "example.com/acme/project/generated/go/contracts/email/send/v1"
	kernelinvocation "github.com/plystra/kernel/invocation"
)

// Handle is the opaque generated application path to one exact canonical Capability.
type Handle struct {
	target kernelinvocation.Handle[contract.Request, contract.Response]
}

// New binds the application path to its caller-scoped canonical Kernel handle.
func New(target kernelinvocation.Handle[contract.Request, contract.Response]) Handle {
	return Handle{target: target}
}

// Available reports whether assembly selected the canonical provider.
func Available(handle Handle) bool {
	return handle.target.Available()
}

// Invoke runs the application path for email.send/v1 and dispatches its canonical ID.
func (h Handle) Invoke(ctx context.Context, request contract.Request) (contract.Response, error) {
	return h.target.Invoke(ctx, request)
}
