// Code generated by Plystra CLI. DO NOT EDIT.

package ordercreatev1

import (
	"context"

	contract "example.com/acme/project/generated/go/contracts/order/create/v1"
	invocationcontext "example.com/acme/project/generated/go/internal/invocationcontext"
	kernelinvocation "github.com/plystra/kernel/invocation"
)

// Handle is the opaque generated application path to one exact canonical Capability.
type Handle struct {
	target kernelinvocation.Handle[contract.Request, contract.Response]
}

// New binds the application path to its caller-scoped canonical Kernel handle.
func New(target kernelinvocation.Handle[contract.Request, contract.Response]) Handle {
	return Handle{target: target}
}

// Available reports whether assembly selected the canonical provider.
func Available(handle Handle) bool {
	return handle.Available()
}

// Available reports whether assembly selected the canonical provider.
func (h Handle) Available() bool {
	return h.target.Available()
}

// Invoke runs the application path for order.create/v1 and dispatches its canonical ID.
func (h Handle) Invoke(ctx context.Context, request contract.Request) (contract.Response, error) {
	plystraPolicyMetadataDeriveCodeDerived := string(request.OrderID)
	ctx, plystraPolicyMetadataDeriveCodeError := invocationcontext.WithValue(ctx, "policy.code", plystraPolicyMetadataDeriveCodeDerived, 32)
	if plystraPolicyMetadataDeriveCodeError != nil {
		return contract.Response{}, plystraPolicyMetadataDeriveCodeError
	}
	plystraPolicyMetadataAttachContextCopySource, plystraPolicyMetadataAttachContextCopyPresent := invocationcontext.Value[string](ctx, "policy.code")
	if !plystraPolicyMetadataAttachContextCopyPresent {
		return contract.Response{}, invocationcontext.ErrInvalidValue
	}
	ctx, plystraPolicyMetadataAttachContextCopyError := invocationcontext.WithMetadata(ctx, "policy.code", string(plystraPolicyMetadataAttachContextCopySource), 16)
	if plystraPolicyMetadataAttachContextCopyError != nil {
		return contract.Response{}, plystraPolicyMetadataAttachContextCopyError
	}
	ctx, plystraPolicyMetadataAttachRequestError := invocationcontext.WithMetadata(ctx, "policy.order-id", string(request.OrderID), 16)
	if plystraPolicyMetadataAttachRequestError != nil {
		return contract.Response{}, plystraPolicyMetadataAttachRequestError
	}
	ctx, plystraPolicyMetadataAttachDerivedError := invocationcontext.WithMetadata(ctx, "policy.derived", string(plystraPolicyMetadataDeriveCodeDerived), 16)
	if plystraPolicyMetadataAttachDerivedError != nil {
		return contract.Response{}, plystraPolicyMetadataAttachDerivedError
	}
	ctx, plystraPolicyMetadataAttachRejectedError := invocationcontext.WithMetadata(ctx, "policy.rejected", bool(request.Reject), 5)
	if plystraPolicyMetadataAttachRejectedError != nil {
		return contract.Response{}, plystraPolicyMetadataAttachRejectedError
	}
	ctx, plystraPolicyMetadataAttachLiteralError := invocationcontext.WithMetadata(ctx, "policy.literal", bool(false), 5)
	if plystraPolicyMetadataAttachLiteralError != nil {
		return contract.Response{}, plystraPolicyMetadataAttachLiteralError
	}
	return h.target.Invoke(ctx, request)
}
