// Code generated by Plystra CLI. DO NOT EDIT.

package ordercreatev1

import (
	"context"
	"errors"
	"time"

	policycheckv1 "example.com/acme/project/generated/go/clients/policy/check/v1"
	contract "example.com/acme/project/generated/go/contracts/order/create/v1"
	policycheckv1contract "example.com/acme/project/generated/go/contracts/policy/check/v1"
	kernelinvocation "github.com/plystra/kernel/invocation"
)

// Handle is the opaque generated application path to one exact canonical Capability.
type Handle struct {
	target              kernelinvocation.Handle[contract.Request, contract.Response]
	policycheckv1Client policycheckv1.Client
}

// New binds the application path to its caller-scoped canonical Kernel handle.
func New(
	target kernelinvocation.Handle[contract.Request, contract.Response],
	policycheckv1Client policycheckv1.Client,
) Handle {
	return Handle{
		target:              target,
		policycheckv1Client: policycheckv1Client,
	}
}

// Available reports whether assembly selected the canonical provider.
func Available(handle Handle) bool {
	return handle.Available()
}

// Available reports whether assembly selected the canonical provider.
func (h Handle) Available() bool {
	return h.target.Available()
}

// Invoke runs the application path for order.create/v1 and dispatches its canonical ID.
func (h Handle) Invoke(ctx context.Context, request contract.Request) (contract.Response, error) {
	plystraPolicyRequireCreateCheckResponse, plystraPolicyRequireCreateCheckError := plystraInvokeWithTimeout(
		ctx,
		75*time.Millisecond,
		h.policycheckv1Client.Check,
		policycheckv1contract.Request{
			Enforce:    bool(true),
			Permission: string(request.OrderID),
			RetryCount: int64(2),
		},
	)
	if plystraPolicyRequireCreateCheckError != nil {
		return contract.Response{}, plystraPolicyRequireCreateCheckError
	}
	_ = plystraPolicyRequireCreateCheckResponse
	return h.target.Invoke(ctx, request)
}

var plystraErrInvalidContext = errors.New("nil generated invocation context")

func plystraInvokeWithTimeout[Request, Response any](
	ctx context.Context,
	timeout time.Duration,
	invoke func(context.Context, Request) (Response, error),
	request Request,
) (Response, error) {
	if ctx == nil {
		var response Response
		return response, plystraErrInvalidContext
	}
	callContext, cancel := context.WithTimeout(ctx, timeout)
	defer cancel()
	return invoke(callContext, request)
}
