// Code generated by Plystra CLI. DO NOT EDIT.

package ordercreatev1

import (
	"context"
	"encoding/json"
	"errors"
	"time"

	policycheckv1 "example.com/acme/project/generated/go/clients/policy/check/v1"
	contract "example.com/acme/project/generated/go/contracts/order/create/v1"
	policycheckv1contract "example.com/acme/project/generated/go/contracts/policy/check/v1"
	invocationcontext "example.com/acme/project/generated/go/internal/invocationcontext"
	kernelinvocation "github.com/plystra/kernel/invocation"
)

// Handle is the opaque generated application path to one exact canonical Capability.
type Handle struct {
	target              kernelinvocation.Handle[contract.Request, contract.Response]
	policycheckv1Client policycheckv1.Client
}

// New binds the application path to its caller-scoped canonical Kernel handle.
func New(
	target kernelinvocation.Handle[contract.Request, contract.Response],
	policycheckv1Client policycheckv1.Client,
) Handle {
	return Handle{
		target:              target,
		policycheckv1Client: policycheckv1Client,
	}
}

// Available reports whether assembly selected the canonical provider.
func Available(handle Handle) bool {
	return handle.target.Available()
}

// Invoke runs the application path for order.create/v1 and dispatches its canonical ID.
func (h Handle) Invoke(ctx context.Context, request contract.Request) (contract.Response, error) {
	plystraPolicyNodeValuesDerivePermissionDerived := string(request.OrderID)
	ctx, plystraPolicyNodeValuesDerivePermissionError := invocationcontext.WithValue(ctx, "policy.permission", plystraPolicyNodeValuesDerivePermissionDerived, 32)
	if plystraPolicyNodeValuesDerivePermissionError != nil {
		return contract.Response{}, plystraPolicyNodeValuesDerivePermissionError
	}
	plystraPolicyNodeValuesCheckSourceResponse, plystraPolicyNodeValuesCheckSourceError := plystraInvokeWithTimeout(
		ctx,
		50*time.Millisecond,
		h.policycheckv1Client.Check,
		policycheckv1contract.Request{
			Enforce:    bool(true),
			Permission: string(plystraPolicyNodeValuesDerivePermissionDerived),
			RetryCount: int64(1),
		},
	)
	if plystraPolicyNodeValuesCheckSourceError != nil {
		return contract.Response{}, plystraPolicyNodeValuesCheckSourceError
	}
	_ = plystraPolicyNodeValuesCheckSourceResponse
	plystraPolicyNodeValuesDeriveAllowedDerived := bool(plystraPolicyNodeValuesCheckSourceResponse.Allowed)
	ctx, plystraPolicyNodeValuesDeriveAllowedError := invocationcontext.WithValue(ctx, "policy.allowed", plystraPolicyNodeValuesDeriveAllowedDerived, 5)
	if plystraPolicyNodeValuesDeriveAllowedError != nil {
		return contract.Response{}, plystraPolicyNodeValuesDeriveAllowedError
	}
	var plystraPolicyNodeValuesDeriveReasonDerived *string
	var plystraPolicyNodeValuesDeriveReasonError error
	if plystraPolicyNodeValuesCheckSourceResponse.Reason != nil {
		plystraPolicyNodeValuesDeriveReasonDerived = plystraPointer(string(*plystraPolicyNodeValuesCheckSourceResponse.Reason))
		ctx, plystraPolicyNodeValuesDeriveReasonError = invocationcontext.WithValue(ctx, "policy.reason", *plystraPolicyNodeValuesDeriveReasonDerived, 32)
	}
	if plystraPolicyNodeValuesDeriveReasonError != nil {
		return contract.Response{}, plystraPolicyNodeValuesDeriveReasonError
	}
	plystraPolicyNodeValuesDeriveEvidenceDerived, plystraPolicyNodeValuesDeriveEvidenceError := plystraConvertValue[map[string]any](plystraPolicyNodeValuesCheckSourceResponse)
	if plystraPolicyNodeValuesDeriveEvidenceError != nil {
		return contract.Response{}, plystraPolicyNodeValuesDeriveEvidenceError
	}
	ctx, plystraPolicyNodeValuesDeriveEvidenceError = invocationcontext.WithValue(ctx, "policy.evidence", plystraPolicyNodeValuesDeriveEvidenceDerived, 256)
	if plystraPolicyNodeValuesDeriveEvidenceError != nil {
		return contract.Response{}, plystraPolicyNodeValuesDeriveEvidenceError
	}
	plystraPolicyNodeValuesCheckDerivedRequestEvidence, plystraPolicyNodeValuesCheckDerivedError := plystraConvertValue[map[string]any](plystraPolicyNodeValuesCheckSourceResponse)
	if plystraPolicyNodeValuesCheckDerivedError != nil {
		return contract.Response{}, plystraPolicyNodeValuesCheckDerivedError
	}
	plystraPolicyNodeValuesCheckDerivedResponse, plystraPolicyNodeValuesCheckDerivedError := plystraInvokeWithTimeout(
		ctx,
		50*time.Millisecond,
		h.policycheckv1Client.Check,
		policycheckv1contract.Request{
			Credential: plystraConvertOptional(plystraPolicyNodeValuesCheckSourceResponse.Reason, func(value string) string { return string(value) }),
			Enforce:    bool(plystraPolicyNodeValuesDeriveAllowedDerived),
			Evidence:   plystraPointer(map[string]any(plystraPolicyNodeValuesCheckDerivedRequestEvidence)),
			Permission: string(plystraPolicyNodeValuesDerivePermissionDerived),
			RetryCount: int64(2),
		},
	)
	if plystraPolicyNodeValuesCheckDerivedError != nil {
		return contract.Response{}, plystraPolicyNodeValuesCheckDerivedError
	}
	_ = plystraPolicyNodeValuesCheckDerivedResponse
	return h.target.Invoke(ctx, request)
}

var plystraErrInvalidContext = errors.New("nil generated invocation context")

func plystraInvokeWithTimeout[Request, Response any](
	ctx context.Context,
	timeout time.Duration,
	invoke func(context.Context, Request) (Response, error),
	request Request,
) (Response, error) {
	if ctx == nil {
		var response Response
		return response, plystraErrInvalidContext
	}
	callContext, cancel := context.WithTimeout(ctx, timeout)
	defer cancel()
	return invoke(callContext, request)
}

var plystraErrInvalidGeneratedValue = errors.New("invalid generated invocation value")

func plystraConvertValue[Target any](value any) (Target, error) {
	var result Target
	data, err := json.Marshal(value)
	if err != nil {
		return result, plystraErrInvalidGeneratedValue
	}
	if err := json.Unmarshal(data, &result); err != nil {
		return result, plystraErrInvalidGeneratedValue
	}
	return result, nil
}

func plystraPointer[Value any](value Value) *Value {
	return &value
}

func plystraConvertOptional[Source, Target any](value *Source, convert func(Source) Target) *Target {
	if value == nil {
		return nil
	}
	result := convert(*value)
	return &result
}
