// Code generated by Plystra CLI. DO NOT EDIT.

package ordercreatev1

import (
	"context"
	"errors"
	"time"

	policycheckv1 "example.com/acme/project/generated/go/clients/policy/check/v1"
	contract "example.com/acme/project/generated/go/contracts/order/create/v1"
	policycheckv1contract "example.com/acme/project/generated/go/contracts/policy/check/v1"
	invocationcontext "example.com/acme/project/generated/go/internal/invocationcontext"
	kernelinvocation "github.com/plystra/kernel/invocation"
)

// Handle is the opaque generated application path to one exact canonical Capability.
type Handle struct {
	target              kernelinvocation.Handle[contract.Request, contract.Response]
	policycheckv1Client policycheckv1.Client
}

// New binds the application path to its caller-scoped canonical Kernel handle.
func New(
	target kernelinvocation.Handle[contract.Request, contract.Response],
	policycheckv1Client policycheckv1.Client,
) Handle {
	return Handle{
		target:              target,
		policycheckv1Client: policycheckv1Client,
	}
}

// Available reports whether assembly selected the canonical provider.
func Available(handle Handle) bool {
	return handle.Available()
}

// Available reports whether assembly selected the canonical provider.
func (h Handle) Available() bool {
	return h.target.Available()
}

// Invoke runs the application path for order.create/v1 and dispatches its canonical ID.
func (h Handle) Invoke(ctx context.Context, request contract.Request) (contract.Response, error) {
	plystraPolicyConditionsCheckResponse, plystraPolicyConditionsCheckError := plystraInvokeWithTimeout(
		ctx,
		50*time.Millisecond,
		h.policycheckv1Client.Check,
		policycheckv1contract.Request{
			Enforce:    bool(true),
			Permission: string("order.create"),
			RetryCount: int64(2),
		},
	)
	_ = plystraPolicyConditionsCheckResponse
	if plystraPolicyConditionsCheckError != nil {
		return contract.Response{}, plystraConditionalError{code: contract.ErrPolicyFailed, message: "Policy provider failed."}
	}
	if !plystraPolicyConditionsCheckResponse.Allowed {
		return contract.Response{}, plystraConditionalError{code: contract.ErrPolicyFailed, message: "Policy denied the request."}
	}
	if request.Note == nil {
		return contract.Response{}, plystraConditionalError{code: contract.ErrPolicyFailed, message: "Order note is required."}
	}
	if request.Reject {
		return contract.Response{}, plystraConditionalError{code: contract.ErrPolicyFailed, message: "Order was explicitly rejected."}
	}
	_, plystraPolicyConditionsContextBlockedPresent := invocationcontext.Value[string](ctx, "policy.block")
	if plystraPolicyConditionsContextBlockedPresent {
		return contract.Response{}, plystraConditionalError{code: contract.ErrPolicyFailed, message: "Policy context blocked the request."}
	}
	response, invocationError := h.target.Invoke(ctx, request)
	if invocationError != nil {
		return contract.Response{}, invocationError
	}
	if responseError := plystraValidateResponse(response); responseError != nil {
		return contract.Response{}, responseError
	}
	return response, nil
}

var plystraErrInvalidProviderResponse = errors.New("invalid canonical Provider response")

func plystraValidateResponse(response contract.Response) error {
	return nil
}

// TransportErrorInput is the immutable data-free failure projection consumed by generated external adapters.
type TransportErrorInput struct {
	semanticErrorCode string
	kernelErrorClass  kernelinvocation.ErrorCode
	kernelDetailCode  string
}

// Valid reports whether the projection contains exactly one closed semantic or Kernel failure classification.
func (i TransportErrorInput) Valid() bool {
	if i.semanticErrorCode != "" {
		return i.kernelErrorClass == "" && i.kernelDetailCode == "" && plystraDeclaredSemanticError(i.semanticErrorCode)
	}
	if !i.kernelErrorClass.Valid() || !kernelinvocation.ValidDetailCode(i.kernelDetailCode) {
		return false
	}
	return i.kernelErrorClass != kernelinvocation.ErrorDenied || i.kernelDetailCode != ""
}

// SemanticErrorCode returns one declared canonical semantic code or an empty string.
func (i TransportErrorInput) SemanticErrorCode() string {
	if !i.Valid() {
		return ""
	}
	return i.semanticErrorCode
}

// KernelErrorClass returns one closed Kernel failure class or an empty string.
func (i TransportErrorInput) KernelErrorClass() string {
	if !i.Valid() {
		return ""
	}
	return i.kernelErrorClass.String()
}

// KernelDetailCode returns the optional bounded Kernel detail code or an empty string.
func (i TransportErrorInput) KernelDetailCode() string {
	if !i.Valid() {
		return ""
	}
	return i.kernelDetailCode
}

// SafeTransportError projects one canonical invocation failure without retaining its text, cause, payload, or Provider data.
func SafeTransportError(err error) (input TransportErrorInput) {
	input = plystraInternalTransportError()
	defer func() {
		if recover() != nil || !input.Valid() {
			input = plystraInternalTransportError()
		}
	}()
	if err == nil {
		return input
	}
	var semantic plystraSemanticErrorCoder
	if errors.As(err, &semantic) {
		code := semantic.SemanticErrorCode()
		if plystraDeclaredSemanticError(code) {
			return TransportErrorInput{semanticErrorCode: code}
		}
		return input
	}
	var classified *kernelinvocation.Error
	if errors.As(err, &classified) {
		return TransportErrorInput{kernelErrorClass: classified.Code(), kernelDetailCode: classified.DetailCode()}
	}
	switch {
	case errors.Is(err, context.DeadlineExceeded):
		return TransportErrorInput{kernelErrorClass: kernelinvocation.ErrorTimeout}
	case errors.Is(err, context.Canceled):
		return TransportErrorInput{kernelErrorClass: kernelinvocation.ErrorCancelled}
	default:
		return input
	}
}

type plystraSemanticErrorCoder interface {
	error
	SemanticErrorCode() string
}

func plystraDeclaredSemanticError(code string) bool {
	switch code {
	case "policy_failed":
		return true
	default:
		return false
	}
}

func plystraInternalTransportError() TransportErrorInput {
	return TransportErrorInput{kernelErrorClass: kernelinvocation.ErrorInternal}
}

var plystraErrInvalidContext = errors.New("nil generated invocation context")

func plystraInvokeWithTimeout[Request, Response any](
	ctx context.Context,
	timeout time.Duration,
	invoke func(context.Context, Request) (Response, error),
	request Request,
) (Response, error) {
	if ctx == nil {
		var response Response
		return response, plystraErrInvalidContext
	}
	callContext, cancel := context.WithTimeout(ctx, timeout)
	defer cancel()
	return invoke(callContext, request)
}

type plystraConditionalError struct {
	code    contract.ErrorCode
	message string
}

func (e plystraConditionalError) Error() string { return e.message }

func (e plystraConditionalError) Unwrap() error { return e.code }
