// Code generated by Plystra CLI. DO NOT EDIT.

import { resolveUnaryMethod } from "../../../descriptors.js";
import { createRuntime, type ClientOptions, type Runtime } from "../../../runtime.js";
import {
  bindOperationMethod as bindCanonicalOperationMethod,
  type Operation,
} from "../../../operations/email/send/v1.js";
export type { ErrorCode, Operation, Request, Response } from "../../../operations/email/send/v1.js";

export const capabilityID = "compat.send/v1";
export const targetCapabilityID = "email.send/v1";
export const contractDigest = "sha256:9b01b630e8fae8883269196c6888aefec9416b903ac0076c08695e8de86b7a07";
const method = resolveUnaryMethod(
  "plystra.generated.compat.send.v1.CompatSendV1Service",
  "Invoke",
  "plystra.generated.email.send.v1.EmailSendV1Request",
  "plystra.generated.email.send.v1.EmailSendV1Response",
);

export function bindOperation(runtime: Runtime): Operation {
  return bindCanonicalOperationMethod(runtime, method);
}

export function createOperation(options: ClientOptions): Operation {
  return bindOperation(createRuntime(options));
}
