package plugincreate

import (
	"fmt"
	"go/format"
	"go/token"
	"strings"
	"unicode"

	"github.com/plystra/cli/internal/atomicfs"
)

const pluginTemplate = `package %s

import configuration %q

// Config is the generated configuration type for %s.
type Config = configuration.%sConfig

// Plugin implements %s.
type Plugin struct{}

// New constructs the %s plugin.
func New(_ Config) *Plugin {
	return &Plugin{}
}
`

const pluginTestTemplate = `package %s

import "testing"

func TestNew(t *testing.T) {
	t.Parallel()

	if plugin := New(Config{}); plugin == nil {
		t.Fatal("New returned nil")
	}
}
`

const configurationTemplate = `// Code generated by Plystra CLI. DO NOT EDIT.

package configuration

// %sConfig is generated from %s/plugin.yaml.
type %sConfig struct{}
`

const registrationTemplate = `// Code generated by Plystra CLI. DO NOT EDIT.

package assembly

import %s %q

// %sPluginID is the immutable identity declared by %s/plugin.yaml.
const %sPluginID = %q

// New%sPlugin binds the generated assembly to the plugin constructor.
func New%sPlugin(config %s.Config) *%s.Plugin {
	return %s.New(config)
}
`

const pluginReadmeTemplate = `# %s plugin

Plugin ID: ` + "`%s`" + `

This is a root-level plugin in the ` + "`%s`" + ` Go Module. Its declarative source is ` + "`plugin.yaml`" + `, and generated configuration and assembly bindings are committed under the module's ` + "`generated/`" + ` directory.

## Capabilities

This plugin starts without capabilities. Add a custom capability with:

` + "```text" + `
plystra capability create <capability-name>
` + "```" + `

Implement an existing canonical capability with:

` + "```text" + `
plystra capability implement <capability-name>/vN
` + "```" + `
`

func renderScaffold(modulePath, name, id string) ([]atomicfs.Write, error) {
	packageName := goPackageName(name)
	goName := exportedName(name)
	pluginSource, err := format.Source([]byte(fmt.Sprintf(
		pluginTemplate,
		packageName,
		modulePath+"/generated/configuration",
		id,
		goName,
		id,
		id,
	)))
	if err != nil {
		return nil, fmt.Errorf("format plugin source: %w", err)
	}
	testSource, err := format.Source([]byte(fmt.Sprintf(pluginTestTemplate, packageName)))
	if err != nil {
		return nil, fmt.Errorf("format plugin test: %w", err)
	}
	configurationSource, err := format.Source([]byte(fmt.Sprintf(configurationTemplate, goName, name, goName)))
	if err != nil {
		return nil, fmt.Errorf("format configuration source: %w", err)
	}
	registrationSource, err := format.Source([]byte(fmt.Sprintf(
		registrationTemplate,
		packageName,
		modulePath+"/"+name,
		goName,
		name,
		goName,
		id,
		goName,
		goName,
		packageName,
		packageName,
		packageName,
	)))
	if err != nil {
		return nil, fmt.Errorf("format assembly registration: %w", err)
	}

	return []atomicfs.Write{
		{Path: name + "/plugin.yaml", Data: []byte("id: " + id + "\n\nconfig: {}\n"), Mode: 0o644, MustNotExist: true, ParentMustNotExist: true},
		{Path: name + "/plugin.go", Data: pluginSource, Mode: 0o644, MustNotExist: true},
		{Path: name + "/plugin_test.go", Data: testSource, Mode: 0o644, MustNotExist: true},
		{Path: name + "/README.md", Data: []byte(fmt.Sprintf(pluginReadmeTemplate, title(name), id, modulePath)), Mode: 0o644, MustNotExist: true},
		{Path: "generated/configuration/" + name + "_gen.go", Data: configurationSource, Mode: 0o644, MustNotExist: true},
		{Path: "generated/assembly/" + name + "_gen.go", Data: registrationSource, Mode: 0o644, MustNotExist: true},
	}, nil
}

func goPackageName(name string) string {
	value := strings.ReplaceAll(name, "-", "")
	if token.Lookup(value).IsKeyword() {
		return value + "plugin"
	}
	return value
}

func exportedName(name string) string {
	parts := strings.Split(name, "-")
	for index, part := range parts {
		parts[index] = strings.ToUpper(part[:1]) + part[1:]
	}
	return strings.Join(parts, "")
}

func title(name string) string {
	words := strings.Split(name, "-")
	for index, word := range words {
		runes := []rune(word)
		runes[0] = unicode.ToUpper(runes[0])
		words[index] = string(runes)
	}
	return strings.Join(words, " ")
}
