// Code generated by Plystra CLI. DO NOT EDIT.

import {
  createRuntime,
  hasOwn,
  invoke,
  isJSONValue,
  isPlainObject,
  PlystraError,
  type ClientOptions,
  type JSONValue,
  type RequestOptions,
  type Runtime,
} from "../../../runtime.js";

export const capabilityID = "email.send/v1";
export const contractDigest = "sha256:836377411dbd56a4b2e7441377ce8e3f093d1e8758677ae44b8062bb69c6a8a5";
const routePath = "api/v1/capabilities/email.send/v1/invoke";

export interface Request {
  readonly "metadata"?: Readonly<Record<string, JSONValue>>;
  readonly "priority": "normal" | "urgent";
  readonly "retries"?: -1 | 0 | 2;
  readonly "tags": ReadonlyArray<string>;
  readonly "to": string;
}

export interface Response {
  readonly "accepted": boolean;
  readonly "latency"?: number;
}

export type ErrorCode = "invalid_recipient" | "temporarily_unavailable";

function isRequest(value: unknown): value is Request {
  return (
    isPlainObject(value) &&
    Object.keys(value).every((key) => key === "metadata" || key === "priority" || key === "retries" || key === "tags" || key === "to") &&
    (!hasOwn(value, "metadata") || isPlainObject(value["metadata"]) && isJSONValue(value["metadata"])) &&
    hasOwn(value, "priority") && (value["priority"] === "normal" || value["priority"] === "urgent") &&
    (!hasOwn(value, "retries") || Number.isSafeInteger(value["retries"]) && (value["retries"] === -1 || value["retries"] === 0 || value["retries"] === 2)) &&
    hasOwn(value, "tags") && Array.isArray(value["tags"]) && value["tags"].every((item) => typeof item === "string") &&
    hasOwn(value, "to") && typeof value["to"] === "string"
  );
}

function isResponse(value: unknown): value is Response {
  return (
    isPlainObject(value) &&
    Object.keys(value).every((key) => key === "accepted" || key === "latency") &&
    hasOwn(value, "accepted") && typeof value["accepted"] === "boolean" &&
    (!hasOwn(value, "latency") || typeof value["latency"] === "number" && Number.isFinite(value["latency"]))
  );
}

export type Operation = (
  request: Request,
  options?: RequestOptions,
) => Promise<Response>;

export function bindOperation(runtime: Runtime): Operation {
  return async (request, options = {}) => {
    let requestIsValid = false;
    try {
      requestIsValid = isRequest(request);
    } catch {
      requestIsValid = false;
    }
    if (!requestIsValid) {
      throw new TypeError("request does not match email.send/v1");
    }
    const response = await invoke(runtime, routePath, request, options);
    if (!isResponse(response)) {
      throw new PlystraError(200, "invalid_response");
    }
    return response;
  };
}

export function createOperation(options: ClientOptions): Operation {
  return bindOperation(createRuntime(options));
}
