// Code generated by Plystra CLI. DO NOT EDIT.

import {
  createRuntime,
  hasOwn,
  invoke,
  isSignedInteger,
  isJSONValue,
  isPlainObject,
  PlystraError,
  type ClientOptions,
  type ErrorContract,
  type JSONValue,
  type MessageCodec,
  type RequestOptions,
  type Runtime,
} from "../../../runtime.js";
import { resolveMessage, resolveUnaryMethod } from "../../../descriptors.js";

export const capabilityID = "email.send/v1";
export const contractDigest = "sha256:f8a801ed064ea942c0a6999e45359fba607be8d62fabce6d6ebec8909a5b3833";
const method = resolveUnaryMethod(
  "plystra.generated.email.send.v1.EmailSendV1Service",
  "Invoke",
  "plystra.generated.email.send.v1.EmailSendV1Request",
  "plystra.generated.email.send.v1.EmailSendV1Response",
);
const requestCodec: MessageCodec = {
  fields: [
    {
      canonicalName: "checkpoints",
      protobufJSONName: "checkpoints",
      kind: "array",
      items: "integer",
      required: false,
    },
    {
      canonicalName: "metadata",
      protobufJSONName: "metadata",
      kind: "object",
      required: false,
    },
    {
      canonicalName: "offset",
      protobufJSONName: "offset",
      kind: "integer",
      required: false,
    },
    {
      canonicalName: "priority",
      protobufJSONName: "priority",
      kind: "string",
      required: true,
      enum: [
        { canonical: "normal", protobufName: "EMAILSENDV1REQUESTPRIORITYENUM_VALUE_82FBB169E798324839513347C048ECC9C91A6574588E1760F13D6B9650C328BF" },
        { canonical: "urgent", protobufName: "EMAILSENDV1REQUESTPRIORITYENUM_VALUE_7466B39FCDA68E26B86694D2BF85F5A0AB189B2F26675DA303A0B3FBABA19CED" },
      ],
    },
    {
      canonicalName: "retries",
      protobufJSONName: "retries",
      kind: "integer",
      required: false,
      enum: [
        { canonical: -9223372036854775808n, protobufName: "EMAILSENDV1REQUESTRETRIESENUM_VALUE_85386477F3AF47E4A0B308EE3B3A688DF16E8B2228105DD7D4DCD42A9807CB78" },
        { canonical: 0n, protobufName: "EMAILSENDV1REQUESTRETRIESENUM_VALUE_5FECEB66FFC86F38D952786C6D696C79C2DBC239DD4E91B46729D73A27FB57E9" },
        { canonical: 9223372036854775807n, protobufName: "EMAILSENDV1REQUESTRETRIESENUM_VALUE_B34A1C30A715F6BF8B7243AFA7FAB883CE3612B7231716BDCBBDC1982E1AED29" },
      ],
    },
    {
      canonicalName: "tags",
      protobufJSONName: "tags",
      kind: "array",
      items: "string",
      required: true,
    },
    {
      canonicalName: "to",
      protobufJSONName: "to",
      kind: "string",
      required: true,
    },
  ],
};
const responseCodec: MessageCodec = {
  fields: [
    {
      canonicalName: "accepted",
      protobufJSONName: "accepted",
      kind: "boolean",
      required: true,
    },
    {
      canonicalName: "latency",
      protobufJSONName: "latency",
      kind: "number",
      required: false,
    },
    {
      canonicalName: "positions",
      protobufJSONName: "positions",
      kind: "array",
      items: "integer",
      required: false,
    },
    {
      canonicalName: "revision",
      protobufJSONName: "revision",
      kind: "integer",
      required: false,
    },
  ],
};

const errorDetailDescriptor = resolveMessage("plystra.generated.transport.v1.PlystraErrorDetail");
const semanticErrorCodes = Object.freeze([
  "invalid_recipient",
  "temporarily_unavailable",
]);

export interface Request {
  readonly "checkpoints"?: ReadonlyArray<bigint>;
  readonly "metadata"?: Readonly<Record<string, JSONValue>>;
  readonly "offset"?: bigint;
  readonly "priority": "normal" | "urgent";
  readonly "retries"?: -9223372036854775808n | 0n | 9223372036854775807n;
  readonly "tags": ReadonlyArray<string>;
  readonly "to": string;
}

export interface Response {
  readonly "accepted": boolean;
  readonly "latency"?: number;
  readonly "positions"?: ReadonlyArray<bigint>;
  readonly "revision"?: bigint;
}

export type ErrorCode = "invalid_recipient" | "temporarily_unavailable";

function isRequest(value: unknown): value is Request {
  return (
    isPlainObject(value) &&
    Object.keys(value).every((key) => key === "checkpoints" || key === "metadata" || key === "offset" || key === "priority" || key === "retries" || key === "tags" || key === "to") &&
    (!hasOwn(value, "checkpoints") || Array.isArray(value["checkpoints"]) && value["checkpoints"].every((item) => isSignedInteger(item))) &&
    (!hasOwn(value, "metadata") || isPlainObject(value["metadata"]) && isJSONValue(value["metadata"])) &&
    (!hasOwn(value, "offset") || isSignedInteger(value["offset"])) &&
    hasOwn(value, "priority") && (value["priority"] === "normal" || value["priority"] === "urgent") &&
    (!hasOwn(value, "retries") || isSignedInteger(value["retries"]) && (value["retries"] === -9223372036854775808n || value["retries"] === 0n || value["retries"] === 9223372036854775807n)) &&
    hasOwn(value, "tags") && Array.isArray(value["tags"]) && value["tags"].every((item) => typeof item === "string") &&
    hasOwn(value, "to") && typeof value["to"] === "string"
  );
}

function isResponse(value: unknown): value is Response {
  return (
    isPlainObject(value) &&
    Object.keys(value).every((key) => key === "accepted" || key === "latency" || key === "positions" || key === "revision") &&
    hasOwn(value, "accepted") && typeof value["accepted"] === "boolean" &&
    (!hasOwn(value, "latency") || typeof value["latency"] === "number" && Number.isFinite(value["latency"])) &&
    (!hasOwn(value, "positions") || Array.isArray(value["positions"]) && value["positions"].every((item) => isSignedInteger(item))) &&
    (!hasOwn(value, "revision") || isSignedInteger(value["revision"]))
  );
}

export type Operation = (
  request: Request,
  options?: RequestOptions,
) => Promise<Response>;

/** @internal */
export function bindOperation(runtime: Runtime): Operation {
  return bindOperationMethod(runtime, method, capabilityID);
}

/** @internal */
export function bindOperationMethod(runtime: Runtime, operationMethod: typeof method, requestedCapabilityID: string): Operation {
  const errorContract: ErrorContract = {
    requestedCapabilityID,
    canonicalCapabilityID: capabilityID,
    semanticErrorCodes,
    detailDescriptor: errorDetailDescriptor,
  };
  return async (request, options = {}) => {
    let requestIsValid = false;
    try {
      requestIsValid = isRequest(request);
    } catch {
      requestIsValid = false;
    }
    if (!requestIsValid) {
      throw new TypeError("request does not match email.send/v1");
    }
    const response = await invoke(runtime, operationMethod, requestCodec, responseCodec, errorContract, request, options);
    if (!isResponse(response)) {
      throw new PlystraError(200, "invalid_response");
    }
    return response;
  };
}

export function createOperation(options: ClientOptions): Operation {
  return bindOperation(createRuntime(options));
}
